### ISSUE TITLE
[QUESTION] Sprint

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1024]
## Login
<img width="1200" alt="Capture d’écran 2019-12-02 à 09 46 39" src="https://user-images.githubusercontent.com/47273014/69944948-cc40fa00-14e8-11ea-94ad-231c0e7074c9.png">

- [ ] phrase à reprendre

**Comment by Jasminemeurin** [comment]
Le visuel est beaucoup mieux mais attention aux éléments de langage !

je propose: 

-Favoriser les échanges d’informations entre les acteurs de la protection juridique des majeurs,
-Offrir une meilleure visibilité sur l'activité en temps réel des mandataires,
-Assister les magistrats dans leur décision d'attribution d'une mesure,
-Obtenir des informations précises pour connaître, anticiper l'évolution des
besoins et piloter au mieux la politique publique,
-Optimiser l’accompagnement de la personne à protéger.
