### ISSUE TITLE
[SERVICE] edition d'un service

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1049]
<img width="520" alt="Capture d’écran 2019-12-04 à 09 36 18" src="https://user-images.githubusercontent.com/47273014/70126550-93845a80-1679-11ea-9c4b-2ac02bcc4677.png">

**Comment by kwiss** [comment]
@tglatt tu l'as vu ou ce bug ?

**Comment by tglatt** [comment]
@kwiss, en production

**Comment by tglatt** [comment]
#1052
