### ISSUE TITLE
[MANDATAIRE][INDIVIDUEL] Pas de correlation entre code postal et Ville dans "mon profil"

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1062]
Date de détection : 04/12/2019
Version de recette : https://v25-9-2-emjpm.dev.fabrique.social.gouv.fr
Profil : Mandataire individuel
Description du problème :  
Possibilité de mettre un code postal parisien et Bordeaux en Ville associé à ce CP dans modifer "mes informations"

![image](https://user-images.githubusercontent.com/53866545/70157000-11198c00-16b5-11ea-924f-33494196944a.png)

![image](https://user-images.githubusercontent.com/53866545/70157010-1676d680-16b5-11ea-9ac7-be7ef4ca2684.png)

**Comment by tglatt** [comment]
duplicate #939
