### ISSUE TITLE
ETQ magistrat, je peux faire une recherche de MJPM dans un moteur de recherche

### ISSUE THREAD

**Issue by Jasminemeurin** [SocialGouv/emjpm#1083]
Je suis un magistrat et j'ai déjà une idée du nom du MJPM que je vais désigner. 
Je veux vérifier sa disponibilité et pour ne pas rechercher dans la liste, je veux pouvoir inscrire son nom dans une fonctionnalité qui me permettra d'accéder directement à ses infos.

**Comment by tglatt** [comment]
#1169
