### ISSUE TITLE
ETQ service, quand je crée une antenne, je ne peux pas indiquer de "préférences géographiques"

### ISSUE THREAD

**Issue by Jasminemeurin** [SocialGouv/emjpm#1091]
dans "Vos informations", j'ai l'info "préférences géographiques" qui doit être remplacée par "informations à destination du magistrat" et lorsque je clique sur "Voir l'antenne" puis "Modifier les informations de l'antenne", il n'y a pas de rubrique "informations à destination du magistrat" 'ou pour le moment "préférences géographiques")

**Comment by tglatt** [comment]
Nous avons décidé que le magistrat sélectionnait un service et non une antenne. Il est donc cohérent que les informations soient au niveau du service.
@Jasminemeurin, si tu n'es pas d'accord, je te laisse réouvrir le le ticket
