### ISSUE TITLE
[MANDATAIRES][INDIVIDUELS] Modifications des informations du profil impossible

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1252]
**Date d'ouverture** 19/12/2019
**Version de détection** https://v25-12-1-emjpm.dev.fabrique.social.gouv.fr/
**Description détaillées du bug** Impossible de modifier les informations du profil mandataire individuel
Lorsque je tente d'ajouter un secrétariat au mandataire, lorque l'on appui sur "enregistrer", rien ne se passe et si on revient à une autre page on constate que la modification n'est effectivement pas prise en compte
Ceci est valable pour tous les champs modifiables dans "vos informations". Cependant la modification d'une mesure attribuée fonctionne.

Voici les erreurs constatées (erreurs 404 niveau serveur) :  

![image](https://user-images.githubusercontent.com/53866545/71180699-01807280-2273-11ea-8f93-9053c5b4fc29.png)

**Comment by gershon** [comment]
Je ne reproduis pas en local (et j'ai pas de diff de metadata avec un hasura export), @kwiss @tglatt vous avez une idée?

**Comment by tglatt** [comment]
fix
