### ISSUE TITLE
 [MANDATAIRES][INDIVIDUELS] Si je tente de rentrer une mesure mais que j'annule cette opération, l'utilisateur se retrouve sur une page blanche 404 NOT FOUND

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1255]
**Date d'ouverture** 19/12/2019
**Version de détection** https://v25-12-1-emjpm.dev.fabrique.social.gouv.fr/
**Profil** Individuel
**Description détaillées du bug** Si un mandataire clique sur "ajouter une mesure", puis décide d'annuler cette opération, on est redirigé vers une page blanche 404 :

![image](https://user-images.githubusercontent.com/53866545/71182307-2c1ffa80-2276-11ea-9cc8-c848d1586907.png)

a noter que l'URL change, c'est de là que le problème semble venir (un "s" se rajoute à l'URL) :  
https://v25-12-1-emjpm.dev.fabrique.social.gouv.fr/mandatairess

![image](https://user-images.githubusercontent.com/53866545/71182469-6c7f7880-2276-11ea-9bc5-9466bb70dde1.png)

**Comment by tglatt** [comment]
fix
