### ISSUE TITLE
[MANDATAIRES][INDIVIDUELS] Impossible d'ajouter une mesure manuellement (postgres query error)

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1256]
**Date d'ouverture** 19/12/2019
**Version de détection** https://v25-12-1-emjpm.dev.fabrique.social.gouv.fr/
**Profil** Individuel
**Description détaillées du bug**
Lorsque l'on clique sur "ajouter une mesure" et que l'on rempli tous les champs puis que l'on enregistre il n'y a aucun message d'erreur et on retombe sur la page "vos mesures". 
Cependant, cette mesure n'apparaît nulle part et le nombre de mesures ne change pas (il reste fixe ici à 42/43 alors que j'ai créé deux mesures entre temps)

![image](https://user-images.githubusercontent.com/53866545/71183253-f1b75d00-2277-11ea-9239-b61befc22a8b.png)

**Comment by gershon** [comment]
@tglatt @kwiss strictement aucune idée pour ma part, je vous laisse regarder.

**Comment by tglatt** [comment]
fix
