### ISSUE TITLE
[MANDATAIRES][INDIVIDUELS] Import fichier ocmi KO (il est indiqué que 31 mesures vont être joutées mais il n'en est rien) et pas de mail généré

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1262]
**Date d'ouverture** 19/12/2019
**Version de détection** https://v25-12-1-emjpm.dev.fabrique.social.gouv.fr/
**Profil** Individuel
**Description détaillées du bug** Import fichier ocmi KO, il est indiqué que 31 mesures vont être joutées mais il n'en est rien :
- Le profil reste à 42/43 mesures 
- aucun mail dans mailtrap https://mailtrap.io/inboxes/708446/messages

=> Si on réitère l'opération, cela est toujours en succès et cela ne tiens évidemment pas compte du précédent import. J'ai tenté un 2nd import avec le même fichier et voici le résultat affiché (et aucune mesure ajoutée) :  

![image](https://user-images.githubusercontent.com/53866545/71185332-88d1e400-227b-11ea-9cea-96840b7b59cd.png)

On retrouve le Graphql error :  

![image](https://user-images.githubusercontent.com/53866545/71185462-c171bd80-227b-11ea-9a22-ae9cb98049bf.png)

- fichier ocmi de test non supporté par GitHub, je peu le fournir sur demande pour analyse

**Comment by gershon** [comment]
Et impossible de reproduire en local, sinon je reproduis aussi en recette avec n'importe quel fichier d'import donc ca ne doit pas venir des fichiers. C'est surement lié aux autres `postgres query error`, @tglatt @kwiss une idée ?

**Comment by tglatt** [comment]
fix
