### ISSUE TITLE
[MANDATAIRES][INDIVIDUELS] La carte de géolocalisation est bonne mais la localisation exacte de la mesure n'apparaît pas

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1281]
**Date d'ouverture** 20/12/2019
**Version de détection** https://v25-13-0-emjpm.dev.fabrique.social.gouv.fr/
**Profil** test@individuelsupport.com / mdp Test12345!
**Description détaillées du bug**
Ajout manuelle de la mesure
Voilà dans la carte (zooms et dézooms tentés, même résultat), la bonne zone apparaît mais pas d'icône d'indication :  

![image](https://user-images.githubusercontent.com/53866545/71260733-e299e300-233b-11ea-8423-70399a6fa679.png)

**Comment by kwiss** [comment]
c'est normal c'est une mesure auto géolocalisé via le code postal et la ville, ce qui entrain des confusion de geolocalisation etc sans données correctes dans un import il y a peu de chance que les mesures soient bien géolocalisé, sauf si on édite à la main l'adresse d'une mesure
