### ISSUE TITLE
[MANDATAIRES][INDIVIDUELS] Renouvellement mot de passe KO

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1282]
**Date d'ouverture** 20/12/2019
**Version de détection** https://v25-13-0-emjpm.dev.fabrique.social.gouv.fr/
**Profil** test@individuelsupport.com / mdp Test12345!
**Description détaillées du bug**
Demande de réinitialisation de mot de passe sute à un oubli.
Le mail est bien envoyé avec le lien :  
"Bonjour,

Vous avez demandé le changement de mot de passe.

Votre identifiant est: test@individuelsupport.com Veuillez cliquer sur le lien suivant: réinitialiser mon mot de passe.

Bien à vous."

Mais lorsque je clique sur le lien je retourne sur la page de connexion : https://v25-13-0-emjpm.dev.fabrique.social.gouv.fr/

Cela m'était remonté par certains mandataires alors que cela fonctionnait très bien pour d'autres.. Cela est sûrement lié aux différents PC et protections

**Comment by kwiss** [comment]
@clement-support si tu peux mettre le lien ça serait top

**Comment by kwiss** [comment]
il me semble que c'est uniquement dans le cas des env de test que le mail n'a pas le token
