### ISSUE TITLE
[non prioritaire][DIRECTION][NATIONAL] Types de mesures affichées

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1284]
Petite question à soulever sur la pertinence des types de mesures afichées dans l'onglet "Vos mesures" - champ "Répartition des mesures à date" suite à un retour de mandataire

Les consultables sont :  

Tutelle
Curatelle renforcée
Curatelle simple
Sauvegarde de justice
Autre

Selon les infos remontées par la présidente de la chambre nationale MJPM (alors ça vaut ce que ça vaut :) ), une "Tutelle" ça n'existe pas... elle est soit aux biens soit à la personne ou au 2.

A discuter au cas ou avec les PO

**Comment by tglatt** [comment]
Cela sera repris avec le schéma de données
