### ISSUE TITLE
[INDICATEUR] Mise en place d'indicateur de suivi

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1306]
### Indicateur inscrit par département
- nb individuel inscrit + % / nb total
- nb prepose inscrit + % / nb total
- nb service inscrit + % / nb total
- nb magistrat inscrit + % / nb total
- nb DR-DD inscrit

### Indicateur connexion par type utilisateur par département
- ratio des utilsateurs avec une connexion dans le dernier mois

## Spécification
- [x] faire une page `/statistique` avec la même structure que `https://wif-dashboard.num.social.gouv.fr/national`
- [x] faire un lien de la page d'accueil vers les statistiques

**Comment by tglatt** [comment]
[https://app.zenhub.com/files/168736295/e925e910-4654-4d6e-b524-3025146a96bf/download](https://app.zenhub.com/files/168736295/e925e910-4654-4d6e-b524-3025146a96bf/download)

**Comment by tglatt** [comment]
```sql

-- mandataire / service inscrit par departement
create view view_indicateur_inscrit as select d.nom, u.type, count(m.id) from mandataires m, users u, departements d
	where m.department_id = d.id and m.user_id = u.id and u.active = true
	group by d.nom, u.type
union
select d.nom, u.type, count(distinct(sa.service_id)) from users u, departements d, service_admin sa, services s
	where u.active = true and u.id = sa.user_id and sa.service_id = s.id and s.department_id = d.id
	group by d.nom, u.type;

-- mandataire / service login dernier mois par departement
create view view_indicateur_login as select d.nom, u.type, count(m.id) from mandataires m, users u, departements d
	where m.department_id = d.id and m.user_id = u.id and u.active = true and u.last_login > now() - interval '1 month'
	group by d.nom, u.type
union
select d.nom, u.type, count(distinct(sa.service_id)) from users u, departements d, service_admin sa, services s
	where u.active = true and u.id = sa.user_id and sa.service_id = s.id and s.department_id = d.id and u.last_login > now() - interval '1 month'
	group by d.nom, u.type;
```

**Comment by kwiss** [comment]
@tglatt j'ai fait une version simple on discutera de la suite ensemble quand tu rentres
