### ISSUE TITLE
[MAGISTRAT] renouvellement de mesure

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1319]
En tant que magistrat lors de la réservation d’une mesure, je veux pouvoir préciser si la mesure à venir est un renouvellement de mesure avec conservation du même mandataire. Dans ce cas la réservation de la mesure n’impacte pas le nombre de mesure en cours ni disponible du mandataire.

**Comment by celinelr** [comment]
related to #2513

**Comment by celinelr** [comment]
Voir si le magistrat 
- cloture les mesures, si pour eux c'est une nouvelle mesure 
- nouveau numéro RG ?

**Comment by celinelr** [comment]
La mesure  garde le numéro RG mais avec une extension (ex: -1 ou -2)
et dès que le prononcement est fait l'extension de mesure réintégre celle originale / intègre de nouveau le dossier

Généralement le magistrat fait appel à e-MJPM dans un cas de renouvellement que dans l'hypothèse que l'on va décharger le mandataire
