### ISSUE TITLE
[MANDATAIRE] présomption d'absence

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1320]
ETQ MAndataire lors d’une acceptation réservation d’une mesure je souhaite pouvoir informer le magistrat d’une présomption d’absence.

**Comment by celinelr** [comment]
touche à la vue :  
- mandataire / service
   - case à cocher
   - + champs pour expliciter les raisons
- magistrat 
  -  montrer cela sur la vue mesure en cours 
  - picto / texte en rouge "présomption d'absence" et au survol afficher le commentaire du mandataire + au clic ajouter le champs sur la mesure

définition of ready : 

CETTE ISSUE NE PEUX ETRE ENTAMEE SANS LES DEVELOPPEMENTS DE L'ISSUE #2556

**Comment by celinelr** [comment]
Profil magistrat, si je clique sur un mandataire qui a suspendu son activité je propose que l'on mettre 
"Activité Suspendue" en rouge 
<img width="1273" alt="Capture d’écran 2021-11-02 à 18 20 05" src="https://user-images.githubusercontent.com/86293911/139914388-ff7296e1-ea35-4b74-90bc-f1c42f7dc77a.png">

**Comment by celinelr** [comment]
Je trouve étrange de pouvoir cliquer sur "reserver une mesure" alors qu'il y a un symbole interdit au survole du bouton "reserver une mesure" + que le bouton est grisé

Je propose de ne pas mettre d'interdit ou de mouton grisé

**Comment by celinelr** [comment]
Profil magistat remplacer "Activité Suspendue" par "Activité suspendue" (en rouge)

**Comment by celinelr** [comment]
Lorsqu'un mandataire indique sa suspension d'activité coté stat des agents ce mandataire est comptabilisé dans "Mandataires capacité non renseignée"

Je ne suis pas forcément d'accord car il indique son incapacité à prendre des mesures. Il a donc bien renseigné ce champ. Qu'en penses-tu ?

**Comment by devthejo** [comment]
@celine je suis d'accord, j'ai fais la modif

**Comment by celinelr** [comment]
top merci

**Comment by celinelr** [comment]
Profil mandataire je propose d'aussi mettre en rouge "Ne souhaite pas de nouvelles mesures pour le moment" et je propose de remplace "Ne souhaite pas de nouvelles mesures pour le moment" par "Je ne souhaite pas de nouvelles mesures pour le moment"

**Comment by celinelr** [comment]
Profil mandataire : à coté du compte de mesure je propose de mettre une pastille rouge "Activité suspendue' 
<img width="1248" alt="Capture d’écran 2021-11-02 à 18 46 58" src="https://user-images.githubusercontent.com/86293911/139918623-2a10090b-2196-4646-8b81-3565e9c12bad.png">

**Comment by celinelr** [comment]
"
|Profil magistat remplacer "Activité Suspendue" par "Activité suspendue" (en rouge)|
"
|Je trouve étrange de pouvoir cliquer sur "reserver une mesure" alors qu'il y a un symbole interdit au survole du bouton "reserver une mesure" + que le bouton est griséJe propose de ne pas mettre d'interdit ou de bouton grisé|
"

aussi , au niveau des stats, si j'ai 10 places dispo, je devrais aussi en avoir 10 dans la dispo totale non ?

![Capture d’écran 2021-11-03 à 16 45 43](https://user-images.githubusercontent.com/86293911/140096935-44ab8bf8-902a-4d7b-b353-16ded6dcf119.png)

**Comment by celinelr** [comment]
Je rajoute pour le suivi QA 

Ces champs du mandataire depuis le profil magistrat sont en rouge alors que le mandataire n'est pas en suspension d'activité
Ca me semble etre une interférence avec le développement de la suspension d'activité 

![Capture d’écran 2021-11-03 à 17 09 42](https://user-images.githubusercontent.com/86293911/140100074-c55804c4-7586-40ac-850e-7aee0d6fe5e5.png)

**Comment by celinelr** [comment]
Sur le profil agent les mandataires en suspension d'activité doivent être indiqués (comme c'est le cas sur le profil magistrat)

**Comment by celinelr** [comment]
@jo je ne vois pas sur test db 

Sur le profil agent les mandataires en suspension d'activité doivent être indiqués (comme c'est le cas sur le profil magistrat)

Bug Liste des mandataires sur le profil agent

Capture d’écran 2021-11-03 à 17 54 48

Resultat attendu Liste des mandataires sur le profil magistrat
Capture d’écran 2021-11-03 à 17 53 47

**Comment by celinelr** [comment]
En ce qui concerne les statistiques je vois que la surcapacité n'est pas prise en compte lorsque le mandataire indique une présomption d'absence. Je croyais que tu voulais que ca soit pris en compte. 
Ca ne me pause pas de problème si ca ne l'est pas.

**Comment by devthejo** [comment]
fixed
