### ISSUE TITLE
[MAGISTRAT] ETQ Magistrat je souhaite pouvoir contacter un mandataire

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1327]
Je souhaite communiquer directement avec le mandataire via e-MJPM.

En tant que mandataire, je peux communiquer directement et de façon libre au magistrat via e-MJPM soit par rapport à une mesure, soit par rapport à mon activité (demande des mandataires mais a priori pas la finalité de l’outil et pb RGPD)

**Comment by devthejo** [comment]
possibilité d'externaliser avec un lien contenant la référence (l'id de la mesure), exemple:
- lien mailto
- lien vers un appli de chat (à déterminer)

**Comment by celinelr** [comment]
gros warning, pour l'homologation, fuite des données, RGPD
On pourrait se rapprocher de julien pour voir quel outil utilise la fabrique
Pourquoi pas faire un mail to
