### ISSUE TITLE
[SERVICE][MANDATAIRE] Gestion des informations à destination des magistrat

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1373]
## Constat
Dans la version précédente, un mandataire pouvait renseigner un texte libre. (colonne `mandataires.zip` dans la DB)

Ce texte libre était visible coté magistrat.

## Besoin
Reprendre cette fonctionnalité pour les services et les mandataires.

**Comment by gershon** [comment]
Duplicate of https://github.com/SocialGouv/emjpm/issues/1375, closing.
