### ISSUE TITLE
[MAGISTRAT] Séparer en 2 la page mandataire et la page service

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1384]
## Constat
Il y a trop d'info sur la page de réservation d'une mesure. On ne voit pas les infomations sous le formulaire

## proposition
On devrait avoir une page service et une page mandataire avec:
- le panneau avec les informations du mandataire / service
- le panneau avec les informations des antennes
- la carte
- une barre d'action avec le CTA `réserver une mesure`

et une autre page avec le formulaire de réservation d'une mesure

**Comment by kwiss** [comment]
c'est ce qui était voulu...
