### ISSUE TITLE
[MANDATAIRES] Est-ce normal qu'une mesure éteinte apparaisse toujours en tête de la liste dans "vos mesures" ?

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1397]
Est-ce normal qu'une mesure éteinte apparaisse toujours en tête de la liste dans "vos mesures" ?

Là j'ai 2 mes 2 premières mesures de la liste qui sont éteintes, ensuite j'accepte une mesure en attente et celle-ci apparaît en dessous des mesures éteintes... => Comment se calcule dans eMJPM la place dans la liste de la page "vos mesures" ?

**Comment by tglatt** [comment]
link to #1531
