### ISSUE TITLE
[MANDATAIRE] Import Excel en succès dans le résultat affiché mais aucune mesure ajoutée (même après avoir rafraîchi la page)

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1399]
**Date d'ouverture** 15/01/2020
**Version de détection** https://v25-17-2-emjpm.dev.fabrique.social.gouv.fr/
**Profil** individuel-134@justice.fr
**Description détaillées du bug**

Mesures avant import :

![image](https://user-images.githubusercontent.com/53866545/72421056-1b34ad00-3780-11ea-98d8-d39d14c959b0.png)

Ensuite import Excel OK 👍 

![image](https://user-images.githubusercontent.com/53866545/72421135-3d2e2f80-3780-11ea-8ecf-eef07a051881.png)

mais pas de mise à jour et les MP ajoutés ne sont pas intégrés :  

![image](https://user-images.githubusercontent.com/53866545/72421469-d8270980-3780-11ea-9595-d8f66b71ce4d.png)

==> A noter que la 2ème fois ça a fonctionné avec le même fichier (donc cela confirme la non prise en compte de la 1ère tentative car sinon ces mesures auraient été en doublon et donc cela aurait été une mise à jour)
==> Problème peut être (sûrement !) lié à l'infra, je la laisse ouverte tout de même jusqu'à la fin de la recette ce soir

**Comment by tglatt** [comment]
Non reproduit
