### ISSUE TITLE
[INSCRIPTIONS][MANDATAIRES INDIVIDUELS] Aucune confirmation de la prise en compte de l'inscription

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1401]
**Date d'ouverture** 15/01/2020
**Version de détection** https://v25-17-2-emjpm.dev.fabrique.social.gouv.fr/
**Profil** test@individuelsupport.com
**Description détaillées du bug**

lorsque je réalise la demande d'inscription en tant que mandataire individuel, je clique sur "valider" une fois toutes mes infos renseignées (deux fois d'affilée en l'occurence à cause du problème), mais je reste sur la même page et aucune mention ou indication m'informe du succès de ma demande, cela reste figé : 

![image](https://user-images.githubusercontent.com/53866545/72437197-80999580-37a2-11ea-8d77-d978605c9a48.png)

Je vais vérifier et le mail est bien arrivé dans mailtrap 👍 

Donc je reclique sur valider pour voir et là (normal du coup), on m'indique que le SIRET existe déjà.

Je vais voir si ça le fait sur tous les profils mais à priori je ne vois pas pourquoi ce serait différent

**Comment by clement-support** [comment]
Non reproduit après retest, sûrement la magie de l'infra ou de mon PC....

**Comment by gershon** [comment]
Je ne reproduis pas non plus, je ferme l'issue.
