### ISSUE TITLE
[Inscriptions][tous profils] dans la liste déroulante de sélection des adresses, seules les rues de Toulouse sont sélectionnables au départ(et possibilité d'entrer des incohérences)

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1402]
**Date d'ouverture** 15/01/2020
**Version de détection** https://v25-17-2-emjpm.dev.fabrique.social.gouv.fr/
**Profil** test@individuelsupport.com et autres
**Description détaillées du bug**

Quand on sélectionne un TI en Ile de France par exemple celui de Pontoise et Nogent, lorsque je commence à saisir un numéro de rue, la liste déroulante me propose uniquement des rues Toulousaines quelque soit le numéro de rue que je tape : 

![image](https://user-images.githubusercontent.com/53866545/72439172-b6d91400-37a6-11ea-964c-cf84c34ae0f6.png)

![image](https://user-images.githubusercontent.com/53866545/72439461-41ba0e80-37a7-11ea-8d78-9a89ba2c932e.png)

Il me faut entrer les 3/4 de l'adresse pour avoir une liste correcte

Ensuite, il est possible de se mettre sur des TI très éloignés les uns des autres et le tout en incohérence avec mon adresse :  

![image](https://user-images.githubusercontent.com/53866545/72439897-1b48a300-37a8-11ea-9052-c4ed15e365a1.png)

**Comment by gershon** [comment]
* pour les TI très éloignés, c'est soit un bug, a voir si ca vaut vraiment le coup d'implementer une selection de TI "dynamique"
* pour les "résultats Toulouse", c'est le retour normal du service https://geo.api.gouv.fr/adresse, si vraiment problématique on peut implémenter une priorité géographique basé sur les TI sélectionnés

cc @tglatt @kwiss

**Comment by tglatt** [comment]
Pour le moment, ce n'est pas d'actualité. je ferme le ticket

**Comment by tglatt** [comment]
Avec l'implémentation de la liste blanche, cette logique va changer.
