### ISSUE TITLE
[MANDATAIRES] Faute de syntaxe 

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1408]
**Date d'ouverture** 20/01/2020
**Version de détection** 25.17.7
**Profil** tous mandataires
**Description détaillées du bug**

télécharger LA modèle Excel

![image](https://user-images.githubusercontent.com/53866545/72722891-be6e3380-3b7f-11ea-97bd-1909c29d3a18.png)

**Comment by gershon** [comment]
Fixed by https://github.com/SocialGouv/emjpm/pull/1413
