### ISSUE TITLE
[ADMIN] incohérence affichage

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1409]
**Date d'ouverture** 20/01/2020
**Version de détection** 25.17.7
**Profil** ADMIN
**Description détaillées du bug**

Lors de la "Création d'un service", il est affiché "création d'un tribunal" :

![image](https://user-images.githubusercontent.com/53866545/72723147-48b69780-3b80-11ea-881b-e8cb58ea9404.png)

**Comment by gershon** [comment]
Fixed by https://github.com/SocialGouv/emjpm/pull/1414
