### ISSUE TITLE
[ADMIN] lors de la création des services via l'admin, les adresses avec les cedex ne sont pas dans la liste déroulante

### ISSUE THREAD

**Issue by clement-support** [SocialGouv/emjpm#1410]
**Date d'ouverture** 20/01/2020
**Version de détection** 25.17.7
**Profil** ADMIN
**Description détaillées du bug**

les adresses avec les cedex ne sont pas dans la liste déroulante et ne sont donc pas sélectionnables

EXEMPLES : 

![image](https://user-images.githubusercontent.com/53866545/72723344-c1b5ef00-3b80-11ea-9b2d-41c881525d8f.png)

et toutes les adresses contenant un CP de ville "CEDEX" ont le même problème, mais la plupart sont trouvables mais sans le cedex et avec le CP de la ville

**Comment by gershon** [comment]
On utilise le service https://geo.api.gouv.fr/adresse, qui ne prends pas en compte les adresse avec CEDEX (comme les autre services de geocoding je pense). 
@clement-support si tu rencontres d'autres problèmes de résultats d'addresses comme ceux la, tu peux tester directement sur le service https://geo.api.gouv.fr/adresse pour voir si c'est un bug chez nous ou coté service, et si coté service, le marquer dans le détail du bug.
