### ISSUE TITLE
[INDICATEUR] ajout des magistrat

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1537]
La page `/indicateurs` affichent des indicateurs par type d'utilisateur d'utilisation de l'application:
- nombre d'inscrit
- nombre d'utilisateur connectés dans le dernier mois

Il faut rajouter les 2 mêmes indicateurs pour les magistrats. Un magistrat est `user` avec la colonne `type` équal à `ti`.

Il faut mettre les indicateurs des magistrats en premier sur la ligne.

https://v25-23-0-emjpm.dev.fabrique.social.gouv.fr/indicateurs

**Comment by remiroyc** [comment]
@tglatt Je vois qu'il n'y a pas de liens actuellement entre la table "tis" et "departements". En revanche il y a un code postal. Du coup je sais pas trop comment rajouter l'aggregation de manière simple. Je pense que ca serait mieux qu'on en parle avant que je me lance dans le dev.

**Comment by tglatt** [comment]
effectivement @remiroyc , il faut
- [ ] rajouter une colonne `departement_id` dans la table `tis`.
- [ ] l'initialiser en faisant correspondre les 2 premiers chiffres du code postal avec le code département. Attention, il y a un petit truc pour la Corse et les DOM-TOM; Il faudra faire des requêtes spécifiques
- [ ] Reprendre le formulaire de création / modification d'un tribunal dans l'admin pour initialiser `departement_id`.  Tu peux regarder `MandataireMesureEditForm.js`



Bref, c'est un ticket :-) #1554
