### ISSUE TITLE
[REFACTORING] Filters context

### ISSUE THREAD

**Issue by remiroyc** [SocialGouv/emjpm#1556]
**1ere étape**

Il faudrait re-localiser les valeurs du formulaire directement dans le filters context. Cela permettrait d'avoir dans le même fichier les valeurs des filtres (par défaut) et la liste des différentes valeurs que le filtre peut prendre. Actuellement cette liste est située directement dans le composant.

**2eme étape**

Etudier la possibilité d'avoir un FiltersContext générique qui permet d'avoir une unique fonction onChange.

**Comment by tglatt** [comment]
@remiroyc , lié à  https://github.com/SocialGouv/emjpm/issues/2122 ??
