### ISSUE TITLE
question(app,ui): creating an `@emjpm/ui.icons` package

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/emjpm#1650]
\following https://github.com/SocialGouv/emjpm/issues/1645

What do you think about making an actual `@emjpm/ui.icons` package in the monorepo instead of having `@styled-icons/*` dependencies twice in the repo  :

https://github.com/SocialGouv/emjpm/blob/1caf2198837d5d5360d18cefb90979b932732380/packages/app/package.json#L31-L35

https://github.com/SocialGouv/emjpm/blob/1caf2198837d5d5360d18cefb90979b932732380/packages/ui/package.json#L34-L37

It will help ensure that the dependencies are in sync.
You can see that both packages are not depending on the same icon dependencies.

**Comment by devthejo** [comment]
closing as ui merged into app
