### ISSUE TITLE
Suppression du module XLSX côté client

### ISSUE THREAD

**Issue by remiroyc** [SocialGouv/emjpm#1664]
![Capture d’écran 2020-04-10 à 12 23 01](https://user-images.githubusercontent.com/11146088/78984271-251f3f80-7b26-11ea-900f-bdbebac5429c.png)

le module XLSX est embarqué dans le bundle client. Il pèse ~700ko + cpexcel ~460ko. 
Il faudrait revoir le code de l'import pour supprimer ce package.

- [x] supprimer XLSX de l'import des mesures
- [x] supprimer XLSX de l'export MandatairesExcel.js **faire une hasura action**
- [ ] supprimer les dépendances et vérifier la taille du nouveau bundle

**Comment by tglatt** [comment]
@devthejo , le ticket est à toi, je n'aurai pas le temps de le faire :-)

**Comment by devthejo** [comment]
@remiroyc @tglatt autre proposition:
faire du lazy import (bundle secondaire importé, téléchargé par le client qu'en cas de nécessité, ou même préchargeable mais après le bundle principal, accélérant de fait le rendu et la disponibilité)
pro:
- on allège le travail du serveur et son espace disque en laissant le soin au client de générer son export
- développement plus rapide (on a quasi déjà le code)
- si on souhaite encore alléger le premier chargement on peut appliquer le procédé à d'autres librairies

con:
- il est vrai qu'avec des volumes titanesque de données le navigateur ne pourra pas suivre (mais je n'ai pas l'impression que ce soit le cas ici), il vaut mieux éviter de demander au navigateur de générer un fichier excel d'1GB

comme je débarque je passe peut être à côté de quelque chose, dîtes moi ;)
