### ISSUE TITLE
[INDIVIDUEL][SERVICE] Accepter une mesure ne fonctionne pas

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1672]
ETQ `individuel`, je ne peux pas accepter une mesure en attente

`expecting a value for non-nullable variable: mandataire_id of type: Int! in variableValues`

**Je n'ai pas pu tester ce cas pour un service, il faut le faire**

**Comment by remiroyc** [comment]
Corrigé par le #1671
