### ISSUE TITLE
Commune introuvable (code postal 31260 HIS)

### ISSUE THREAD

**Issue by tiphaineraffray** [SocialGouv/emjpm#1710]
ETQ préposé, je ne trouve pas ma ville lors de la création d'une mesure.

**Comment by tglatt** [comment]
@tiphaineraffray , on regarde ca!

**Comment by tiphaineraffray** [comment]
Bonjour,
J’ai donc ré essayé hier puis aujourd’hui mais cela ne marche toujours pas.
Les codes postaux suivants ne proposent pas de ville et n’acceptent pas la saisie libre :
49510- 49450 - 49410 - 49570
Quant au 49600 il ne propose que la commune de Beaupréau alors qu’il concerne 10 communes.
Vous remerciant par avance e vos instructions,

**Comment by tglatt** [comment]
@remiroyc , pour la ville Andrezé (49600):
- impossible de la trouver via `https://geo.api.gouv.fr/adresse`
- alors que `https://public.opendatasoft.com/explore/dataset/correspondance-code-insee-code-postal/table/?q=Andrez%C3%A9``

🤔

**Comment by tglatt** [comment]
corrigé et passé en production le 05/12/2020
