### ISSUE TITLE
[ADMIN] affichage des mesures

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1714]
Sur la page d'un utilisateurs dans l'espace administrateur, je souhaite:
- voir les mesures `Mesure en attente`, `Mesure en cours` et 'Mesure éteinte'
- avoir un filtre pour sélectionner pour sélectionner le `state`
- Par défaut, le filtre est à `Mesure en cours`
**Onglet Mesure de la page** `admin/users/1952?type=individuel&active=true`

Sur la page d'un service de l'espace administrateur, je souhaite:
- voir les mesures `Mesure en attente`, `Mesure en cours` et 'Mesure éteinte'
- avoir un filtre pour sélectionner pour sélectionner le `state`
- Par défaut, le filtre est à `Mesure en cours`

**Onglet Mesure de la page** `admin/services/49`

Dans les 2 cas, on fera une barre de filtre au dessus du tableau/

<img width="1108" alt="Capture d’écran 2020-05-04 à 15 56 38" src="https://user-images.githubusercontent.com/47273014/80973623-ec6e3f80-8e1f-11ea-916c-cdc7b562bdcd.png">

**Comment by Toub** [comment]
L'user 1952 n'existe pas sur mon dump.

**Comment by tglatt** [comment]
```sql
select user_id, mesures_en_cours, mesures_en_attente from mandataires;
```
