### ISSUE TITLE
[SERVICE][INDIVIDUEL] affichage des clusters sur la carte

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1716]
ETQ service et individuel, je souhaite voir sur la carte de mes mesures, le nombre de mesure localisées sur un point.
Si je sélectionne ce pin, je veux voir apparaitre les mesures dans la liste de gauche.

![image](https://user-images.githubusercontent.com/367762/81170664-beb20380-8fa3-11ea-8eda-391087666045.png)

**Comment by Toub** [comment]
- [x] afficher les marqueurs simple dans le même style que les clusters (avec un "1")
- [x] styler en rouge le marqueur ou cluster sélectionné

![image](https://user-images.githubusercontent.com/367762/81170087-b6a59400-8fa2-11ea-842b-d2646bc947b5.png)

__Note__:

Si on sélectionne un cluster dont les marqueurs ont différentes positions, puis que l'on zoom, le cluster se décompose en plusieurs points/clusters, ce qui amène à visualiser plusieurs points sélectionnés:

1) dé-zoom, puis sélection
![image](https://user-images.githubusercontent.com/367762/81170298-1bf98500-8fa3-11ea-8dd2-d94fe4b2b7bb.png)

2) zoom
![image](https://user-images.githubusercontent.com/367762/81170271-100dc300-8fa3-11ea-82a7-ac80a515515e.png)

**Comment by tglatt** [comment]
@Toub , il faut faire la même chose coté `individuel` :-)
