### ISSUE TITLE
 [ENQUETE] Import pour l'individuel - onglet "info mandataire-exerc. activité"

### ISSUE THREAD

**Issue by Toub** [SocialGouv/emjpm#1811]
Ticket spécifique à l'import de l'onglet "info mandataire-exerc. activité".

Lié à #1801 

Pour tester: http://localhost:3000/mandataires/enquetes/1

Résultats en bdd et dans les logs de l'api.

- [x] parsing excel "Informations mandataire"
- [x] persistence bdd `enquete_reponses_informations_mandataire`
- [x] parsing excel "Agréments formations" (PARTIEL)
- [x] persistence bdd `enquete_reponses_agrements_formations`

**Comment by Toub** [comment]
Ces champs sont déjà présents en base:
- Département
- Région
- Nom du mandataire

Que doit-on on faire lors de l'import? Les ignorer ou les vérifier? Si ils sont différents, que faire? Refuser l'import, demander confirmation, proposer de les mettre à jour?

**Comment by tglatt** [comment]
Le département dans le tableur excel correspond au département financeur. C'est une donnée que nous n'avons pas dans emjpm. Le plus simple est de le prévoir dans les formulaires d'enquêtes et de l'importer.
Pour le nom et le genre, on ignore.
