### ISSUE TITLE
chore(prettier): upgrade to v2

### ISSUE THREAD

**Issue by Toub** [SocialGouv/emjpm#1851]
Le projet de référence <https://github.com/SocialGouv/sample-next-app> intègre prettier v2, qui a de bien meilleur défaut que la v1 que nous avons sur le projet.

Par exemple: la (virgule de fin)[https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8#.ur8s3venv] : https://prettier.io/docs/en/options.html#trailing-commas

A noter qu'on pourrait aussi l'activer en attendant dans le `.prettierrc`
```json
{
  "trailingComma": "es5"
}
```
Lors de la mise à jour, il faudra reformater tous les fichiers (ce que devrait faire le pré-hook actuel), donc à faire à un moment opportun, où il ne traine pas de grosses PR.

**Comment by douglasduteil** [comment]
<img src=https://user-images.githubusercontent.com/730511/83018604-e4bc4800-a025-11ea-9f06-7dcc220b39e3.png width=693>
