### ISSUE TITLE
[Enquete] enquête déjà renseignée à la création

### ISSUE THREAD

**Issue by Toub** [SocialGouv/emjpm#1879]
![image](https://user-images.githubusercontent.com/367762/83489885-cf2c9f80-a4b7-11ea-910f-c1fbb1f09e5e.png)

Solution:
> ne pas renseigner `enquete_reponses.submitted_at` lors de la création d'une réponse

**Comment by tglatt** [comment]
https://github.com/SocialGouv/emjpm/commit/2d8f1f9486443a77efb57cd613bfa6a7a14b2bda
