### ISSUE TITLE
[RETOUR TEST IMPORT FORMULAIRE ENQUETE] 

### ISSUE THREAD

**Issue by tiphaineraffray** [SocialGouv/emjpm#1889]
# Liste des bugs lors de l'importation du tableur rempli vers le formulaire #

De manière générale il faut **écrire qqpart en **GROS** qu'il faut entrer 0 quand il n'y a rien** parce que ce n'est pas toujours le cas dans le tableur, la case est souvent laissée vide 

## Onglet "Informations générales" ## 
- [x] pour "exercez-vous avec un secrétariat spécialisé" et "exercez-vous votre activité dans un local professionnel" il a entré NON dans le formulaire alors que c'était OUI dans le tableur (test effectué hier aprèm) - après recharge ce matin il a bien mis OUI à chaque fois donc peut-être qu'il y a eu une correction mais je signale quand même 
- [x] dans "informations générales" puis "conditions d'exercice de l'activité", petite coquille: il manque l'accent sur le second e de "secrétariat"

 ## Onglet "Formation" 
- [x] problème dans l'importation du niveau de qualification du mandataire: un total de 7 dans le tableur contre 3 indiqué dans le formulaire > je crois que c'est un pb de coordination avec les intitulés du tableur où il y a plusieurs colonnes pour le niveau 

## Onglet "Activité" 
- [x] problème dans "sauvegarde de justice": il met seulement 2 nouvelles mesures alors que c'est 0 nouvelles mesures et 3 sorties de mesures 
- [x] problème dans "mandat ad hoc majeur": il met seulement 2 nouvelles mesures alors que c'est 0 nouvelles mesures, 1 mesure au 1er janvier et 7 mesures au 31 décembre 

+ pour les rubriques incomplètes: 

soit il y a la petite croix et le message "la valeur de fin d'année n'est pas cohérente avec les autres données", j'ai essayé de compléter avec des zéros dans les cases vides et il affiche toujours le message sans vouloir passer à la rubrique suivante quand on clique sur "suivant" 

soit il y a juste la petite croix, pareil je complète avec des zéros dans les cases vides sauf qu'ils ne se sauvegardent pas et que la croix reste

**Comment by remiroyc** [comment]
> problème dans l'importation du niveau de qualification du mandataire: un total de 7 dans le tableur contre 3 indiqué dans le formulaire > je crois que c'est un pb de coordination avec les intitulés du tableur où il y a plusieurs colonnes pour le niveau

Je suis pas sur de comprendre ce point. Pour le niveau de qualification mandataire on fait apparaitre un unique champ (vu qu'il n'y a qu'un mandataire individuel) dans lequel l'utilisateur peut saisir son niveau de qualification.

**Comment by Toub** [comment]
> De manière générale il faut écrire qqpart en GROS qu'il faut entrer 0 quand il n'y a rien parce que ce n'est pas toujours le cas dans le tableur, la case est souvent laissée vide

On parle des formulaires je suppose? On peut aussi rendre les champs non obligatoires dans ce cas.

**Comment by Toub** [comment]
> 

    problème dans l'importation du niveau de qualification du mandataire: un total de 7 dans le tableur contre 3 indiqué dans le formulaire > je crois que c'est un pb de coordination avec les intitulés du tableur où il y a plusieurs colonnes pour le niveau

J'ai compris le problème, c'est le jeu de données utilisé pour le test qui est mauvais (j'avais du le modifier pendant mes tests): 

![image](https://user-images.githubusercontent.com/367762/83998225-cc72f400-a968-11ea-900e-7da547fadfe5.png)

Sur cette ligne, on ne peut renseigner qu'une seule case, et un total différent de 1 n'a pas de sens:

![image](https://user-images.githubusercontent.com/367762/83998293-edd3e000-a968-11ea-8f04-c30230f47153.png)

**Comment by Toub** [comment]
On peut fermer le ticket. Une fois la validation terminée, @tiphaineraffray pourra refaire une passe.
