### ISSUE TITLE
MAJ Présentation de l'équipe e-mjpm sur beta gouv

### ISSUE THREAD

**Issue by tiphaineraffray** [SocialGouv/emjpm#1890]
+ **la page de présentation d'e-mjpm sur beta gouv** : equipe

https://beta.gouv.fr/startups/e-mjpm.html

**Comment by devthejo** [comment]
mettre à jour: https://beta.gouv.fr/startups/e-mjpm.html

**Comment by celinelr** [comment]
@revolunet Hello, nous avons besoin de toi pour pouvoir changer la listes des personnes participant au projet. Peux tu nous aider s'il te plait ?
