### ISSUE TITLE
[ENQUETE] Import préposé

### ISSUE THREAD

**Issue by Toub** [SocialGouv/emjpm#1989]
__Modalités d'exercice__

Les 1 ici correspondent à des checkbox (ou radiobox si exclusif ?).

![image](https://user-images.githubusercontent.com/367762/85402999-51632d80-b565-11ea-99aa-72db425c066e.png)

De plus, il manque le champ c "Nombre d'établissement"

**Comment by tglatt** [comment]
le nombre d'établissement peut se déduire de la liste des établissements

**Comment by tglatt** [comment]
pour le 1, on devrait avoir un select ou un radio, du coté du formulaire...

**Comment by Toub** [comment]
Ok, le select/radio c'est pour 2.1 ET 2.2 ?
