### ISSUE TITLE
[RETOUR TEST IMPORT FORMULAIRE ENQUETE SERVICES]

### ISSUE THREAD

**Issue by tiphaineraffray** [SocialGouv/emjpm#2045]
## Retour remplissage formulaire "services" par import d'un excel ##

- [x] **page d'accueil** : quand on clique sur l'onglet "enquête 2020", la page affiche immédiatement "Vos réponses à l’enquête 2020 ont bien été envoyées", il faut recharger pour qu'elle affiche "bonjour etc"

- [x] **Informations service** : il faut peut-être ajouter "coopération" avant "nombre de structures concernées"

- [ ] **les champs vides sont tous en rouge** : est-ce qu'on met 0 dans les cases vides ?

- [ ] **Votre activité** > **issues des révisions de mesures** : tableau excel indique 1 mainlevée, 2 MASP, 3 reconductions de mesures, 4 changements de mesures et 5 autres VS formulaire indique 0 mainlevée, 1 MASP, 2 reconductions, 3 changements de mesures et 4 autres 

- [ ] **Votre activité** > **causes des sorties du dispositif** : tableau excel indique 1 mainlevée, 2 décès, 3 MASP VS formulaire indique mainlevées vide, 1 décès et 2 MASP

**Comment by remiroyc** [comment]
@tiphaineraffray Vu avec Thomas, si non coopération le nombre de structures concernées devra être égal à 0.

**Comment by remiroyc** [comment]
> les champs vides sont tous en rouge : est-ce qu'on met 0 dans les cases vides ?

J'ai eu un doute aussi là dessus je ne savais pas trop quels champs on allait considérer comme obligatoire pour cet écran.

**Comment by remiroyc** [comment]
@tglatt 
activite est un onglet commun a prepose, individuel et service
il y a un saut de ligne en moins sur prepose qui pose problème pour le parsing (qui est un fichier commun pour le moment)
Du coup je sais pas si c'est possible de modifier l'excel directemen ou alors je vais être obligé de faire un cas particulier pour le parsing de prepose
