### ISSUE TITLE
Liste Blanche > Afficher et gérer les services dans le liste blanche

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#2124]
### Besoin

ETQ `direction`, je dois pouvoir:
- voir les services
- créer un service
- modifier un service
dans la page de la liste blanche.

### proposition de réalisation
- [ ] dans la barre de filtre, ajouter une entrée 'Service mandataire' et enlever l'entrée `Tous les types`. On sélectionnera `Mandataire individuel`  par défaut
<img width="359" alt="Capture d’écran 2020-08-03 à 17 51 35" src="https://user-images.githubusercontent.com/47273014/89201589-03086c00-d5b2-11ea-9ce8-7e3cd6def5d3.png">

- [ ] quand on sélectionne `Service mandataire`, afficher la liste des services: nom, SIRET, ville, département. On aura à la fin 3 composants:
  - `ListeBlanche` deviendra `ListeBlancheIndividuel`
  - `ListeBlanchePrepose` est à créer. Pour le moment copier / coller `ListeBlanche`.
  - `ListeBlancheService` est à créer
- [ ] rajouter dans `ListeBlancheSummary`, le nombre de `Service mandataire`
- [ ] le bouton `ajouter un enregistrement` change selon le type sélectionné:
  - Ajouter un mandataire individuel
  - Ajouter un mandataire préposé à un établissement
  - Ajouter un service mandataire
- [ ] le formulaire du service mandataire est le même que celui de l'admin. (Vérifier l'unicité du SIRET à la création et à la modification)

**Comment by remiroyc** [comment]
@tglatt Pour la création d'un service, si je reprend les champs de la création du service (admin) il semble manquer des champs dans lb_users (genre téléphone), je suis sensé les rajouter ? ou alors j'ai pas bien compris ?
