### ISSUE TITLE
Liste blanche > Gestion des établissements pour les préposés

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#2126]
## Besoin

Dans la liste blanche, nous devons gérer 3 types d'entrée:
- les mandataire individuels **déjà traité**
- les services mandataires **https://github.com/SocialGouv/emjpm/issues/2124**
- les préposé d'établissement **à faire**

Les préposés d'établissements peuvent travailler dans un ou plusieurs établissement(s) (table `etablissement` en bdd)  dont l'un est leur  établissement de rattachement.

### Base de données
- [x] ajouter et initialiser une colonne `departement_id` dans la table `etablissements`
- [x] ajouter une table `lb_user_etablissements` avec:
 - une colonne `lb_user_id` référençant `lb_user.id`
 - une colonne `etablissement_id` référençant `etablissement.id`
 - une colonne `etablissement_rattachement` de type boolean
 - le clé primaire est `(lb_user_id, etablissement_id)`
- [x] supprimer les entrées `lb_departements` pour les préposés `lb_user.type === prepose`.

### UI - Direction et Admin
- [x] développer la page de création d'un préposé: 
  - nom
  - prenom
  - email
  - sélection d'une liste d'établissement dont l'un est l'établissement de rattachement. utiliser le même système que la sélection des départements pour les mandataires individuels **L'utilisateur de type direction ne peut sélectionner que des établissements de son département.**
- [x] développer la page de modification d'un préposé
- [x] reprendre le composant `ListeBlanchePrepose ` (https://github.com/SocialGouv/emjpm/issues/2124) et afficher uniquement: nom, prenom, email, liste des établissements dont celui de rattachement.
- [x] le filtre par département doit s'appuier sur le département des établissements `lb_users.lb_user_departements.departement_id`
- [x] supprimer le filtre par prénom

### Enquete
- [x] à la création d'une enquête pour un préposé, on initialise `enquete_reponses.departement_id` avec le département de l'établissement de rattachement `lb_user_departements.etablissement_rattachement === true`
- [x] reprendre la fonction `isPayedByParis` et faire le test sur le département de l'établissement de rattachement et

**Comment by remiroyc** [comment]
@tglatt Il faudrait un jour reprendre les noms des champs pour uniformiser, par exemple en base (et dans le code) on trouve à la fois du ```departement_id``` et du ```department_id```

**Comment by remiroyc** [comment]
@tglatt tu peux me confirmer qu'il faut bien supprimer : lb_structures, lb_tribunaux, lb_departements pour les preposes comme j'ai fait ici : https://github.com/SocialGouv/emjpm/pull/2141/commits/ecc37d0600a8a18a000f5433870208361460f7e2
