### ISSUE TITLE
Hasura > Clé privée

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#2246]
mettre la clé privée en variable k8S.

les fichiers `private.pem` et `public.pem` sont accessibles dans le package `api`. Pour des raisons de sécurité, il faut passer par les variables k8s pour gérer ces clés.

see `.k8s.values` dans `packages/api`.

les branches de dev et les tags sont déployées dans un cluster de dev et la production est sur un cluster de prod.

Les variables k8s du cluster de dev sont initialisées dans le fichier `secret-dev.yml`.

Les variables k8s du cluster de production sont renseignées directement dans rancher.  https://rancher.fabrique.social.gouv.fr/

@devthejo tu dois y avoir accès avec ton identifiant github

**Comment by devthejo** [comment]
OK on doit pouvoir déployer la prod j'ai créé de nouvelles clés et les ai ajouté dans les secrets kubernetes:
```sh
openssl genrsa -out keyfile.key 4096
openssl rsa -in keyfile.key -pubout -out keyfile.pub
export KUBECONFIG=/lab/betagouv/.kube/prod2
# backup (just in case)
kubectl -n emjpm get secret emjpm-secret -o yaml>emjpm-secret
# patch existing
AUTH_PUBLIC_KEY=$(base64 < "./keyfile.pub" | tr -d '\n')
AUTH_PRIVATE_KEY=$(base64 < "./keyfile.key" | tr -d '\n')
kubectl -n emjpm patch secret emjpm-secret \
  -p "{\"data\":{\"AUTH_PUBLIC_KEY\":\"${AUTH_PUBLIC_KEY}\",\"AUTH_PRIVATE_KEY\":\"${AUTH_PRIVATE_KEY}\"}}"
```
contrairement à ce que j'avais cru comprendre les secrets ne sont pas sealed donc il ne devrait y avoir aucun problème
