### ISSUE TITLE
perf(api): rate limit on software data push

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/emjpm#2307]
We should ensure that the [rate limit](https://www.npmjs.com/package/express-rate-limit) is working well

The clients have secret to oauth on the api.

\to @revolunet You want it to be on k8s too ?
\to @tglatt can you write some test cases here ?

**Comment by revolunet** [comment]
you'd better use nginx annotation imho https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rate-limiting

**Comment by douglasduteil** [comment]
@revolunet the nginx rate limit can be set by client secret ?

**Comment by revolunet** [comment]
i dont think so

**Comment by devthejo** [comment]
note for me, inspire tests from: https://github.com/animir/node-rate-limiter-flexible/blob/master/test/RateLimiterMemory.test.js

**Comment by devthejo** [comment]
done on prod via annotation with @revolunet
```sh
kubectl -n emjpm annotate ingress api-nodejs nginx.ingress.kubernetes.io/limit-connections=2
kubectl -n emjpm annotate ingress api-nodejs nginx.ingress.kubernetes.io/limit-rpm=60
```

tested using: 
https://gist.github.com/cirocosta/de576304f1432fad5b3a
