### ISSUE TITLE
ETQ DD je veux que mon espace soit revu afin d'avoir une meilleur visibilité

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2353]
Afficher la liste blanche en premier
Ajouter une page magistrats (comme celle des mandataires)

**Comment by celinelr** [comment]
est ce que tu voulais dire : 
1. mettre l'onglet liste en blanche en premier, stats en second, enquêtes en dernier
2. Sur la page stat, afficher en premier l'onglet vue détaillée

Peux tu nous confirmer cela ? :)

**Comment by celinelr** [comment]
Confirmation ce jour de : 

1. mettre l'onglet liste en blanche en premier, stats en second, enquêtes en dernier
2. Sur la page stat, afficher en premier l'onglet vue détaillée

**Comment by celinelr** [comment]
Tout semble très bien fonctionner ! Merci Jo.

Je te laisse regarder pour uniformiser les marges entre les colonnes des différents profils 🙏

**Comment by celinelr** [comment]
ca me semble beaucoup mieux merci Jo
