### ISSUE TITLE
[MANDOLINE] api get user

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#2368]
faire la documentation:

- durée de vie de token
- documentation de l'api `mandoline/user`

Compléter la documentation avec ces 2 choses. la documentation est accessible https://socialgouv.github.io/emjpm-api-doc et le dépôt est ici:

https://github.com/SocialGouv/emjpm-api-doc

Il suffit de modifier le fichier qui se trouve ici `source/index.html`

**Comment by devthejo** [comment]
https://github.com/SocialGouv/emjpm-api-doc/pull/8
