### ISSUE TITLE
Synchronisation des données des mesures

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#2369]
Il y a plusieurs manières de créer des mesures:
 - avec l'UI
- en important les mesures via un csv
- via les API éditeur 
- via l'import des mesures provenant d'OCMI

Question:
Définir la priorité des sources de vérité et éventuellement leur priorisation?

**Comment by devthejo** [comment]
sera résolu par https://github.com/SocialGouv/emjpm/issues/2559
