### ISSUE TITLE
Gérer une montée en charge des données entrantes via les API

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/emjpm#2385]
en rapport avec la discussion lors du point tech, concernant la stratégie à adopter pour gérer la montée en charge qu'il pourrait y avoir prochainement de part l'usage des api par lesquelles arriveraient des données qui demanderaient à postgres une certaine capacité à les accueillir, je pense qu'une bonne stratégie serait d'implémenter une gestion de queue en nodejs et basée sur un serveur redis afin, non pas de limiter l'envoie de données mais simplement de les temporiser sur le disque et de les traiter en file d'attente (et éventuellement de créer un système de priorité pour éviter qu'un éditeur accapare trop de ressources au détriment des autres si cela s'avère nécessaire, mais ce n'est même pas certain que cela soit utile)
gestion de queue en node: https://github.com/OptimalBits/bull
@tglatt @gary-van-woerkens

**Comment by revolunet** [comment]
on peut également monter en gamme sur le serveur PG (on est sur le plus petit) : https://docs.microsoft.com/en-us/azure/postgresql/concepts-pricing-tiers

**Comment by devthejo** [comment]
Merci de ton retour. Effectivement ça peut être une première étape plus pertinente et on peut surveiller ensuite.
On peut garder ma solution tech sous le coude si ça suffit pas à terme, car même en augmentant le nombre de CPU, la vitesse d'écriture sur PG dépends aussi de la vitesse d'écriture sur le disque (à ce propos, sais tu si c'est du SDD ou du HDD, j'ai pas vu l'info sur la page azure).
Pour info: Les autres solution pour scaler PG que je connait sont Stolon (mais c'est surtout pour le sharding, la réplication et pour scaler la lecture, ça change pas grand chose à l'écriture) et Citus (là on scale vraiment horizontalement mais c'est un peu complexe à gérer si on le fait soi même et je sais pas si ça fonctionne bien avec hasura).

**Comment by revolunet** [comment]
Bonne question, je n'ai pas trouvé si c'est du SSD ou HDD. en tous cas sur le déploiement de base comme c'est le cas actuellement, peu de garanties. Un peu upgrade sans problème

https://docs.microsoft.com/fr-fr/azure/postgresql/concepts-pricing-tiers#storage

Il y a aussi PG flexible server en preview : https://docs.microsoft.com/fr-fr/azure/postgresql/flexible-server/

**Comment by revolunet** [comment]
il y a aussi Citus si besoin mais je pense pas :)
