### ISSUE TITLE
refactor pipeline clean

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/emjpm#2388]
1. many refactos can be done to improve consistency of build, test and deployments mainly using 3 adapted Dockerfile (local, test, deploy)
2. considering that emjpm pipelines are outdated and confusing, after exploring theses solutions last two days:
- kosko (seem clean but interop not very natural, i like js but used to yaml with kube)
- werf (concept seem good but usine à gaz)
- gitkube (adapted gitops workflow when doesn't want to rely on gitlab and want a full and light resilient archi, like on my project, but add cluster side complexity, so not very adapted, good to keep pure git history of deployments but lack of common visibility on pipelines except using it in gitlab pipeline but we loose the advantage of having a pure and autonomous gitops workflow)
- helm3 template + kubectl apply (from gitlab-ci pipeline) want to try this approach as it seem to be a very light and flexible pseudo code to put in gitlab ci:
```
run builds
run test (on optimized built test image with cache layer)
deploy:
specific env hooks (before script)
  generate custom env .helm/values.yaml
  (optional) generate additional .k8s/*.yaml	
if -d .helm
  helm template .helm > .k8s/helm-generated.yaml
  if -f .helm/kustomize.yaml
    add post-renderer param to helm
if -d .k8s
  kubectl apply -f .k8s
```

**Comment by devthejo** [comment]
@douglasduteil @revolunet j'aimerais vous proposer d'implémenter une approche et si après avoir vu le refacto vous souhaitez quand même que j'utilise kosko on s'en sera tout de même rapproché en terme de refacto global, ouvert pour en discuter avant si vous le souhaitez (ou après, si vous préférez)

PS: j'ai passé la journée à m'intéresser à la question car je suis à une étape de mon projet perso où je dois traiter cette question (car tous les autres déploiements que je faisai étaient ceux d'outils tiers jusqu'à présent et l'approche n'est pas du tout la même). Donc à chaque fois que j'étudiais une approche, je me posais en même temps les questions pour mon projet et pour emjpm. J'en suis arrivé à des solutions proches mais pas similaires car pas exactement les même prérogatives.

**Comment by revolunet** [comment]
Ce serait très intéressant de voir ta proposition!

La version kosko se rapprocherait de ça : https://github.com/SocialGouv/sample-next-app/tree/master/.k8s

**Comment by devthejo** [comment]
OK ça marche, merci pour le lien vers l'implémentation kosko

**Comment by revolunet** [comment]
Nb: kosko only generate YAML, which is applied as usual with kubectl

**Comment by devthejo** [comment]
yep, j'avais deviné

**Comment by devthejo** [comment]
https://github.com/SocialGouv/k8s-ci
