### ISSUE TITLE
jwks generate on the fly + rotation

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/emjpm#2389]

**Comment by celinelr** [comment]
Estimation 3 jours de dev + 3 jours effets de bord

**Comment by celinelr** [comment]
Ca avait été fait ou tu l'avais seulement close cette issue ?

**Comment by devthejo** [comment]
pas pertinent si le projet migre d'infra

**Comment by celinelr** [comment]
OK! Thanks for the comment
