### ISSUE TITLE
[STATS] Ajouter les mesures dans la page publique de stats

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2414]
ETQ tout public JE VEUX voir le nombre de mesures réservées par mois (au moins) dans la page publique de statistiques : https://emjpm.fabrique.social.gouv.fr

**Comment by devthejo** [comment]
à remonter dans matomo, voir #2432

**Comment by devthejo** [comment]
fixed by https://github.com/SocialGouv/emjpm/commit/776f55e8ee25b0489bad011a3ba01b44337cb94a
à voir quand même pour les mesures non associées à un département, ce qui est la cas pour presque toutes

**Comment by vicmartinezp** [comment]
@devthejo La règle pour dispatcher les mesures par département est la suivante : on prend le département du majeur à protéger. 

Du coup, je te propose de faire cette modification sur la page publique de Statistiques (https://emjpm.fabrique.social.gouv.fr/stats) afin que, en cliquant pour chaque département, on ne voit que les mesures assignées au majeurs dans ce département. 

Merci

**Comment by devthejo** [comment]
@vicmartinezp c'était justement ça que je faisait au départ, le problème est que souvent on a pas cette info et le compteur est donc à zéro presque tout le temps

exemple:
```sql
SELECT COUNT(*) FROM mesures WHERE
magistrat_id IS NOT NULL
AND created_at BETWEEN '2020-12-30T11:27:41.976Z' AND '2021-01-29T11:27:41.976Z'
AND department_id IS NOT NULL;
```

en français: toutes les mesures qui sont associées à un département (et quand on parle de majeur, les seules infos sont dans mesures) et qui ont été affectées et comprise dans le dernier mois, résultat: 77 (contre 311 en réalité)

du coup soit je laisse france entière, soit j'ajoute une info: mesures non rattachées à un départements
