### ISSUE TITLE
[ADMIN] Action retour sur le bouton Enregistrer

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2451]
ETQ admin JE VEUX que lorsque je fais des modifications sur la fiche d'un mandataire individuel et je clique sur Enregistrer, il y ait un retour vers la liste. 
Aujourd'hui, je fais une modification, je clique sur Enregistrer et rien ne se passe. Je suis obligée de retourner en arrière de façon manuelle. Par contre, la modification a bien été prise en compte.

**Comment by devthejo** [comment]
je te propose un deuxième boutton "Enregistrer et Retour" (ou autre, ou le premier en "Enregistrer et continuer l'édition", comme tu veux) ainsi qu'une notification indiquant l'enregistrement s'est bien produit, car cela ma semble anormal de forcer l'utilisateur à quitter l'espace d'édition dans lequel il se trouve au moment de l'enregistrer

**Comment by vicmartinezp** [comment]
Suite à notre échange, nous avons décidé avoir les boutons suivants : 
- Supprimer (pour l'admin)
- Annuler
- Enregistrer
- Terminer (cette action enregistre et fait retour sur la liste)

**Comment by devthejo** [comment]
pour le bouton supprimer il faudra attendre la fonctionnalité d'historisation qui arrive bientôt
pour le bouton terminer, je viens de l'implémenté pour l'édition des mandataires, ce sera dans la prochaine release
dis moi si tu veux que j'implémente ça aussi ailleurs
