### ISSUE TITLE
[STATS] Correction des chiffres affichées

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2454]
Les chiffres affichées doivent être les mêmes que sur l'onglet Statistiques du profil Direction

**Comment by vicmartinezp** [comment]
Profil direction -> Statistiques -> Vue détaillée
https://emjpm.fabrique.social.gouv.fr/direction/mandataires/list 

Page publique Stats
https://emjpm.fabrique.social.gouv.fr/stats/01

Pour l'exemple de l'Ain -> 6 mandataires individuels sur l'un, et 8 sur l'autre -> ce n'est pas cohérent

**Comment by devthejo** [comment]
filtre par département dans direction (même stats pour tous les profils direction)

**Comment by devthejo** [comment]
Actuellement la page publique des stats remonte le nombre d'inscrits (ceux qui ont un compte) alors que les stats du profil direction remontent aussi ceux qui n'en ont pas.
C'est d'ailleur précisé sur la page publique: "Inscrits".
Es tu donc certaine qu'il faille les remplacés par les chiffres du profil direction ?
et dans ce cas là il faudrait aussi enlever le terme "Inscrits" de la page publique des stats pour que cela soit raccord.
