### ISSUE TITLE
[MAGISTRAT] La liste de mandataires doit être issue de la liste blanche

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2478]
La liste de mandataires du profil Magistrat doit être la même que celle que l'on voit sur le profil Direction -> Onglet Statistiques -> Vue Détaillée

**Comment by devthejo** [comment]
à vérifier avec le métier que l'on peut enlever le filtre par tribunal

**Comment by devthejo** [comment]
c'est ok on peut

**Comment by vicmartinezp** [comment]
Laisser les tribunaux mais l'orienter vers "préférences" ?
