### ISSUE TITLE
Mise à disposition d'une base de tests (données fictives)

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2479]
Pour la semaine du 22 au 26 fév -> Cindy pourra créer les profils fictifs

**Comment by devthejo** [comment]
Je réouvre ce ticket car comme je le disais à Doug, il faut l'implémenter dans les tests E2E et entièrement les refactorer (c'était ça le but au départ)

**Comment by vicmartinezp** [comment]
@devthejo Ok Jo, sorry

**Comment by celinelr** [comment]
related tu #2555
