### ISSUE TITLE
[DIRECTION] Le compteur Mesures en cours n'est pas correct

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2489]
![image](https://user-images.githubusercontent.com/51990737/108567814-3968c700-7309-11eb-99c6-9a68a6f6d315.png)

**Comment by devthejo** [comment]
après investigation le filtre semble se faire sur le département des mesures et non sur celui des mandataire comme cela devrait être le cas, je veux bien qu'on regarde ça ensemble @vicmartinezp car cela me semble étrange qu'il y ait pus y avoir une telle incohérence, en tout cas c'est visiblement un problème ancien

**Comment by devthejo** [comment]
ah en fait il semble qu'il y ait aussi un problème avec le filtrage par dates...

**Comment by devthejo** [comment]
j'ai fait comme on s'est dit, ce sera déployé dans quelque minutes
