### ISSUE TITLE
[DIRECTION] Ajouter date de MAJ des mesures des mandataires

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2490]
Profil Direction -> Onglet Statistiques -> Bouton Vue détaillée

Ajout de la date à laquelle les mandataires ont mis à jour leurs mesures. Car autrement, il est impossible de savoir si les données sont d'actualité ou d'il y a un an.

Même modification pour la vue des magistrats. 

A voir ensemble comment intégrer cette donnée dans le tableau

**Comment by devthejo** [comment]
fixed by #2509

**Comment by devthejo** [comment]
profil direction ok, pas encore sur profil magistrat

**Comment by devthejo** [comment]
713f326dfb7917c6c3cb03e66481d314c04a4f6c
4e7165ebc1536e2c700c8b78baca03971ed8a6c7
c2602a52d26e0357bcd8e6d6e7d265a455e2120f
