### ISSUE TITLE
Comptes inaccessibles

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2491]
Lorsqu'on accède au profil de certains utilisateurs, on tombe sur la page d'erreur avec la souris. Que ce soit l'utilisateur ou moi avec le compte admin. Les liens pour retour en arrière de la page ne fonctionnent pas et il n'y a pas moyen de revenir en arrière. Je dois effacer les cookies depuis la console, puis relancer la page.

Voici deux exemples : 
individuel-2494
direction-1080

**Comment by devthejo** [comment]
pour le 1080 l'erreur était visiblement ancienne (le parsing des agréments était implémenté de façon bizarre),
pour le 2494 l'erreur était autre (attente d'une direction non existente dans le cas du profil direction national)
j'ai rajouté un bouton déconnexion sur la page d'erreur ;)
je viens de lancer la mise en prod, le robot devrait indiqué quand c'est bon sur le channel s/emjpm/notifs
de mattermost ;)

**Comment by vicmartinezp** [comment]
Merci Jo! Je peux accéder au profil individuel-1080, mais le département apparait avec le mot (Undefined). Et pareil pour tous dans la liste déroulante 

![image](https://user-images.githubusercontent.com/51990737/108619802-880c8300-7427-11eb-8fac-bcae212393e7.png)

**Comment by vicmartinezp** [comment]
Pour direction-2494, j'ai toujours l'erreur, mais c'est bizarre. Car, déjà, la demande de compte n'est pas bonne (elle est @justice.fr et elle demande un compte "direction") et en plus, il n'y avait pas de ticket Pastek lié.
Du coup, je te propose de supprimer cet user et je vais la contacter pour lui dire de faire une autre demande, cette fois-ci avec le profil "juge de tutelles". Merci :)

**Comment by devthejo** [comment]
le bug "undefined" n'est pas spécifique au profil 1080, c'est partout et c'est un autre bug (sans doute encore lié au refacto des départements)
pour 2494, j'avais résolu le bug qui apparaissait en s'y connectant, je viens de voir qu'en allant simplement sur la fiche il y a effectivement toujours un bug

**Comment by devthejo** [comment]
le bug vient du fait qu'à plusieurs endroits du code le profil direction de type national n'est pas pris en compte (développement pas finit on dirait)

**Comment by devthejo** [comment]
le problème est qu'elle n'a aucune liegne d'associée dans la table direction (il devrait au moins y en avoir une: regional, departemental ou national), c'est le seul user dans ce cas mais il faut que je trouve comment elle a réussi à rentrer comme ça, ça ne devrait pas être possible, en tout cas cela ne semble pas prévu dans le code, la question que je me pose c'est est-ce qu'il faut le prévoir ou empêcher que cela arrive (si cela est vraiment possible et fiable)

**Comment by vicmartinezp** [comment]
C'est peut-être lié au fait qu'il n'y avait pas de ticket Pastek. Comme s'il s'agissait d'une demande de création de compte "non finie"... je ne sais pas. En tout cas, je ne validerai jamais ce compte car il s'agit d'un juge de tutelle et non pas d'un agent direction. Mais oui, il faudrait savoir comment et pourquoi s'est arrivé pour que cela ne se reproduise. :) 
Pour le bug départements (undefined), crée un nouveau ticket si tu le préfères ;)

**Comment by devthejo** [comment]
OK, t'inquiète pour les départements c'était rien c'est résolu, ça sera bon lors de la prochaine MEP
