### ISSUE TITLE
[ETABLISSEMENTS] - Problème de pagination

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2493]
![image](https://user-images.githubusercontent.com/51990737/108695492-a4302300-7500-11eb-99e1-317fd8553e67.png)

Lorsque je fais une recherche par établissement, par exemple "VAUGIRARD", il n'y a que 2 résultats qui s'affichent. Par contre, une pagination infinie... lorsqu'on clique sur la 2ème page, il nous dit, pas de résultats

**Comment by devthejo** [comment]
fixed by https://github.com/SocialGouv/emjpm/commit/a2d9d118cc5774509f896099e4806840de902ee5
