### ISSUE TITLE
[CHAMP GENRE] Non obligatoire mais bloquant

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2496]
![image](https://user-images.githubusercontent.com/51990737/108847388-ed0ad900-75df-11eb-8275-1db472ab42a0.png)

Dans la fiche d'un préposé, le champ "Genre" n'apparaît pas comme obligatoire. Or, il est bloquant pour pouvoir Enregistrer.

Proposition : le rendre obligatoire et lui ajouter le (*)

**Comment by devthejo** [comment]
oui, il y en a effectivement partout où il manque l'astérisque alors que le champs est obligatoire, il faudra faire un tour complet de ça car j'en vois tout le temps
