### ISSUE TITLE
[MANDATAIRES] Rendre obligatoire le département financeur ou l'établissement de rattachement

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2511]

**Comment by celinelr** [comment]
# Is your feature request related to a problem? Please describe.
Les mandataires sans établissement de rattachement ne remontent pas dans les stats ni dans le profil DD.
Un mandataire préposé ne devrait pas pouvoir utiliser la plateforme s'il n'a pas ces informations de renseignée.

Cela concerne plus de 300 mandataires préposés sur 400 et quelques

# Describe the solution you'd like
Il faudrait lancer une campagne d'information

**Comment by celinelr** [comment]
je viens d'envoyer la campagne aux 100 (et quelques préposés)
