### ISSUE TITLE
[TRIBUNAUX] - Gestion des doublons

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2513]

**Comment by vicmartinezp** [comment]
Suite à une réunion avec le métier, nous avons compris que les tribunaux d'instance ont été convertis en tribunaux judiciaires ou de proximité. Pour info, eMJPM n'utilise que les tribunaux verrouillés, donc, on est bon.
Pour les tribunaux "non verrouillés" utilisés par OCMI ou l'API, nous allons créer une table de correspondance pour les liés aux bons tribunaux "verrouillés".

**Comment by devthejo** [comment]
[tis non immutable joined on mesures.zip](https://github.com/SocialGouv/emjpm/files/6295684/tis.non.immutable.joined.on.mesures.zip)

**Comment by celinelr** [comment]
Yay ! Je viens de mettre à jour la liste des 200 tribunaux :partying_face: !! :sweat_smile:

Ils ont tous un match avec un tribunal actuel

pourrais-tu rendre le champ "correspond au tribunal actuel" obligatoire s'il te plait ?

pour toute les futures entrées ca sera mieux je pense

**Comment by celinelr** [comment]
Merci je viens de vérifier
