### ISSUE TITLE
ETQ utilisateur je dois pouvoir indiquer que je ne souhaite pas de mesure en plus que celle que j'ai en cours (ne pas avoir de dispo positives pour une personne ne souhaitant plus de mesure)

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2538]

**Comment by devthejo** [comment]
Note à moi même: Dispo Boutton Switch: je ne souhaite pas de mesures supplémentaires: put dispo at min(current, dispo_max) as readonly

**Comment by celinelr** [comment]
## PROBLEME

Mise en situation : 
Dans le cas ou un mandataire veut stopper son activité / la ralentir / est absent  il indique qu'il ne veut plus de mesure en mettant "0 mesures souhaitées" alors qu'il en a en cours. Son solde est alors négatif. 

On ne devrait pas avoir un solde négatif . 
Il faudrait indiquer le fait qu'il ne souhaite pas de mesure en plus que celles qu'il a déjà

## SOLUTION 

Proposition :  
Ne pas toucher au nb de mesures en plus et donner la possibilité de cocher une case indiquant qu'il ne souhaite pas de mesure en plus

**Comment by celinelr** [comment]
Il faudrait vérifier le besoin par les utilisateurs en les faisant utiliser des mockup de la solution
