### ISSUE TITLE
[MAGISTRAT] afficher un message incompatibilité sur les navigateurs EDGE et IE

### ISSUE THREAD

**Issue by ThbtSprt** [SocialGouv/emjpm#2545]
EDGE et IE sont les navigateurs par défaut installés sur les postes des juges des tutelles ainsi que Firefox ESR 52.9

Un message d'incompatibilité s'affiche pour Firefox, mais pas pour les autres navigateurs alors qu'ils sont également incompatibles (plusieurs scripts ne s'exécutent pas, notamment au stade de la "réservation de mesure", ce qui empêche de soumettre le formulaire).

Il pourrait être utile de prévoir un message d'incompatibilité pour ces navigateurs également.

**Comment by celinelr** [comment]
Merci @devthejo, j'ai bien le message d'erreur. 

Par contre celui indique "La plateforme e-MJPM n'est pas compatible avec votre navigateur ([nom du navigateur et version]). Nous vous conseillons d'utiliser une version récente de Firefox pour profiter pleinement des fonctionnalités d'eMJPM. Veuillez cliquer ici pour installer ou mettre à jour ce navigateur libre."

Est ce que l'on n'ajouterait pas "ou Chrome" à la suite de "Nous vous conseillons d'utiliser une version récente de Firefox" ? Qu'est ce que tu en penses ?

**Comment by celinelr** [comment]
Finalement afficher le message : "La plateforme e-MJPM n'est pas compatible avec votre navigateur ([_nom du navigateur]_). Nous vous conseillons d'utiliser une version récente de Firefox (cliquer ici) pour profiter pleinement des fonctionnalités d'eMJPM. eMJPM est également compatible avec le navigateur Chrome."

Dans _cliquer ici_ mettre le lien : https://www.mozilla.org/fr/firefox/

**Comment by celinelr** [comment]
Top ! merci
