### ISSUE TITLE
Restaurer le workflow preprod par branches multiples (déploiement de données fictives)

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2555]

**Comment by celinelr** [comment]
Pas prio pour le moment

**Comment by celinelr** [comment]
= avoir un environnement de test par feature

**Comment by celinelr** [comment]
on pourrait associer ce ticket à la randomisation des données

**Comment by devthejo** [comment]
ajouter une double instance pour apitest afin d'avoir du zero-downtime lors de déploiments (comme sur la prod)

**Comment by devthejo** [comment]
gérer le problème du nombre trop limitées de connections parallèles à la DB (voir avec l'équipe OPS/SRE ou réduire les connections au strict minimum en environnement de dev)
