### ISSUE TITLE
Import incrémental

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/emjpm#2559]
TODO:

Dev:
- Import OCMI
- Import en matchant sur le numero de dossier et l'id du mandataire, sinon sur numero_rg et siret tribunal
- Contrainte d'unicité avec message d'erreurs pour les imports ultérieurs
déjà réalisé: import batch par l'API (Import en matchant sur le numero de dossier et l'id du mandataire) [x]

PO:
- Contacter des magistrat pour vérifier que le numero RG est bien unique au sein du tribunal (siret-tribunal + numero_rg = clé unique de mesure)
- Contacter les mandataires qui ont des doublons pour vérifier qu'il s'agit bien de numéro bidon (me demander une liste d'emails)

**Comment by devthejo** [comment]
related: https://github.com/SocialGouv/emjpm/issues/2513
résoudre ce point (la redirection des siret de tribunaux obsolètes) sinon s'attendre à des doublonnages car pas de match entre les siret des tribunaux (sinon résolvable par le mandataire en l'incitant à remplir le numéro dossier)

**Comment by devthejo** [comment]
@vicmartinezp @celinelr tenez moi au courant dès que vous avez du nouveau concernant ce sujet, cela me permettra de commencer les travaux sereinement

**Comment by vicmartinezp** [comment]
@devthejo @cedricr J'ai envoyé la question du numéro RG unique par tribunal à 4 magistrats. On attend les réponses

**Comment by celinelr** [comment]
> @devthejo @celinelr J'ai envoyé la question du numéro RG unique par tribunal à 4 magistrats. On attend les réponses

Merci Victoria

**Comment by devthejo** [comment]
from @vicmartinezp on mattermost:
> nous avons 4 réponses de magistrats : le numéro RG est bien unique pour chaque tribunal

**Comment by celinelr** [comment]
Story points Maximal car :  
- que faire avec  les mesures éteintes si elles sont un même numéro RG pas "bidon" ? 
- les dedoublonner en base? -> mettre un numéro incrémental derrière ?

**Comment by devthejo** [comment]
upsert
  DELETE ALL MESURES NON INCREMENTABLES
  REFUSE TO CREATE WITH NO NUMERO_RG AND TI_ID

**Comment by devthejo** [comment]
mesures en doublons ~14000 dont ~13000 en cours
services impactés par les doublons 62 / 227
mandataires impactés par les doublons 834 / 1695

**Comment by celinelr** [comment]
doit-on les contacter / faire quelque chose ?

**Comment by devthejo** [comment]
non je ne pense pas, j'ai juste mis ça là pour info, je songe à mettre une infobulle à côté des numéro rg doublonnés dans l'interface des mandataires et services

**Comment by celinelr** [comment]
Ca marche ! En quel cas pourras tu me montrer avant la MEP ? :D

**Comment by vicmartinezp** [comment]
@devthejo Merci pour ces chiffres. Et ok pour l'infobulle lorsqu'un numéro RG est en doublon ;-)
