### ISSUE TITLE
Se baser sur le SIREN plutôt que sur le SIRET du mandataire

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/emjpm#2560]
Solutionner les problèmes de conflits en considérant le SIRET le plus élevé comme le seul valide (merci à Bruno d'OCMI pour l'info)

**Comment by celinelr** [comment]
Chantier important car cela va supprimer des utilisateurs (ex: ceux qui n'ont pas de mesure / pas d'actvité sur le compte)
Chantier important surtout sur l'administration de la base plus que de developpement

**Comment by celinelr** [comment]
Story points :  
- facile en dvlpt
- Par contre, il faudra contacter 2 préposés et 2 individuels pour voir quels sont les comptes utilisés (pour les comptes doublonnés

**Comment by devthejo** [comment]
```sql
SELECT   COUNT(*) AS nbr_doublon, SUBSTR(siret, 0,10) AS siren
FROM  mandataires
GROUP BY siren
HAVING   COUNT(*) > 1;
```

```sql
SELECT   COUNT(*) AS nbr_doublon, SUBSTR(siret, 0,10) AS siren
FROM  services
GROUP BY siren
HAVING   COUNT(*) > 1;
```

**Comment by devthejo** [comment]
```sql
SELECT
COUNT(*) AS nbr_doublon,
SUBSTR(siret, 0,10) AS siren,
STRING_AGG(mandataires.id::text, ',') as mandataire_ids,
STRING_AGG(users.email, ',') as emails
FROM  mandataires
JOIN users ON users.id = mandataires.user_id
WHERE siret IS NOT NULL
GROUP BY siren
HAVING   COUNT(*) > 1;
```

```sql
SELECT
COUNT(*) AS nbr_doublon,
SUBSTR(siret, 0,10) AS siren,
STRING_AGG(services.id::text, ',') as service_ids,
STRING_AGG(services.email, ',') as emails
FROM  services
WHERE siret IS NOT NULL
GROUP BY siren
HAVING   COUNT(*) > 1;
```sql

**Comment by devthejo** [comment]
finalement, ayant constaté un cas (et plusieurs autres possibles potentiels) où plusieurs comptes se partagent légitimement  le même SIREN (des préposés en l'occurence), la solution de se baser sur le SIREN ne sera appliquée uniquement que comme fallback lors des imports OCMI.

**Comment by celinelr** [comment]
effectivement, dans le cas où des préposés font parties d'un sous ensemble établissements rattaché à entité juridique supérieur
Exemple, numéro Finess 910100015

@devthejo peux expliquer "le SIREN ne sera appliquée uniquement que comme fallback lors des imports OCMI" s'il te plait ?

**Comment by devthejo** [comment]
un fallback c'est un plan B
si aucun match avec le siret alors rechercher le siren

**Comment by devthejo** [comment]
cela solutionne notre problème de SIRET désynchronisés parfois avec OCMI, au cas où le SIREN lui matchera toujours

**Comment by celinelr** [comment]
Top explication limpide, merci :)
