### ISSUE TITLE
Décliner la dispo par département

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2561]
Pour les mandataires ind, préposé et services, afficher la disponibilité par département : vue agent et vue magistrats

**Comment by devthejo** [comment]
Il y a un petit problème de consistence qui est posé par le fait que les mandataires ont actuellement des tribunaux sélectionnés (historiquement) qui ne correspondent pas aux départements dans lesquels ils ont un agrément.
Plusieurs solutions:
- les agents de direction donnent des agréments cohérent avec le travail réel des mandataires, ça implique qu'ils doivent se bouger un peu (ce qui n'arrivera donc pas)
- on ajoute dans la liste des dispo par département les départements pas seulement des agréments mais aussi des tribunaux sélectionnés historiquement (par contre c'est lourd, même pour la maintenance à long terme, c'est un peu usine à gaz)
- le besoin étant principalement pour les services, le problème est marginal, et le jour où un mandataire nous remonte le problème on l'incite à se rapprocher de la dd pour avoir l'agrément dans le département et on s'excuse du fait qu'eMJPM manque de cohérence pour des raison historiques et bureaucratiques
@vicmartinezp @celinelr Qu'en pensez vous ?

**Comment by vicmartinezp** [comment]
@devthejo @celinelr Je pense qu'on doit voir ce point avec le métier avant de prendre des décisions

**Comment by devthejo** [comment]
C'est typiquement le genre de sujet auquel ils ne savent pas répondre car ils sont rigide dans leur façon de voir. Ils (ou plutôt elles) n'arrivent pas à se mettre à la place des magistrats et des mandataires et ne raisonnent qu'en terme de réglementation et de gestion. C'est pour ça que j'avais proposé le filtre qu'on a actuellement sur la vue magistrat pour trouver un compromis entre leurs besoins et ceux des utilisateurs finaux. Si on les avais écouté sur ce point on aurait empêché les magistrats et les mandataires de travailler en cassant tous les liens qu'ils avaient établi dans eMJPM.
Je pense au contraire que c'est nous qui devons arbitrer et peut être trouver une meilleur compromis, une meilleur idée que celles que je propose, ou alors choisir la troisième solution et attendre de voir si un mandataire individuel ou préposé vient se plaindre que la nouvelle fonctionnalité pourrait être mieux. En attendant ça leur enlève rien et ça répond au problème initial pour les services.

**Comment by devthejo** [comment]
je viens de déployer la preprod sur https://testdb-emjpm.dev2.fabrique.social.gouv.fr/ pour recettage
Pour récapituler ce qu'on s'était dit:
- ETQ mandataire (individuel, préposé et service) je peux indiquer mes disponibilités par département (départements d'agréments pour les invididuels, départements des établissements pour les préposés, départements associés pour les services) (pages impactées: /services/edit-informations, /services/informations, /mandataires/edit-informations, /mandataires/informations)
- ETQ magistrat je peux filtrer les mandataires par département, lorsque le filtre est actif, je vois la disponibilité par département, toujours lorsque le filtre est actif et que l'ordre de tri actif est par disponibilité, le tri se fait sur la disponibilité par département plutôt que sur la disponibilité globale (page impactée: /magistrats)
- ETQ agent de direction, je vois la disponibilité par département lorsque le filtre est actif (page impactée: /directions)

Je viens de réaliser que nous avons confondu, assez facilement, et sans s'en rendre compte, disponibilité et mesures souhaitées.
Nous n'avons pas établi comment on obtient la disponibilité par département à partir du nombre de mesures souhaitées par département.
Possibilités:
- il s'agit bien de disponibilité indicative et le mandataire doit les ajuster à la main au fil de l'eau pour informer les magistrats
- il faut un moyen de soustraires les mesures, nous avons bien un département sur la mesure (il s'agit de celui du majeur) mais quid des cas où le département du majeur n'est pas celui de sa prise en charge (établissement dans le département adjacent par exemple)
- ajouter un champs sur la réservation de la mesure (renseignable côté magistrat et mandataire, pour laisser la possibilité au mandataire de le renseigné au moment de l'acceptation si le magistrat ne l'a pas fait), mais l'information risque d'être manquante pour les mesures importée (que ce soit via OCMI ou l'API des autres éditeurs de logiciels)
Aucun solution n'étant pleinement satisfaisante sur cette problématique, cela serait bien que l'on en discute rapidement.

@celinelr @vicmartinezp

**Comment by celinelr** [comment]
Suite à notre point ce jour :  

Piste : un seul compte pourrait avoir plusieurs services au lieu de plusieurs comptes par service -> Faisable ? - attente de retour de @devthejo 

A la suite de cela nous (@vicmartinezp  et @celinelr ) contacterons certains services pour vérifier notre hypothèse de développement

**Comment by devthejo** [comment]
Je confirme que cela est possible mais nécessite plusieurs refactos, je viens d'identifier et de baliser au moins 16 emplacements impactés dans le code, chacun de ces emplacements étant la source d'une arborescence de modifications. C'est un énorme travail et il reste le plus important: déterminer le fonctionnement au niveau de l'UX pour un service.
Solutions envisagées:
1. Un switch général (déterminer où il serait positionné) pour passer de la gestion d'un service à un autre, avec un rappel du service selectionné.
Pros:
- plus rapide à développer (encore que c'est à vérifier, pas certain)
- cela ressemble déjà à la manière dont fonctionnent les services en multi département, on leur évite simplement d'avoir à se logguer et délogguer et de gérer plusieurs utilisateurs
Cons:
- moins user firendly
- comment on détermine sur quel service on arrive par défaut lorsque aucun n'est encore sélectionné (ou alors il faut prévoir une vue supplémentaire pour sélectionner un service)
2. Une aggrégation sur chaque vue, puis un filtre ou un switch selon chaque vue (ex: un filtre pour la liste des mesures, des onglets pour la page vos informations etc...)
Pros:
- plus cohérent
- plus user firendly
Cons:
- plus de travail
- il faut bien identifier chaque vue impactée et comment elle l'est avant de commencer les travaux

L'approche service en multi-département avait l'avantage d'être similaire en terme de fonctionnement avec la gestion actuelle des mandataires individuels et préposé (qui ont respectivement plusieurs départements associés, via les agréments pour les individuels ou les établissement pour les préposé). Cette solution représentait également moins de chamboulement du code et l'évolution vers quelque chose de plus cohérent au niveau global.
Si nous conservions cette approche, le même résultat aurait pu être atteint en gardant un seul service mais en l'affichant plusieurs fois côté magistrat (un par département) et en le suffixant avec le numéro de département (tel que les services sont déjà nommé actuellement). Le magistrat réserverait donc un une mesure en spécifiant obligatoirement à quel département cela fait référence et nous aurions obligatoirement cette donnée pour calculer des dispos par département. Mais nous aurions toujours le problème de l'info manquant au niveau des imports.

Autre possibilité, le principe d'antenne de service réponds bien à cette problématique, car on peut spécifier une disponibilité par antenne, la seul limitation que l'on avait était que le service était limité à un département, mais, étant donnée qu'il ne l'est plus, on peut très bien créer une antenne par département. Je vois qu'au moment d'accepter la mesure le mandataire spécifie son antenne (ce que moi j'appelai, la localisation d'éxecution de la mesure).

Tout semble résolu avec cette dernière approche. La seul chose qui nous a empêché de l'envisager clairement, c'est nos lacunes concernant le fonctionnement d'eMJPM, j'insiste donc sur le fait qu'une des priorités majeures devrait être d'établir une documentation exhaustive métier/données d'eMJPM décrivant tous les process d'actions sur les données à partir des besoins métier (un genre de doc technique et condensée à destination des PO aussi bien que des Devs). C'est un travail à réaliser en collaboration étroite entre nous.

Le seule chose qu'il reste à faire est de s'assurer auprès des intéressés (les services qui ont besoin de fonctionner en multidépartement et qui ont déjà des antennes), si cela ne pose aucun problème par rapport à leur façon actuelle de fonctionner avec les antennes. Je vois qu'un des service en question a déjà deux antennes, cela ne devrait pas lui posait de problème mais il faut qu'on s'en assure en organisant un call, auquel je pense qu'il préférable que je participe.

@celinelr @vicmartinezp

**Comment by celinelr** [comment]
Merci Jo pour cette analyse détaillée! 

Cette dernière approche me semble très interessante ! 
Est ce que / comment je pourrais t'aider dans la rédaction de cette documentation ? 

Pour ce qui est de prévoir un "workshop/atelier/call" avec des services, je pense que Victoria tu es la meilleure référente sur le sujet.

**Comment by celinelr** [comment]
Je propose un petit atelier lundi pour définir les objectifs de documentation ainsi que sa forme
