### ISSUE TITLE
Créer un nouveau profil greffiers

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2574]
Création d'un nouveau profil greffiers. Deux actions nécessaires 
- Échange avec 1 ou 2 magistrats pour vérifier le besoin
- Imaginer comment cela se traduit sur eMJPM : un greffier peut réserver des mesures sur le compte de plusieurs magistrats, mais juste dans un seul tribunal --> associer un greffier à un tribunal

**Comment by devthejo** [comment]
- user type - Il s'agit d'un nouveau type d'utilisateur à part entière
- role greffier - Il s'agit d'un nouveau role à part entière (gestion des drtois à dupliquer à partir de ti/magistrat)
- créer une table greffier (ti_id, user_id) pour faire la liaison entre la tribunaux et les greffier (comme la table magistrat le fait pour les users de type magistrat/ti)
- impacts:
  - page d'inscription selecteur de type (décliner depuis l'inscription du magistrat)
  - onglet greffier dans vue admin
  - dupliquer toutes les pages magistrats pour le greffier (les découpler pour anticiper des spécifications propres à ce type d'utilisateur)

**Comment by celinelr** [comment]
Page d'inscription :
- Dans la liste déroulante ajouter "Greffier" en dessous de "Juge de tutelle"

**Comment by celinelr** [comment]
Permettre à un magistrat de passer à un profil greffier, regarder la possibilité ?
Bouton coté admin ?

**Comment by celinelr** [comment]
Dans le processus de création de compte greffier erreur en anglais si j'enlève ce qu'il y a dans le champ tribunal 

<img width="762" alt="Capture d’écran 2021-11-23 à 17 28 48" src="https://user-images.githubusercontent.com/86293911/143064303-da43e1a0-8e6d-48b1-bb82-a70428e3027b.png">

**Comment by devthejo** [comment]
merci du retour, sur magistrat également, le fix est cours de deploy

**Comment by celinelr** [comment]
Lorsque j'ai fait mon inscription en tant que greffier j'ai rentré mon nom de cabinet mais il n'apparait pas dans la vue admin 
<img width="1216" alt="Capture d’écran 2021-11-23 à 17 33 49" src="https://user-images.githubusercontent.com/86293911/143065123-47010a12-1713-43d1-a29c-c3e9f43235f2.png">

**Comment by celinelr** [comment]
J'ai validé le compte du greffier mais lorsque je fais impersonnate en tant qu'admin j'arrive sur une page blanche
<img width="1438" alt="Capture d’écran 2021-11-23 à 17 34 25" src="https://user-images.githubusercontent.com/86293911/143065305-e49be08f-9710-4388-9e93-600eb884ca24.png">

**Comment by celinelr** [comment]
Dans le profil Greffier le champ cabinet se vide (ne garde pas l'information du cabinet) dès lors que je clique sur "modifer vo informations"

<img width="1438" alt="Capture d’écran 2021-11-23 à 17 34 25" src="https://user-images.githubusercontent.com/86293911/143068888-3526b208-4453-455a-bff1-bf1888b16888.png">

**Comment by devthejo** [comment]
yep, c'est exactement là dessus que je suis ;)

**Comment by devthejo** [comment]
le cabinet n'était pas restitué, même bug avec le profil magistrat, c'est corrigé et en cours de déploiement, ce qui est bien c'est qu'on va corrigé plein d'erreur du profil magistrat en même temp :-)

**Comment by celinelr** [comment]
Nous avons 3 greffiers qui testent actuellement la feature. Je reviens vers eux la semaine prochain pour connaitre leur expérience
