### ISSUE TITLE
SERVICES - Incohérences entre le référentiel Services et la liste blanche

### ISSUE THREAD

**Issue by vicmartinezp** [SocialGouv/emjpm#2577]
Lorsqu'on ajoute un service dans la liste blanche, les nom/prénom du responsable ne sont pas demandés. Or, il s'agit de champs obligatoires dans l'onglet Service (par exemple).

Cohérence globale à assurer entre les deux liste. Plein de données manquantes (et peut-être non nécessaires).

**Comment by devthejo** [comment]
linked to #2588
