### ISSUE TITLE
ETQ direction ou admin remonter l'erreur de SIRET déjà existant

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/emjpm#2587]
Liste blanche, tentative d'insérer une entrée avec un SIRET déjà existant

**Comment by celinelr** [comment]
il faudrait ajouter un message d'erreur explicite pour les utilisateurs pour les informer qu'il n'est pas possible de rentrer cette donnée car elle existe deja dans e-mjpm

**Comment by celinelr** [comment]
Je valide merci
