### ISSUE TITLE
Quand une enquête est lancée les mandataires doivent être prévenus par un bandeau sur la page d'accueil

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/emjpm#2589]
et invité à mettre à jour leurs informations eMJPM pour pouvoir bénéficier du préremplissage, avant d'aller sur l'enquête

**Comment by celinelr** [comment]
Ca avait été fait ou tu l'avais seulement close cette issue ?

**Comment by devthejo** [comment]
only closed, next "enquêtes" challengers will work on this, not us ;)

**Comment by celinelr** [comment]
All right ! Thanks for the comment
