### ISSUE TITLE
Remplacer automatiquement l'email dans la liste-blanche lorsqu'on associe un utilisateur via le SIRET

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/emjpm#2590]

**Comment by celinelr** [comment]
C'est développé ? Je croyais que ce n'etait pas possible car le match entre la liste blanche se faisait pas le siret justement

**Comment by devthejo** [comment]
Nope, je l'ai close car plus d'actualité, il s'est mis tout seul dans la colonne "développement done"
