### ISSUE TITLE
En tant que service je veux voir toutes les mesures dans mon onglet mesure même si la mesure n'est pas associée à une antenne

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2592]
# situation actuelle

Si une mesure n'est pas associée à une antenne, elle n'apparait pas dans l'onglet mesure via le systeme de tri. 

# Solution 

afficher une vignette similaire à celle des antennes mais avec ecrit "mesure sans antenne"
+ 
Ajouter dans le filtre antenne cette nouvelle rubrique

**Comment by devthejo** [comment]
ajouter un KPI "sans antenne"
ajouter un filtre "sans antenne"
