### ISSUE TITLE
Messages d'erreurs non qualifiés et en anglais

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2651]
**Describe the bug**
## 1. Champ tribunal d'une mesure
Mesure > modification > supprimer le champs tribunal 
<img width="576" alt="Capture d’écran 2021-09-24 à 15 39 06" src="https://user-images.githubusercontent.com/86293911/134684001-053ab7f4-569c-4896-a60b-fe5be882728e.png">

"ti_id must be a `string` type, but the final value was: `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`" 
Remplacer par :
<img width="238" alt="Capture d’écran 2021-09-24 à 15 40 43" src="https://user-images.githubusercontent.com/86293911/134684134-6e347758-1276-4366-a50e-c55c2511d84b.png">
"Veuillez renseigner ce champ."

## 2. Ajout d'un mandataire individuel à la liste blanche
Admin>liste blanche  > ajouter un mandataire indiv > champ d'adresse

<img width="695" alt="Capture d’écran 2021-09-24 à 15 48 08" src="https://user-images.githubusercontent.com/86293911/134685387-e86de74d-d792-4fa1-b4c6-fd083f8dc24e.png">
"adresse1 must be a `string` type, but the final value was: `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`
"

Remplacer par :
<img width="238" alt="Capture d’écran 2021-09-24 à 15 40 43" src="https://user-images.githubusercontent.com/86293911/134684134-6e347758-1276-4366-a50e-c55c2511d84b.png">
"Veuillez renseigner ce champ."

**Comment by celinelr** [comment]
@devthejo je viens de découvrir un nouveau message en anglais 

**édition d'une mesure**, remplir le champ d'année de naissance par des caractères 
<img width="731" alt="Capture d’écran 2021-09-28 à 10 29 34" src="https://user-images.githubusercontent.com/86293911/135052110-8607c93f-2066-4b48-9281-ec578553145b.png">

**Comment by celinelr** [comment]
Par contre je valide les problèmes précédents ! Merci

**Comment by devthejo** [comment]
Il manquait le picker d'année, c'est bugfixé

**Comment by celinelr** [comment]
top je valide, merci

**Comment by celinelr** [comment]
J'ai le problème d'erreur en anglais dans l'édition d'une mesure lorsque je fais un changement d'état. 

Si je remplis le champs pays puis que je retire l'entrée alors le champs code postal et ville se mettent en erreur non qualitfiée et en anglais 
<img width="521" alt="Capture d’écran 2021-10-06 à 09 32 14" src="https://user-images.githubusercontent.com/86293911/136162492-60caf9af-68a7-4aba-955c-78e8aa14e2f2.png">

**Comment by celinelr** [comment]
Lors de la cloture d'une mesure `date_fin_mesure must be a `date` type, but the final value was: `Invalid Date`.``
<img width="1254" alt="Capture d’écran 2021-11-23 à 11 33 20" src="https://user-images.githubusercontent.com/86293911/143008980-e047a85a-9e6b-4907-aec9-fcfb281aef0b.png">

**Comment by celinelr** [comment]
Formulaire d'ajout de tribunal pour le champ 'correspond au tribunal actuel'

J'ai ce message si j'enlève un tribunal selectionné

<img width="1172" alt="Capture d’écran 2021-11-23 à 16 52 13" src="https://user-images.githubusercontent.com/86293911/143057764-7a9a1caf-ee36-43ce-8892-14cdcc883993.png">

**Comment by devthejo** [comment]
corrigé et bientôt redéployé

**Comment by celinelr** [comment]
Merci pour ces corrections
