### ISSUE TITLE
Problèmes de champs coupés 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2652]
**Describe the bug**
## login page 

Vu qu'en préprod, pas en prod
<img width="528" alt="Capture d’écran 2021-09-24 à 15 53 30" src="https://user-images.githubusercontent.com/86293911/134685988-6b3ac43e-7fa4-49c9-af66-960ad7eb632f.png">

**Comment by celinelr** [comment]
Je n'ai plus ce background bleu , par contre la ligne du bas du dernier champ a disparu
 
<img width="470" alt="Capture d’écran 2021-09-28 à 11 07 10" src="https://user-images.githubusercontent.com/86293911/135058262-623e5033-9c4a-43fc-956d-e9e5eab96e1c.png">

**Comment by celinelr** [comment]
Sur google tout est parfait ! 

Sur firefox j'ai toujours du jaune, mais ce background n'impacte plus les éléments de l'interface cf. image 

<img width="509" alt="Capture d’écran 2021-09-28 à 17 19 10" src="https://user-images.githubusercontent.com/86293911/135116652-eaeb24ec-9077-4d2a-8ac4-5f171d38403a.png">

**Comment by devthejo** [comment]
bugfixed
