### ISSUE TITLE
[Edition d'une mesure ]Si je change la commune de vie d'un  majeur alors celle ci doit changer dans le résumé de la mesure

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2665]
**Describe the bug**
En tant que mandataire je veux changer la commune de vie d'un majeur afin d'indiquer un changement d'état.
Malheureusement ce changement d'état n'est pas pris en compte dans le resumé de la mesure

<img width="1055" alt="Capture d’écran 2021-10-06 à 09 33 11" src="https://user-images.githubusercontent.com/86293911/136164288-622e41a3-b19d-4e4d-b1c7-e149d675bd78.png">

**Comment by devthejo** [comment]
ce qui est marrant c'est que lorsqu'on met à jour le dernier état d'une mesure, là ça synchronise bien

**Comment by celinelr** [comment]
Je close car en fait le resumé se met à jour en fonction de la date du dernier changement d'état de la mesure. Si on ajoute un changement d'état mais avec une date antérieure au dernier état présent, alors il n'y à pas de mise à jour de la mesure. Cf screenshot
