### ISSUE TITLE
[RGAA] Éléments obligatoires 8.7 Dans chaque page web, chaque changement de langue est-il indiqué dans le code source (hors cas particuliers) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2675]
P11	Mandataire : Import d'une mesure	https://testdb-emjpm.dev.fabrique.social.gouv.fr/mandataires/import-mesures	

**Au moins un mot ou un passage de texte dont la langue est différente de la langue par défaut n'est pas identifié.Par exemple :**
- Le message d'erreur "Unexpected error processing file"

**Corrections :**
- Pour chaque mot en langue étrangère, ajouter un attribut lang pour indiquer la langue des termes :
`<span lang="en">Unexpected error processing file</span>`

**solution** 
- Mettre un message générique en francais et ajouter une balise code dans laquelle l'erreur technique s'y trouve
Je propose "Une erreur est survenue"

**Comment by celinelr** [comment]
As tu une idée comment je pourrais tester cela ? :)

**Comment by unicscode** [comment]
c'est compliqué a tester. c'est une erreur qui est retourné lorsque les imports échouent, l'api retourne Unexpected error...
ce que j'ai fait c'est que je catch ces erreurs la et je les remplace par "Une erreur est survenue"

**Comment by celinelr** [comment]
Ok, as tu aussi ajouté une balise code dans laquelle l'erreur technique s'y trouve ?
Je ne peux pas vérifier. Sinon je suis preneuse d'une video demo :)

**Comment by celinelr** [comment]
Pas de balise code car pas de valeur utilisateur

Suite à la demo, je valide
