### ISSUE TITLE
[RGAA] Images 1.1 Chaque image porteuse d'information a-t-elle une alternative textuelle ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2677]
## P01	Accueil	https://testdb-emjpm.dev.fabrique.social.gouv.fr/login

Au moins une image porteuse d'information n'a pas d'alternative textuelle.
Par exemple :
- Les images <svg> "Marianne"

Corrections :
- Pour les images <svg> "Marianne" : ajouter un role="img" et une propriété aria-label="République Française"

## P05	Magistrat : Tous les mandataires	https://testdb-emjpm.dev.fabrique.social.gouv.fr/magistrats

Au moins une image porteuse d'information n'a pas d'alternative textuelle.
Par exemple :
- L'image <svg> "homme"
- L'image <svg> "femme"
- L'image <svg> "Habilitation vérifiée"
- L'image <svg> "Le mandataire n'a pas exprimé son souhait de recevoir des mesures en provenance de votre tribunal"
- L'image <svg> "Il y a 11 places disponibles"

Corrections :
- Pour l'image <svg> "homme" : supprimer la propriété aria-hidden="true", ajouter un role="img" et une propriété aria-label="Monsieur".
- Pour l'image <svg> "femme" : supprimer la propriété aria-hidden="true", ajouter un role="img" et une propriété aria-label="Madame".
- Pour l'image <svg> "Habilitation vérifiée" : ajouter une propriété aria-label="Habilitation vérifiée".
- Pour l'image <svg> "Le mandataire n'a pas exprimé son souhait de recevoir des mesures en provenance de votre tribunal" : ajouter une propriété aria-label="Le mandataire n'a pas exprimé son souhait de recevoir des mesures en provenance de votre tribunal".
- Pour l'image <svg> "Il y a 11 places disponibles" : ajouter une propriété aria-label="Il y a 11 places disponibles".
## P06	Magistrat : La carte des mandataires	https://testdb-emjpm.dev.fabrique.social.gouv.fr/magistrats/map
	Au moins une image porteuse d'information n'a pas d'alternative textuelle.
Par exemple :
- L'image <svg> "homme"
- L'image <svg> "femme"

Corrections :
- Pour l'image <svg> "homme" : supprimer la propriété aria-hidden="true", ajouter un role="img" et une propriété aria-label="Monsieur".
- Pour l'image <svg> "femme" : supprimer la propriété aria-hidden="true", ajouter un role="img" et une propriété aria-label="Madame".
P09	Mandataire : Accueil	https://testdb-emjpm.dev.fabrique.social.gouv.fr/mandataires
	"Au moins une image porteuse d'information n'a pas d'alternative textuelle.
Par exemple :
- Le graphique <svg>

Corrections :
- Pour le graphique <svg> : ajouter un role=""img"" et une propriété aria-label=""14 mesures réparties par nature"""
## P10	Mandataire : Liste des mesures	https://testdb-emjpm.dev.fabrique.social.gouv.fr/mandataires/mesures
	Au moins une image porteuse d'information n'a pas d'alternative textuelle.
Par exemple :
- L'image <svg> "femme"
- L'image <svg> "homme"

Corrections :
- Pour l'image <svg> "femme" : ajouter un role="img" et une propriété aria-label="femme"
- Pour l'image <svg> "homme" : ajouter un role="img" et une propriété aria-label="homme"
## P15	Direction : Statistiques	https://testdb-emjpm.dev.fabrique.social.gouv.fr/direction/stats	
Au moins une image porteuse d'information n'a pas d'alternative textuelle.
Par exemple :
- Les graphiques <svg> "Disponibilités par type de mandataires", "Répartition de l’activité par type de mandataires" et "Disponibilités par territoire"

Corrections :
- Pour le graphique <svg> "Disponibilités par type de mandataires", ajouter un role="img" et une propriété aria-label="Disponibilités par type de mandataires"
- Pour le graphique <svg> "Répartition de l’activité par type de mandataires", ajouter un role="img" et une propriété aria-label="166 mesures réparties par type de mandataire"
- Pour le graphique <svg> "Disponibilités par territoire", ajouter un role="img" et une propriété aria-label="Disponibilités par territoire"

**Comment by celinelr** [comment]
Profil magistrat > Vos mandataires > Image service

Pour l'image "Service" : supprimer la propriété aria-hidden="true", ajouter un role="img" et une propriété aria-label="Service".

Profil magistrat > La carte des mandataires > Image service

Pour l'image "Service" : supprimer la propriété aria-hidden="true", ajouter un role="img" et une propriété aria-label="Service".

**Comment by celinelr** [comment]
## Image femme - homme

Dans Profil magistrat > Vos mandataires  ET Profil magistrat > La carte des mandataires Les icones homme et femme sont nommés monsieur, madame. 
Alors que dans Profil magistrat > Vos mesures Les icones homme et femme sont nommés homme et femme. 

-> uniformiser la dénomination -> homme et femme pour ces icones 


![Capture d’écran 2022-01-31 à 12 14 36](https://user-images.githubusercontent.com/86293911/151784562-922ff115-e4dc-4748-ba7a-9b0d5eee41ed.png)

**Comment by celinelr** [comment]
Mandataire > Carte 

Je ne vois pas de mention Femme / Homme sur les images des mesures 

![Capture d’écran 2022-01-31 à 12 43 12](https://user-images.githubusercontent.com/86293911/151788143-3b049db7-2d59-4fd4-b3a8-b88ce5cc7628.png)

**Comment by celinelr** [comment]
@unicscode lorsque je parle de problème pour le profil magistrat, je ne précise pas qu'il y a les memes sur le profil greffier mais c'est le cas, car ces deux profils sont identiques dans les données. Il faudra donc aussi faire les corrections coté greffier s'il te plait :)

**Comment by celinelr** [comment]
Même si ce n'est vu que par les admins, peux tu ajouter une balise et une description "Impersonnate" pour cette image s'il te plait ?
Cela se trouve sur la liste des utilisateurs 
![Capture d’écran 2022-01-31 à 13 17 39](https://user-images.githubusercontent.com/86293911/151792547-deed8a75-ccb9-45a4-9800-ef14db550826.png)

**Comment by celinelr** [comment]
Je valide tout. Tu as privilégier mettre Madame/Monsieur plutot que Femme/Homme. Ca me va.

**Comment by celinelr** [comment]
Agent de l'état > Statistique > vue globale > graph "Disponibilités par type de mandataires"

Lorsque je passe mon curseur sur un batonnet j'ai des infos que je ne retrouve pas dans le code pour l'accessibilité. Crois tu que c'est conforme ? Pouvons nous retranscrire ces informations ? 

![Capture d’écran 2022-02-04 à 18 07 52](https://user-images.githubusercontent.com/86293911/152572371-cf2e5c16-7c5b-416b-bee3-9357c420b5f1.png)

**Comment by unicscode** [comment]
oui, il y a un aria-label et un aria-describedby sur le svg

**Comment by unicscode** [comment]
les charts sont considérés comme des images, donc une description suffit. on peut utiliser une autre technique qui consiste a cacher le graph pour les screen reader et le remplacer avec un tableau visible uniquement par les screen reader.
tu me dis si tu veux implémenter cette solution

**Comment by celinelr** [comment]
Merci pour ton retour ! On en parle avec @vicmartinezp Lundi en sprint planning :D

**Comment by celinelr** [comment]
Merci je valide les tableaux
