### ISSUE TITLE
[RGAA] Éléments obligatoires 8.6 Pour chaque page web ayant un titre de page, ce titre est-il pertinent ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2678]
## P02	Mention légales	https://testdb-emjpm.dev.fabrique.social.gouv.fr/mentions-legales	
"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>Mentions légales | e-MJPM</title>"
## P03	Accessibilité	https://testdb-emjpm.dev.fabrique.social.gouv.fr/rgaa
	"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>Déclaration d'accessibilité | e-MJPM</title>"
## P04	Politique de confidentialité	https://testdb-emjpm.dev.fabrique.social.gouv.fr/politique-confidentialite
	"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>Politique de confidentialité | e-MJPM</title>"
## P6	Magistrat : La carte des mandataires	https://testdb-emjpm.dev.fabrique.social.gouv.fr/magistrats/map
	"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>La carte des mandataires | e-MJPM</title>"
## P07	Magistrat : Réserver une mesure	https://testdb-emjpm.dev.fabrique.social.gouv.fr/magistrats/gestionnaires/individuel-18/reservation
	"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>Réserver une mesure auprès de Lucie KAO | e-MJPM</title>"
## P08	Magistrat : Votre mesure	https://testdb-emjpm.dev.fabrique.social.gouv.fr/magistrats/mesures/180
	"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>Votre mesure | e-MJPM</title>"
## P09	Mandataire : Accueil	https://testdb-emjpm.dev.fabrique.social.gouv.fr/mandataires
	"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>Tableau de bord | e-MJPM</title>"
## P11	Mandataire : Import d'une mesure	https://testdb-emjpm.dev.fabrique.social.gouv.fr/mandataires/import-mesures
	"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>Importer vos mesures | e-MJPM</title>"
## P12	Mandataire : Mesure	https://testdb-emjpm.dev.fabrique.social.gouv.fr/mandataires/mesures/191
	"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>Curatelle renforcée aux biens
11A11111 | e-MJPM</title>"
## P13	Direction : Liste blanche	https://testdb-emjpm.dev.fabrique.social.gouv.fr/direction
	"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>Liste blanche | e-MJPM</title>"
## P14	Direction : Vue détaillée des profiles de la liste blanche	https://testdb-emjpm.dev.fabrique.social.gouv.fr/direction/liste-blanche/services/7
	"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>AMINE-TEST Adbel - Mandataire individuel | e-MJPM</title>"
## P15	Direction : Statistiques	https://testdb-emjpm.dev.fabrique.social.gouv.fr/direction/stats	
"Le titre de la page n'est pas pertinent.

Correction :
- Modifier le titre de la page sur le modèle : <title>Statistiques | e-MJPM</title>"

**Comment by celinelr** [comment]
Je crois que cette issue correspond à #2639 Peux tu me le confirmer @unicscode ? :)

**Comment by unicscode** [comment]
@celinelr oui, c'est la meme

**Comment by celinelr** [comment]
https://testdb-emjpm.dev.fabrique.social.gouv.fr/mandataires/informations > "Informations sur le mondataire | e-MJPM " à remplacer par "Informations sur le mandataire | e-MJPM " (il y a une faute sur le mot mandataire)

**Comment by celinelr** [comment]
https://testdb-emjpm.dev.fabrique.social.gouv.fr/magistrats/gestionnaires/service-2
Profil magistrat > Vos mandataires > lorsque je sélectionne un mandataire ou service le titre est "[Nom]| e-MJPM"-> il manque un espace après le nom  ce qui fait que le nom est collé à la barre. 

![Capture d’écran 2022-01-31 à 15 29 16](https://user-images.githubusercontent.com/86293911/151811630-49122570-45eb-41ff-abb7-228aa15279c0.png)

**Comment by celinelr** [comment]
https://testdb-emjpm.dev.fabrique.social.gouv.fr/magistrats/map "la carte des mandataires | e-MJPM " rajouter une majuscule en début de phrase "La carte des mandataires | e-MJPM"

**Comment by celinelr** [comment]
Le profil greffier est identique à celui des magistrats. 
Lorsque je clique sur un mandataire j'ai "Gestionnaire individuel-13 | e-MJPM" dans cet exemple au lien d'avoir le nom prenom comme c'est le cas pour le profil magistrat
![Capture d’écran 2022-01-31 à 15 32 53](https://user-images.githubusercontent.com/86293911/151812994-868d14bd-f19a-4c0f-be7a-cb5ad5931c7b.png)
![Capture d’écran 2022-01-31 à 15 33 15](https://user-images.githubusercontent.com/86293911/151812998-8fd57173-329a-40c0-b19a-ca441f2f6074.png)

**Comment by celinelr** [comment]
Que ce soit pour le profil magistrat ou greffier > vos mesures > si je sélectionne une mesure le tire est "Mesure [chiffre] | e-MJPM"

Il faudrait que ce chiffre soit le numéro RG, ce n'est pas le cas. 
![Capture d’écran 2022-01-31 à 15 48 07](https://user-images.githubusercontent.com/86293911/151814779-f70e5742-d65a-41eb-9917-fbbf7b9d314c.png)

**Comment by celinelr** [comment]
P13 Direction : Liste blanche https://testdb-emjpm.dev.fabrique.social.gouv.fr/direction
"Le titre de la page n'est pas pertinent. "Direction | e-MJPM"
Correction :
Modifier le titre de la page sur le modèle : <title>Liste blanche | e-MJPM</title>"

**Comment by celinelr** [comment]
Je valide tout sauf un détail 


Il manque une majuscule sur le profil magistrat > vos mesure  > Selection d'une mesure 

Cf . Le comportement correct du profil greffier >  vos mesures > Selection d'une mesure 

![Capture d’écran 2022-02-04 à 17 47 32](https://user-images.githubusercontent.com/86293911/152569208-44a985f2-efa1-42e1-97a2-ac5807887f04.png)

Mettre une majuscule en début de titre
![Capture d’écran 2022-02-04 à 17 47 18](https://user-images.githubusercontent.com/86293911/152569213-c8cab093-0e11-469e-b777-fa2fae5b89a0.png)
