### ISSUE TITLE
Le champs de recherche liste des tribunaux ne fonctionne pas dans le profil magistrat

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2688]
**Describe the bug**
- Profil magistrat
- Modifier vos informations
- Changer de tribunal > faire une recherche
- la liste de propositions ne se met pas à jour en fonction de la recherche

**Comment by devthejo** [comment]
même chose sur le parcours d'inscription magistrat

**Comment by celinelr** [comment]
Mince ! Merci pour la modification, je vais recetter demain
