### ISSUE TITLE
[RGAA] Couleurs	3.3	Dans chaque page web, les couleurs utilisées dans les composants d'interface ou les éléments graphiques porteurs d'informations sont-elles suffisamment contrastées (hors cas particuliers ) ? Couleurs	3.2	Dans chaque page web, le contraste entre la couleur du texte et la couleur de son arrière-plan est-il suffisamment élevé (hors cas particuliers) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2696]
## P01	Accueil	https://testdb-emjpm.dev.fabrique.social.gouv.fr/login	Au moins un composant d'interface ou un élément graphique porteur d'information n'est pas suffisamment contrasté.
Par exemple :
- La couleur #D4D4D4 de la bordure sur le fond #FFFFFF (ratio : 1.5)

Corrections :
- Contrôler tous les contrastes des composants d'interface et des éléments graphiques et vérifier qu'ils sont suffisants (3:1).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

## P05	Magistrat : Tous les mandataires	https://testdb-emjpm.dev.fabrique.social.gouv.fr/magistrats	Au moins un composant d'interface ou un élément graphique porteur d'information n'est pas suffisamment contrasté.
Par exemple :
- La couleur #D4D4D4 de la bordure des champs de formulaire sur le fond #FFFFFF (ratio : 1.5)
- La couleur #70D54F de l'icône sur le fond #FFFFFF (ratio : 1.9)
- La couleur #70D54F de l'icône sur le fond #E5E5E5 (ratio : 1.5)
Corrections :
- Contrôler tous les contrastes des composants d'interface et des éléments graphiques et vérifier qu'ils sont suffisants (3:1).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

## P07	Magistrat : Réserver une mesure	https://testdb-emjpm.dev.fabrique.social.gouv.fr/magistrats/gestionnaires/individuel-18/reservation	Au moins un composant d'interface ou un élément graphique porteur d'information n'est pas suffisamment contrasté.
Par exemple :
- La couleur #D4D4D4 de la bordure des champs de formulaire sur le fond #FFFFFF (ratio : 1.5)

Corrections :
- Contrôler tous les contrastes des composants d'interface et des éléments graphiques et vérifier qu'ils sont suffisants (3:1).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

## P10	Mandataire : Liste des mesures	https://testdb-emjpm.dev.fabrique.social.gouv.fr/mandataires/mesures	Au moins un composant d'interface ou un élément graphique porteur d'information n'est pas suffisamment contrasté.
Par exemple :
- La couleur #007AD9 de l'icône du bouton "Exporter" sur le fond #F2F5F9 (ratio : 4.01)
- La couleur #D4D4D4 de la bordure des champs de formulaire sur le fond #FFFFFF (ratio : 1.5)
Corrections :
- Contrôler tous les contrastes des composants d'interface et des éléments graphiques et vérifier qu'ils sont suffisants (3:1).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).
## P11	Mandataire : Import d'une mesure	https://testdb-emjpm.dev.fabrique.social.gouv.fr/mandataires/import-mesures	Au moins un composant d'interface ou un élément graphique porteur d'information n'est pas suffisamment contrasté.
Par exemple :
- La couleur #D4D4D4 de la bordure du champ sur le fond #FFFFFF (ratio : 1.5)
Corrections :
- Contrôler tous les contrastes des composants d'interface et des éléments graphiques et vérifier qu'ils sont suffisants (3:1).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

**Comment by celinelr** [comment]
[Contraste de couleur accessible.xlsx](https://github.com/SocialGouv/emjpm/files/8365432/Contraste.de.couleur.accessible.xlsx)


Voici le fichier qui regroupe toutes les couleurs de eMJPM ainsi que tous les composants non accessibles 

Dans la tab 1 "couleurs" j'affiche une nouvelle correspondance pour toutes les couleurs non-accessibles 
Dans la tab 2 "composants" le listing de toutes les composants non accessibles avec leur couleur et les nouvelles correspondances de couleurs.

**Comment by celinelr** [comment]
[Recette contraste de couleur accessible (1).xlsx](https://github.com/SocialGouv/emjpm/files/8582895/Recette.contraste.de.couleur.accessible.1.xlsx)


@unicscode Voici le fichier de recette complet. Nous avons rajouté une colonne recette. Tu trouveras tous les composants à corriger sous le label "Non conforme" de cette colonne. A coté nous avons précisé les changements à faire.

Aussi, nous avons ajouté une tab "Recette autres composant non conformes" elle regroupe tous les composants qui n'étaient pas listés avant et qui ne sont pas conformes

**Comment by celinelr** [comment]
J'ajoute ici que le bouton d'ajout d'une mesure a disparu sur la carte des mandataires depuis le profil greffier et magistrat
<img width="1434" alt="Capture d’écran 2022-04-28 à 17 35 14" src="https://user-images.githubusercontent.com/86293911/165789894-e871c846-21c3-4a57-b1dd-1dbc49a7b279.png">

**Comment by wolvesjack** [comment]
•	URL : https://rgaa-emjpm.dev.fabrique.social.gouv.fr/admin/api-logs
 
Le contraste n’est pas suffisant (4.21). Dans le cahier de test il est écrit « le contour de la page 'https://testdb-emjpm.dev.fabrique.social.gouv.fr/admin/api-logs' a la couleur #ebeff5 au lieu de #767676. » En revanche la couleur est bien #767676 dans la version que je viens de tester. @
![api-logs](https://user-images.githubusercontent.com/106517262/171126269-1d0188a5-4479-49a5-a6a4-8cde9bb06aa8.png)

unicscode  As-tu une idée de la correction à apporter ?

•	URL : https://rgaa-emjpm.dev.fabrique.social.gouv.fr/admin/liste-blanche
élément : bouton « ajouter » / Background color #007AD9  #0072ca
 
![liste-blanche](https://user-images.githubusercontent.com/106517262/171126363-f97a1089-93c2-4f4a-b34a-9acf93a0b23f.jpg)
![liste-blanche](https://user-images.githubusercontent.com/106517262/171126368-6a13bee3-97c2-4b21-a00c-68d445c7725d.png)



Le contraste n’est pas suffisant (4.39).
