### ISSUE TITLE
[Mandataire] Verrouiller modification/ajout de mesure s'il y a une synchronisation automatique avec un éditeur 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2701]
**Is your feature request related to a problem? Please describe.**
En tant que mandataire je ne dois plus pouvoir ajouter ou modifier de mesure si ma synchronisation de mesure est activée grace à un éditeur. 

Nous voulons le même comportement qu'avec une synchronisation activée avec OCMI. 

Il faudrait changer le texte à 2 endroits :  
- Liste des mesures, au survole "La synchronisation de vos mesures avec votre éditeur est activée. Modifiez vos mesures sur le logiciel de votre éditeur"
- onglet "importer vos mesures" > Dans la rubrique "Synchronisez vos mesures". Remplacer le texte existant par : "Vos mesures sont synchronisés grâce à votre éditeur. Modifiez vos mesures sur le logiciel de votre éditeur."

**Comment by celinelr** [comment]
Tu as choisi d'implémenter un texte différent du mien et il est très bien.

**Comment by devthejo** [comment]
ah, sorry, j'avais pas vu que tu en avais mis un, je fais le changement si tu veux.

**Comment by devthejo** [comment]
mais rajoute le nom de l'éditeur quand même si ça te va.

**Comment by devthejo** [comment]
genre:
> La synchronisation de vos mesures avec votre éditeur est activée. Modifiez vos mesures sur le logiciel de votre éditeur "Nom de l'éditeur".

**Comment by celinelr** [comment]
Merci
