### ISSUE TITLE
Numéro RG message d'erreur en cas de doublon

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2704]
**Describe the bug**
Si je rentre un numéro RG deja existant sur le compte du mandataire le message "Le numéro RG que vous venez de saisir existe déjà sur votre compte eMJPM pour ce tribunal. Merci de le rectifier." s'affiche que si la personne rempli le champ du tribunal. 
Le champ numéro RG devrait se mettre en erreur en cas de doublons dès lors que je valide mon entrée. 

https://user-images.githubusercontent.com/86293911/141993326-40bc8cf2-d696-44d6-bc99-8b56b1a358a3.mov

**Comment by devthejo** [comment]
nope, un mandataire peut avoir un même numéro RG, c'est le doublon numero-rg+tribunal que l'on détecte, il est donc normal de devoir attendre d'avoir le tribunal, c'est également ce qu'indique le message d'erreur
