### ISSUE TITLE
Actualisation des documents légaux suite à l'ajout du profil greffier

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2705]
Voici les documents, en rouge, les ajouts/suppression d'Osiris

[[e-MJPM] - CGU.docx](https://github.com/SocialGouv/emjpm/files/7582844/e-MJPM.-.CGU.docx)
[[e-MJPM] - Politique de confidentialité.docx](https://github.com/SocialGouv/emjpm/files/7582845/e-MJPM.-.Politique.de.confidentialite.docx)

**Comment by celinelr** [comment]
Testé sur API test : 

Dans la Politique de confidentialité il manque : 

![Capture d’écran 2021-11-23 à 16 33 44](https://user-images.githubusercontent.com/86293911/143054339-6cc0ad62-42fc-445c-8f0e-ebcd967b0163.png)

A positition après "Données de profil des magistrats" dans le tableau "Durée de conservation"

**Comment by celinelr** [comment]
Testé dans les Conditions d’utilisation de la plateforme e-MJPM

Le titre "**B - Fonctionnalités proposées aux profils « greffiers »" est mal formaté. Il devrait etre en gras. Manquerait-il leds ** à la fin ?

<img width="918" alt="Capture d’écran 2021-11-23 à 16 35 38" src="https://user-images.githubusercontent.com/86293911/143054820-abb6962d-7224-498c-9e0b-dfc427aab955.png">

Dans la section "C - Fonctionnalités proposées aux profils « mandataires »" il manque "ou par un greffier ;" au 4eme point

![Capture d’écran 2021-11-23 à 16 37 12](https://user-images.githubusercontent.com/86293911/143055046-7d739ec1-459e-4199-a2af-ebb91b2d8194.png)

**Comment by devthejo** [comment]
les deux sont corrigés en bientôt redéployés

**Comment by celinelr** [comment]
Merci, je viens de vérifier
