### ISSUE TITLE
La mesure est marquée comme urgente alors qu'elle ne l'est pas 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2706]
Etrange regression :  

Que ce soit sur le profil greffier ou celui du magistrat  si j'indique que la mesure est urgente ou non elle sera toujours indiqué comme urgente dans la liste des mesures 

<img width="1230" alt="Capture d’écran 2021-11-23 à 17 57 32" src="https://user-images.githubusercontent.com/86293911/143069858-00ee08e5-9488-4d59-a04a-7909883b1723.png">

<img width="1182" alt="Capture d’écran 2021-11-23 à 17 57 42" src="https://user-images.githubusercontent.com/86293911/143069850-af769630-f4e0-4b45-a9bb-b048f1b0c671.png">

**Comment by celinelr** [comment]
J'ai testé : 
- L'inscription 
- La réservation de mesure 
- La suppression de mesure 
- Activation /desactivation du partage d'adresse email
- Changement de cabinet
- La carte

**Comment by devthejo** [comment]
OK cool, merci beaucoup !
Concernant la régression, c'était un oubli de debug, sorry, le fix est en cours de deploiement

**Comment by celinelr** [comment]
La carte, Les colonnes se chevauchent 

Sur le profil greffier : 
<img width="1440" alt="Capture d’écran 2021-11-23 à 18 06 53" src="https://user-images.githubusercontent.com/86293911/143070855-deda43b6-a8a8-4d57-8338-27f8aa7547ff.png">

Sur le profil magistrat 

<img width="1430" alt="Capture d’écran 2021-11-23 à 18 07 26" src="https://user-images.githubusercontent.com/86293911/143070930-2fc88e26-a4b2-4d94-b9c7-8b8224832e6b.png">

**Comment by devthejo** [comment]
merci du retour, c'est corrigé et en cours de déploiement ;)

**Comment by celinelr** [comment]
Si un mesure est marquée comme urgente, le signe doit aussi apparaitre coté mesure du mandataire lorsque la mesure est en attente. Ce n'est pas le cas aujourd'hui. 

![Capture d’écran 2021-12-08 à 15 37 39](https://user-images.githubusercontent.com/86293911/145227664-18b7e4ea-ea97-40b0-9064-fcd397ebbb53.png)
![Capture d’écran 2021-12-08 à 15 37 21](https://user-images.githubusercontent.com/86293911/145227672-cee75b97-70db-4a54-bc0e-e321fc4feb0f.png)

**Comment by celinelr** [comment]
Une fois la correction faite reverifier la liste sur la page des mandataires, celle des magistrat, greffier, carte

**Comment by devthejo** [comment]
bugfix en cours de déploiement ;)

**Comment by celinelr** [comment]
Tout me semble bien, merci Jo ! 

Pour être sûre, peux tu me confirmer qu'il est normal que les mesures en attente n'apparaissent pas sur la carte des mandataires ?

**Comment by devthejo** [comment]
Oui c'est délibéré dans le code, par contre je sais pas pour quelle raison c'est comme ça, mais c'est normal en tout cas.

**Comment by celinelr** [comment]
Merci pour ton retour ! Ok c'est noté
