### ISSUE TITLE
Ajouter dans la page de statistique le nombre de greffiers Inscrits

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2708]
Dans la page https://emjpm.fabrique.social.gouv.fr/stats je souhaiterais une nouvelle donnée. Celle des greffiers. 

A ajouter à la suite des magistrats. (A coté ou à la ligne)

![Capture d’écran 2021-12-01 à 17 35 21](https://user-images.githubusercontent.com/86293911/144275303-6fb8eff9-0c35-4a2b-abb9-2f9946ff7025.png)

Il faudrait l'information pour la france entière et par département

**Comment by celinelr** [comment]
Je vois qu'il y a marqué 0 greffiers en prod alors qu'il y en a un. Le calcul fonctionne t il ?

**Comment by devthejo** [comment]
C'était pourtant testé localement et cela fonctionnait, je regarde ça, merci du retour.

**Comment by devthejo** [comment]
Les migrations en DB ne sont pas passées.

**Comment by devthejo** [comment]
C'est corrigé.

**Comment by devthejo** [comment]
Par contre pas encore le login visiblement...

**Comment by celinelr** [comment]
Top merci je viens de vérifier. 

Merci aussi pour l'information pour le login

**Comment by devthejo** [comment]
Cette fois ci, c'est la bonne :-)
All's bugfixed.

**Comment by celinelr** [comment]
Top, merci ;)
