### ISSUE TITLE
Remplacer « Activité suspendue »  par "Activité interrompue"

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2717]
Un utilisateur nous informe que « Activité suspendue »  porte à confusion. En effet il s’analyse immédiatement comme « interdiction d’exercer » car le MJPM est mis en suspend le temps de l’enquête….

Nous remplacerons donc « Activité suspendue »  par "Activité interrompue"

**Comment by celinelr** [comment]
Il faudrait mettre "interrompu" coté magistrat sur la liste des mandataires
![Capture d’écran 2021-12-14 à 12 28 37](https://user-images.githubusercontent.com/86293911/145990379-c810a75e-ddc8-47b2-85b9-574f9f147014.png)

**Comment by devthejo** [comment]
c'est fait et en cours de déploiement sur l'instance de test

**Comment by celinelr** [comment]
sur la carte des mandataire il faudrait aussi afficher "Interrompu" 
![Capture d’écran 2021-12-14 à 16 04 20](https://user-images.githubusercontent.com/86293911/146024006-eb4a563f-1bb1-4bde-a4f8-1254f9c4d65a.png)
![Capture d’écran 2021-12-14 à 16 04 14](https://user-images.githubusercontent.com/86293911/146024030-2cc88c85-93f7-48a0-bcb9-64275b27b917.png)

**Comment by celinelr** [comment]
@devthejo cette issue n'est pas en prod. Est ce pour une raison particulière ou y a t il un problème ? ou ca sera dans la MEP d'aujourd'hui ?

**Comment by devthejo** [comment]
Dans la MEP de ce soir ;)

**Comment by celinelr** [comment]
OK :)
