### ISSUE TITLE
RGAA navigation au clavier encadré bleu

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2733]
Je n'ai pas d'encadré bleu avec la navigation au clavier 

## Dans la création de compte
- sur le bouton suivant dans la création de compte 1/2
- Sur les boutons retour de la enregistrer dans la création de compte 2/2
- L'encadré du bouton annuler de la enregistrer dans la création de compte 2/2 à lui une forme etrange (comme une extension à droite de l'encadré bleu, cf image)

<img width="1221" alt="Capture d’écran 2022-01-14 à 17 31 11" src="https://user-images.githubusercontent.com/86293911/149523643-d40ecb8f-e389-498a-92d2-97818c1bede9.png">

## Lorsqu'un mandataire accepte une mesure 
- sur les bouton annuler et valider
![Capture d’écran 2022-01-18 à 16 53 47](https://user-images.githubusercontent.com/86293911/149972650-93af525f-e491-4301-b161-7c3a128f5cd5.png)

**Comment by celinelr** [comment]
@devthejo prefères-tu que je l'assigne à @unicscode ?

**Comment by devthejo** [comment]
@celinelr yep

**Comment by celinelr** [comment]
OK merci !

**Comment by celinelr** [comment]
Merci, c'est corrigé
