### ISSUE TITLE
[RGAA] Formulaires 11.5	Dans chaque formulaire, les champs de même nature sont-ils regroupés, si nécessaire ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2736]
# P14	Direction : Vue détaillée des profiles de la liste blanche	https://testdb-emjpm.dev.fabrique.social.gouv.fr/direction/liste-blanche/services/7

## Des champs de même nature ne sont pas regroupés.Par exemple :
- Les champs "Départements" du bloc "Liste des agréments"
## Corrections :
- Utiliser l'élément <fieldset> pour regrouper les champs de même nature et l'élément <legend> pour donner un titre aux regroupements.
- ou utiliser le role="group" et la propriété aria-label="Départements" ou aria-labelledby="Départements"

**Comment by celinelr** [comment]
Est ce que tu peux me confirmer que dans madantaire individuel > edit informations le champ tribunaux dans  lesquels vous exercez est conforme à cette regle de regroupement ?  Est ce la "class="css-xiuxxt" qui prend le role de titre de regroupement dans cet exemple ?


![Capture d’écran 2022-02-02 à 17 10 59](https://user-images.githubusercontent.com/86293911/152192046-ecbffddd-f5f6-4d56-89c5-cf4c134a0504.png)

**Comment by celinelr** [comment]
Dans l'exemple que je donne pas besoin de regroupement mais regarder pour les autres formulaires

**Comment by celinelr** [comment]
Madataire -> mesure 
![Capture d’écran 2022-02-03 à 17 22 28](https://user-images.githubusercontent.com/86293911/152384048-a4e3a7b4-17b5-4ada-8741-2b4f1d7a9455.png)


le nom du groupe est "aria-labelledby="majeur_a_protger_heading"" il faudrait mettre proteger, il manque le e

Aussi, il y a de l'anglais faut il le mettre en francais ?

**Comment by celinelr** [comment]
Pareil pour ici

![Capture d’écran 2022-02-03 à 17 25 19](https://user-images.githubusercontent.com/86293911/152384503-66c189ec-99b4-4306-a86a-a5843bb750f3.png)

**Comment by celinelr** [comment]
mandataire > mesure en attente > accepter la mesure

![Capture d’écran 2022-02-03 à 17 32 30](https://user-images.githubusercontent.com/86293911/152385901-c3fbe932-ac86-4a1b-a138-53c1b55ab4b7.png)

Faut-il regrouper ces champs  ?

**Comment by celinelr** [comment]
mandataire > mesure en cours > cloturer la mesure 


![Capture d’écran 2022-02-03 à 17 33 50](https://user-images.githubusercontent.com/86293911/152386075-b404f080-2c0e-47e1-857c-3a56dac12d25.png)

Faut-il regrouper ces champs ?

**Comment by celinelr** [comment]
User -> modifier les infos > il manque le regroupement pour la structure juridique 
![Capture d’écran 2022-02-03 à 17 35 26](https://user-images.githubusercontent.com/86293911/152386403-1bbaec96-da4e-4043-904b-407c83f1811b.png)

**Comment by celinelr** [comment]
Mandataire Service > modifier les infos > il manque le regroupement pour les Informations personnelles
![Capture d’écran 2022-02-03 à 17 37 57](https://user-images.githubusercontent.com/86293911/152386790-cb875f1e-a78e-44b4-9b40-18059ca9765b.png)

**Comment by celinelr** [comment]
Direction > Liste blanche > Mandataire indiv

- Il manque le regroupement pour les informations personnelles
![Capture d’écran 2022-02-03 à 17 42 46](https://user-images.githubusercontent.com/86293911/152387895-f9b7b7a5-36c2-410b-b11f-9687134a321d.png)

- Je vois le aria labelled by mais je ne vois pas le role group pour <div id="structure_juridique" class="css-1cb1xl5">Structure juridique</div>
![Capture d’écran 2022-02-03 à 17 45 11](https://user-images.githubusercontent.com/86293911/152388215-62ba16a5-8b7c-4b92-b24a-dd9d59bc8234.png)

**Comment by celinelr** [comment]
Direction > Liste blanche > Service

- je vois le role group et le arialabelledby mais je pense que l'on peut changer le titre aria-labelledby="service_tutelaire_heading" par aria-labelledby="structure_juridique_heading" Qu'est ce que tu en penses ?

**Comment by unicscode** [comment]
oui, je peux le changer, même si l'utilisateur ne voit pas ça, c'est juste que ça renvoie a l'id "service_tutelaire_heading" qui contient le texte "Structure juridique"

**Comment by unicscode** [comment]
c'est fait

**Comment by celinelr** [comment]
> mandataire > mesure en attente > accepter la mesure
> 
> ![Capture d’écran 2022-02-03 à 17 32 30](https://user-images.githubusercontent.com/86293911/152385901-c3fbe932-ac86-4a1b-a138-53c1b55ab4b7.png)
> 
> Faut-il regrouper ces champs ?

Ces éléments ne sont pas régroupés sur l'environnement RGAA

![Capture d’écran 2022-02-14 à 10 10 07](https://user-images.githubusercontent.com/86293911/153833879-5731113a-02ba-4540-a348-0b6964d342d3.png)

**Comment by celinelr** [comment]
> mandataire > mesure en cours > cloturer la mesure
> 
> ![Capture d’écran 2022-02-03 à 17 33 50](https://user-images.githubusercontent.com/86293911/152386075-b404f080-2c0e-47e1-857c-3a56dac12d25.png)
> 
> Faut-il regrouper ces champs ?

Ici, aussi, faut il regrouper ces champs ?

**Comment by celinelr** [comment]
> Mandataire individuel ET preposé -> modifier les infos > il manque le regroupement pour la structure juridique ![Capture d’écran 2022-02-03 à 17 35 26](https://user-images.githubusercontent.com/86293911/152386403-1bbaec96-da4e-4043-904b-407c83f1811b.png)

Ces éléments ne sont pas regroupés

**Comment by celinelr** [comment]
Je ne poursuis pas la recette de ce ticket, Es tu sûr d'avoir livré cela sur l'environnement rgaa ?

**Comment by celinelr** [comment]
Tout semble corrigé, merci Koceila :)

**Comment by celinelr** [comment]
Tout semble corrigé, merci Koceila :)
