### ISSUE TITLE
Formulaire, champ obligatoire

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2748]
Lorsqu'un mandataire accepte une mesure il doit remplir un formulaire.
Les champs obligatoires ville et code postal sont obligatoire, pourtant il n'y a pas d'etoile rouge pour l'indiquer
![Capture d’écran 2022-01-18 à 16 53 47](https://user-images.githubusercontent.com/86293911/149972417-8dd9e0b7-85f2-4217-b8a5-bcc785d4a117.png)

**Comment by devthejo** [comment]
pour info: ce n'est pas détecté automatiquement parce qu'ils ne sont pas obligatoire lorsque le pays est autre que France.
C'est corrigé :)

**Comment by celinelr** [comment]
Oh ! Merci de l'information ! Je viens tester, je valide
