### ISSUE TITLE
Navigation au clavier

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2769]
## Profil magistrat > La carte des mandataires 

Si je navigue au clavier je ne peux pas accéder à la liste des mandataires et les selectionner. Il faudrait que ce soit le cas, comme dans l'onglet vos mandataires ou cela est possible 

## Profil magistrat > Vos mandataires > je selectionne un mandataire 

Lorsque je suis sur la page correspondant à un mandataire pour lui reserver une mesure je peux me déplacer au clavier partout. Toutes les boutons sont accessibles, par contre la partie listant toutes les informations du mandataire voice over ne les lit pas 

## Profil magistrat > vos informations

Lorsque je suis sur la page correspondant à vos information  je peux me déplacer au clavier partout. Toutes les boutons sont accessibles, par contre la partie listant toutes les informations du magistrat voice over ne les lit pas 

![Capture d’écran 2022-01-31 à 12 29 18](https://user-images.githubusercontent.com/86293911/151786244-0324469b-9cc3-42bb-b6bb-3c0af1553159.png)

## Profil mandataire

Voici les éléments non lu 

- tableau de board >
    -  rubrique vos indicateurs >  les chiffres 
    - rubrique vos tribunaux > Le texte 
    - Vos agrément > Texte 
    - Graphique 
![Capture d’écran 2022-01-31 à 12 47 27 (2)](https://user-images.githubusercontent.com/86293911/151788946-31d602aa-fab6-476f-9df5-2855eb1e0d1c.png)
- Mesures > une fois qu'une mesures est sélectionné
    - aucun texte n'est lu, sauf les boutons
![Capture d’écran 2022-01-31 à 12 51 52](https://user-images.githubusercontent.com/86293911/151789313-ac8cdbb3-d10f-462f-9253-7941ea8a01ab.png)
- Carte
    - je ne peux pas naviguer dans la liste des mesures 

![Capture d’écran 2022-01-31 à 12 46 38](https://user-images.githubusercontent.com/86293911/151789406-987ecef2-6b1b-4568-9495-2fbda136c9b3.png)
- Vos informations
    - Aucun texte n'est lu sauf les boutons

![Capture d’écran 2022-01-31 à 12 47 47](https://user-images.githubusercontent.com/86293911/151789619-578a2c81-5259-4ae6-af4d-13024a9d9492.png)

## Profil agent

- Statistique 
    - Piège au clavier je ne peux pas naviguer sur la page si je ne sélectionne pas une date de début 
![Capture d’écran 2022-01-31 à 13 05 22](https://user-images.githubusercontent.com/86293911/151791238-372db988-2643-470e-9ee1-8f76d7b6cfc4.png)
   - Tout le texte n'est pas lu / selectionnable
        - Stats
        - la vue détaillée, les mandataires
![Capture d’écran 2022-01-31 à 12 51 52](https://user-images.githubusercontent.com/86293911/151791559-4dd0bcf8-1767-4b13-893a-e480e0a85d5a.png)
       - La vue globale les graphiques 

![Capture d’écran 2022-01-31 à 13 11 03](https://user-images.githubusercontent.com/86293911/151791671-c34a2d72-9ca5-44e1-a7d8-94f1399d900d.png)

- Vos informations

    - Aucun texte n'est lu sauf les boutons

**Comment by celinelr** [comment]
@unicscode lorsque je parle de problème pour le profil magistrat, je ne précise pas qu'il y a les memes sur le profil greffier mais c'est le cas, car ces deux profils sont identiques dans les données. Il faudra donc aussi faire les corrections coté greffier s'il te plait :)

**Comment by celinelr** [comment]
J'ai beaucoup de mal à lire les tableaux et les comprendre dans la page direction > stat > vue globale https://rgaa-emjpm.dev.fabrique.social.gouv.fr/direction/stats

Est ce que tu peux me faire une demo demain s'il te plait ?

**Comment by celinelr** [comment]
Comme vu ensemble aujourd'hui, il faudrait supprimer les tableaux et ajouter une description à la place.

**Comment by wolvesjack** [comment]
**URL :** https://rgaa-emjpm.dev.fabrique.social.gouv.fr/magistrats/gestionnaires/service-7
Sur le bouton "Réserver une mesure", l'épellation vocalisée restitue "résérver"

![navigation clavier - aide vocale - épelation](https://user-images.githubusercontent.com/106517262/171192151-ca40a932-e1c7-4d23-b653-588c4c3ac5fa.png)

**URL :** https://rgaa-emjpm.dev.fabrique.social.gouv.fr/mandataires

Encart "Répartition des mesures par nature"
à  l'écran on restitue : 
- 2 curatelle renforcée
- 3 curatelle simple

l'aide vocale lit : 
"5 mesures réparties par nature.
- curatelle renforcée : 2
- curatelle simple : 3"
puis : "
- 2 curatelle renforcée
- 3 curatelle simple"

**CE N'EST PAS UNE ANOMALIE**, juste un peu déstabilisant. Si possible l'aide vocale pourrait ne lire que : 
"5 mesures réparties par nature.
- 2 curatelle renforcée
- 3 curatelle simple"
 
![navigation clavier - aide vocale - répartition](https://user-images.githubusercontent.com/106517262/171193949-c904617a-f3ba-46a6-a1d9-3b1ce8505612.png)

**URL** : https://rgaa-emjpm.dev.fabrique.social.gouv.fr/direction/stats > onglet "Statistiques" > bouton "vue globale"

Les disponibilités par type de mandataires sont présentées dans la description de l'image de l'histogramme comme suit : disponibilité max puis disponibilité actuelle
L'aide vocale, au contraire, va lire en premier la disponibilité actuelle puis la disponibilité max et enfin donner l'indication de surcapacité ("oui" ou "non")

**CE N'EST PAS UNE ANOMALIE**, juste par souci de meilleure cohérence : 
si possible dans la description de l'image de l'histogramme commencer par "disponibilité actuelle" puis "disponibilité max"



![image](https://user-images.githubusercontent.com/106517262/171190416-1516b77b-eb8a-42f7-873a-07c5ae1240d9.png)
