### ISSUE TITLE
Formulaires éléments obligatoires

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2770]
Inscription magistrat ou greffier : 

Le champ de renseignement du tribunal est obligatoire mais il manque l'étoile l'indiquant
![Capture d’écran 2022-01-31 à 11 51 51](https://user-images.githubusercontent.com/86293911/151787807-797e418b-efda-45b2-a5bb-63f6c7469eb9.png)

**Comment by devthejo** [comment]
effectivement j'ai corrigé sur la création de tribunal dans l'admin, pas le signup, c'est fait dans le code, ça arrive avec le prochain déploiement, merci du retour

**Comment by celinelr** [comment]
Je ne valide pas complètement. Je ne devrais pas avoir d'étoile obligatoire pour "cabinet du tribunal". Ce champ n'est pas obligatoire 
![Capture d’écran 2022-02-15 à 12 12 06](https://user-images.githubusercontent.com/86293911/154050945-1a4e761b-da74-4e89-903a-52cdd7c777cf.png)
![Capture d’écran 2022-02-15 à 12 11 46](https://user-images.githubusercontent.com/86293911/154050950-187083fe-31c1-42b2-a10e-102cead1f8ec.png)

**Comment by devthejo** [comment]
sorry, it's bugfixed now, will be on testdb in 10 minutes
