### ISSUE TITLE
En tant qu'admin de service je dois etre reconnue comme tel

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2778]
Au moment de l'inscription d'un mandataire de service, s'il y a un match entre son adresse email et celle du responsable de service renseigné dans la liste blanche, alors il doit obtenir les droits admins de son service

Que se passe t il si l'adresse email change coté liste blanche ou coté utilisateur ? 

-> la personne garde ses droits admin 

Que se passe t il si l'adresse email change coté liste blanche et utilisateur avec la même adresse s'inscrit? 

-> L'ancien admin , reste admin 
-> Le nouvel inscrit qui match avec la nouvelle adresse coté liste blanche devient elle aussi admin

Comme c'est le cas dans mon exemple :

## Test d'acceptance 

SUCCES : 
Etant donné que l'adresse email du mandataire est marilène.picard@astra.fr
Lorsque le champ addresse e-mail du responsable de service est marilène.picard@astra.fr
alors marilène.picard@astra.fr doit avoir les pouvoir admin

ECHEC : 
Etant donné que l'adresse email du mandataire est marilène.picard@astra.fr
Lorsque le champ addresse e-mail du responsable de service est pierre.dupond@astra.fr
alors marilène.picard@astra.fr doit avoir les pouvoir admin

 
SUCCES 
Etant donné que l'adresse email du mandataire responsable à changé est est maintenant pierre.brava@astra.fr
Lorsque le mandataire pierre.brava@astra.fr s'inscrit sur eMJPM
alors pierre.brava@astra.fr et marilène.picard@astra.fr doivent avoir les pouvoirs admins

**Comment by celinelr** [comment]
Si l'adresse e mail rentrée en liste blanche ou sur le profil est identique mais que l'une des deux présente une majuscule alors le match ne se fait pas 

Si je change l'adresse sur liste 


Le nom prenom adresse ne se met pas à jour sur la liste blanche

Le nom prenom adresse ne se met pas à jour sur le profil utilisateur depuis le compte admin emjpm

**Comment by devthejo** [comment]
ça n'a rien à voir avec ce ticket mais je prends note quand même

**Comment by devthejo** [comment]
Pour info: tous ces points n'ont pas vraiment de rapport les uns avec les autres.

1. bug non systématique en rapport avec les donnée de org_gestionnaire (pas forcément visible dans l'interface), si ça provients bien de ce bug qui empêche d'enregistrer le formulaire, c'est maintenant corrigé, sinon je n'ai pas réussi à le reproduire, dis moi...
2. testé en local et sur testdb, pas réussi à reproduire
3. non pas forcément, on peut en discuter, mais contrairement aux autres profiles, le service est créé d'initiative par la liste blanche, il y a donc plusieurs infos déjà remplis côté service, on pourrait faire évoluer et permettre la demande de création de nouveau service depuis le formulaire d'inscription, bref, à discuter...
4. ...
5. Il faudra que tu me montre, je n'ai pas fait de modifications sur cette partie
6. Non, la norme RFC qui détermine le fonctionnement des adresse email définit qu'elles sont case sensitive, donc majuscule et minusculent font la différence, par contre beaucoup de providers d'emails décident (et c'est leur droit) que leurs emails sont case insensitive (en gros chez gmail aucune différence entre majuscule et minuscule, mais un autre provider peut décider d'être case sensitive puisque cela est permis par le protocole standard).
7. Je n'ai pas compris cette histoire de localisation, le mieux c'est que tu me montre ça en direct ou d'échanger sur mattermost

**Comment by celinelr** [comment]
C'est à la création du service que certains champs ne se sauvegardent pas (nom du responsable, prénom du responsable, Localisation)

**Comment by celinelr** [comment]
Merci, je  confirme le correctif/évolution concernant un membre de service pouvant voir le statut des autres membres du service (membre/admin)
