### ISSUE TITLE
Remplacer le composant react-select par un composant select accessible

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/emjpm#2791]
Le composant react-select n'est pas accessible. Nous devons le changer pour une nous permettant d'atteindre nos objectifs d'accessibilité.

**Comment by celinelr** [comment]
## mandataire

### Le select ville dans l'ajout de mesure son label for est différent de son id ID

![Capture d’écran 2022-03-07 à 19 35 07](https://user-images.githubusercontent.com/86293911/157096463-2962f6fe-2d58-4f2f-9106-4bf514ab86e3.png)
![Capture d’écran 2022-03-07 à 19 34 50](https://user-images.githubusercontent.com/86293911/157096468-3fbea10d-f186-4f6d-935b-7ef81c182bec.png)

### Acceptation de mesure > Ville > label for est différent de son id ID

### Mesure  > Ajout d'état > Ville > label for est différent de son id ID

### mesure > Ajout d'une ressource > as tu remplacé le composant react-select pour le champ prestation sociales ? Il se nomme toujours react-select, alors je préfère vérifier avec toi 

![Capture d’écran 2022-03-07 à 19 56 38](https://user-images.githubusercontent.com/86293911/157099844-e71f0a36-d412-4406-a463-0483748f460f.png)

### Modifier vos informations > localisation
- as tu remplacé le composant react-select pour le champ ? Il se nomme toujours react-select, alors je préfère vérifier avec toi 
- L'id utilisée doit etre différente du for car je ne ma retrouve pas

![Capture d’écran 2022-03-07 à 19 59 25](https://user-images.githubusercontent.com/86293911/157100160-2c7131e7-4237-4651-bce9-68d4efd6c8e1.png)

### Modifier vos informations > tribunaux dans lesquels vous exercez
- as tu remplacé le composant react-select pour le champ ? Il se nomme toujours react-select, alors je préfère vérifier avec toi 
- L'id utilisée doit etre différente du for car je ne ma retrouve pas

## Magistrat 

### Vos mesures > les selects nature de la mesure et état de la mesure ont le meme label et pas d'ID
![Capture d’écran 2022-03-07 à 19 41 07](https://user-images.githubusercontent.com/86293911/157097479-48780285-235f-4615-a3bc-3b09c927ac21.png)

### Vos mesures > le select search n'a pas d'ID
![Capture d’écran 2022-03-07 à 19 43 51](https://user-images.githubusercontent.com/86293911/157097746-ca7264f2-7382-455c-8d3f-e9cdd73fac20.png)


### Vos mesures > le select search2 n'a pas d'ID

![Capture d’écran 2022-03-07 à 19 45 22](https://user-images.githubusercontent.com/86293911/157097929-c11387fd-ec48-4286-9de3-bd134dcad13a.png)


## Agent

**Comment by celinelr** [comment]
J'ai tout recetté sur l'envirronement react-select. 

Tout semble bon. J'ai un doute par contre sur le profil magistrat 


### Magistrat
Vos mesures > le select search n'a pas d'ID mais un name= dans l'input
![](https://user-images.githubusercontent.com/86293911/157097746-ca7264f2-7382-455c-8d3f-e9cdd73fac20.png)


Vos mesures > le select search2 n'a pas d'ID mais un name= dans l'input


![](https://user-images.githubusercontent.com/86293911/157097929-c11387fd-ec48-4286-9de3-bd134dcad13a.png)

**Comment by unicscode** [comment]
corrigé. à tester sur sur l'environement rgaa

**Comment by celinelr** [comment]
Merci, je confirme que l'id est ajoutée à la fois sur le profil greffier ainsi que sur celui magistrat
