### ISSUE TITLE
CP Belgique

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#291]
En tant que mandataire, les mesures concernant des majeurs protégés hébergés en Belgique doivent être géolocalisées en Belgique (codes postaux belges actifs) pour éviter qu'elles n'apparaissent au milieu de l'Océan et ne soient ignorées par les agents de l'Etat ou le magistrat.

## Problématique
Des mesures sont localisées en Belgique et n'apparaissent pas sur la carte
La géolocalisation ne fonctionne que pour les communes françaises (hors cedex). Toutefois des majeurs protégés français sont régulièrement pris en charge par des établissements belges car nous n'avons pas en France le type d'accueil proposé en Belgique.
La vue "carte" pour les mandataires et les magistrats n'est donc pas totalement juste et à jour car il manque les mesures portant sur des majeurs français prises en charge par des mandataires exerçant en France mais dont les personnes protégées sont hébergés en Belgique.

## Utilisateur
Mandataires _ magistrats _ agents

## Résultat souhaité
Les mesures de communes en Belgique sont géolocalisées

## Solution
Intégrer les codes postaux de Belgique dans notre base, sur le même modèle que les codes postaux en France.

pistes proposées par Dominique : 
- se connecter à la base commune de Belgique ?
- demander à l'utilisateur de saisir l'url sur google maps, et enregistrer la longitude/ lattitude ?
- afficher sur la carte "des mesures situées en belgique ne son tpas affichées sur la carte mais apparaissent dans la liste" ?
- dans les formulaire, ajouter un champ "Pays", positionné par défaut à France, avec autre option "Belgique" ?

## Critères d'acceptation
- [ ] les majeurs protégés résidant en Belgique apparaissent géolocalisées (en Belgique) sur les vues "carte" des mandataires et des magistrats
- [ ]

**Comment by coraliepelletier** [comment]
@kwiss , on en est où sur la question des codes postaux belges ?

@tous : cette foncitonnalité qui parait complexe à mettre en place techniquement (prise en charge des codes postaux belges) ne me parait pas prioritaire pour la rentrée. Peut-être à mettre dans les priorités 2 (pour décembre 2019) ?

**Comment by coraliepelletier** [comment]
Cette US a été repriorisée aujourd'hui (21 août) suite à des remontées utilisateurs dont @clement-support nous a fait part. @melanie57 précise que les mandataires de toute la France ont besoin de cette fonctionnalité car des majeurs de toute la France sont pris en charge en Belgique où les établissements proposent des services spécifiques que l'on ne trouve pas en France. [vu en daily ce matin].

Au regard du nombre de remontées utilisateurs, cette US est remontée dans le Sprint en cours.
