### ISSUE TITLE
Tests techniques sur les services

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#298]

**Comment by coraliepelletier** [comment]
STOP : discussion le 26 juin 2019, en concertation avec Christophe D, Douglas, Adrien, Coralie, et suite aux éclairages de Jasmine et Mélanie, il a été fait le choix de stopper le temps de dev sur les tests liés aux importations.

En effet, la refonte Ux générale et plus particulièrement la refonte de l'interface SERVICE qui doit intervenir sur l'outil dès la semaine prochaine modifiera l'ensemble des tests à mettre en place. Pour ne pas multiplier le rework inutile, il est décidé de ne pas poursuivre les tests.
