### ISSUE TITLE
ETQ magistrat je souhaite avoir + d'infos sur la zone d'intervention géo des MJPM

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#311]
Problématique

En tant que magistrat je manque d'information sur le lieu d'exercice des mandataires. 
Le problème se pose plus particulièrement pour les mandataires individuels (préposés attachés à un ou plusieurs établissements / service se répartissant entre salariés les mesures pour des tournées cohérentes). L'idée étant d'offrir un maximum d'informations aux juges afin de réduire le temps de trajet des mandataires et ainsi améliorer l'accompagnement des majeurs protégés. 

Utilisateur

Mandataire, magistrat, agent ? : Magistrat

Contexte

Nouvelle feature suite à des retours utilisateurs :
Demande des magistrats notamment de Paris et de mandataires essentiellement individuels. 

Résultat souhaité

- Possibilité pour le magistrats de n'afficher que les mandataires géolocalisés sur la carte. 
- Mise à jour des informations en fonction de l'utilisation de la carte (si je la déplace, si je zoome...)
- Possibilité pour un magistrat d'avoir une vue sur l'ensemble des mesures confiées à un mandataire (a priori fonctionnalité uniquement nécessaire pour les mandataires individuels). 
- Possibilité pour un magistrat de consulter la zone d'intervention géographique privilégiée d'un mandataire (a priori fonctionnalité nécessaire uniquement pour les mandataires individuels). 

Solution

Maquettes

Pas de maquette actuellement 

Critères d'acceptation

# A discuter : 

N'est-il pas nécessaire de faire aider par un UX pour cette carte? 
Faire le lien avec les volonté pour les mandataires de préciser leur zone d'intervention géo privilégiée? 
Fonctionnalité nécessaire que pour les mandataires individuels?

**Comment by coraliepelletier** [comment]
Demande des magistrats : lorsque l'on clique sur un mandataire, seules les mesures prises en charge par ce mandataire apparaissent
