### ISSUE TITLE
ETQ utilisateurs, dans le genre, ajouter "autre"

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#312]
ETQ utilisateurs, dans le genre, ajouter "autre"

## Problématique

_
** fréquence ** : combien de cas actuellement ? 
_
**conséquence** : 
_
**pourquoi/ causes identifées** :

_
## Utilisateur
**mandataire, magistrat, agent ?** : 

_
## Contexte d'utilisation
(quand est-ce que cela se produit dans le parcours utilisateur ?)

_
## Résultat souhaité

_
## Solution

_
## Autres solutions envisagées,rejetées et pourquoi :

_
## Maquettes (optionnel)

_
## A discuter ?
- [ ]  ?
_
## Critères d'acceptation
- [ ] ?
_
## autres stories à voir :
_
carte importée depuis carte trello : https://trello.com/c/H1j77F3W

**Comment by coraliepelletier** [comment]
On reste sur la dénomination légale, quand la loi permettra de dire autre chose que "homme" et "femme" sur les papiers officiels, on reviendra sur ce point.
