### ISSUE TITLE
ETQ MJPM préposé je souhaite pouvoir préciser les établissements dans lesquels j'interviens et ma capacité par établissement

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#315]
ETQ MJPM préposé je souhaite pouvoir préciser les établissements dans lesquels j'interviens et ma capacité par établissement

## Problématique

_
** fréquence ** : combien de cas actuellement ? 
_
**conséquence** : 
_
**pourquoi/ causes identifées** :

_
## Utilisateur
**mandataire, magistrat, agent ?** : Mandataire

_
## Contexte d'utilisation
(quand est-ce que cela se produit dans le parcours utilisateur ?)

_
## Résultat souhaité

_
## Solution

_
## Autres solutions envisagées,rejetées et pourquoi :

_
## Maquettes (optionnel)

_
## A discuter ?
- [ ]  ?
_
## Critères d'acceptation
- [ ] ?
_
## autres stories à voir :
_
carte importée depuis carte trello : https://trello.com/c/t7Po17eH

**Comment by coraliepelletier** [comment]
Possibilité d'ajouter les établissements des préposés 
"préposé" = établissement de santé
Case "nom de l'établissement" = complètement libre
N° SIRET
