### ISSUE TITLE
ETQ utilisateurs, je souhaite accéder à une page de connexion plus smart.

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#319]
ETQ utilisateurs, je souhaite accéder à une page de connexion plus smart.

## Problématique

_
** fréquence ** : combien de cas actuellement ? 
_
**conséquence** : 
_
**pourquoi/ causes identifées** :

_
## Utilisateur
**mandataire, magistrat, agent ?** : NON PRIORITAIRE

_
## Contexte d'utilisation
(quand est-ce que cela se produit dans le parcours utilisateur ?)

_
## Résultat souhaité

_
## Solution
Remplacer la page de connexion actuelle par la page de connexion proposée par Jérémy en modifiant les éléments suivants : 

- Mettre la page d'accueil en couleurs (garder les couleurs de e-mjpm, garder le dessin et le mettre en couleur)

- Enlever le beta 

- Remplacer le texte "guide d'utilisation" par "Aide"

- Modifier le texte à gauche de l'écran par le texte suivant "Une connaissance en temps réel de l'activité des mandataires et de leur disponibilité.
Un référentiel géolocalisé de l'ensemble des professionnels. 
Un meilleur partage de l'information au service du majeur protégé."

- Enlever à droite le "ou" et le logo de France connect - pas de possibilité de s'identifier avec FranceConnect

- Agrandir le cadre à droite de connexion pour une symétrie avec le texte de gauche

La page doit être responsive

_
## Autres solutions envisagées,rejetées et pourquoi :

_
## Maquettes (optionnel)
https://trello-attachments.s3.amazonaws.com/5ae1d4c1ec15c70d6fc31e7c/5c5c2fd6208fa28600ac357b/b6dec3a0ef0c7d8bf22187f22c0f9739/image.png

_
## A discuter ?
- [ ]  ?
_
## Critères d'acceptation
- [ ] ?
_
## autres stories à voir :
_
carte importée depuis carte trello : https://trello.com/c/enokMcol

**Comment by coraliepelletier** [comment]
24.07.2019 > l'Ui de l'ensemble de l'interface eMJPM est en cours de refonte. Je clos cet issue car il est redondant avec d'autres plus précis.
