### ISSUE TITLE
ETQ MJPM, je souhaite pouvoir modifier une mesure réservée.

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#324]
ETQ MJPM, je souhaite pouvoir modifier une mesure réservée.

ETQ MJPM, je souhaite pouvoir modifier manuellement le cabinet des mesures qui me sont attribuées et réservées.

**Comment by coraliepelletier** [comment]
Pouvoir modifier oui, mais pas toutes les données

**Comment by melanie57** [comment]
ETQ mandataires - services / individuels ou préposés - je souhaite pouvoir modifier une mesure réservée

*Problématique / contexte*
Les mandataires sont dans l'incapacité de modifier les données d'une mesure réservée. Or dans certains cas, certaines données peuvent avoir changé ou être erronées.

Utilisateurs
Mandataires (individuels, services, préposés)

Résultat souhaité
Le mandataire a la possibilité de modifier uniquement certaines données de la mesure en attente et non pas la totalité des champs.  En effet, la mesure étant "en attente", elle n'a pas encore officiellement été attribuée au MJPM. Celui-ci n'a pas encore reçu la notification papier du jugement lui permettant de valider la mesure en attente pour la basculer dans ses mesures en cours. 

Solution
- Ajouter une colonne "Référence de la mesure" dans l'onglet "Mesures en attentes" (colonne inexistante à ce jour)
- Ajouter un bouton cliquable "Modifier" (similaire a celui apparaissant dans l'onglet "Mesures en cours") pour chaque mesure en attente. 
- Une fois que l'utilisateur a cliqué sur ce bouton, une fenêtre apparaît lui permettant de modifier les données suivantes :
_Cabinet_
_Numero de dossier_ (catégorie inexistante à ce jour)

*Maquette*
La maquette est très mal faite mais l'idée est la. 
![Screenshot 2019-08-30 at 12.42.41.png](https://images.zenhubusercontent.com/5d08eedda4644173e93beeca/d986a5df-ecfd-416a-801e-15477c381820)

*Critères d'acceptation*
