### ISSUE TITLE
ETQ MJPM, je souhaite pouvoir inclure les mesures de subrogé tutelle ou curatelle.

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#363]
ETQ MJPM, je souhaite pouvoir inclure les mesures de subrogé tutelle ou curatelle.

## Problématique

_
** fréquence ** : combien de cas actuellement ? 
_
**conséquence** : 
_
**pourquoi/ causes identifées** :

_
## Utilisateur
**mandataire, magistrat, agent ?** : 

_
## Contexte d'utilisation
(quand est-ce que cela se produit dans le parcours utilisateur ?)

_
## Résultat souhaité

_
## Solution
Merci de bien vouloir rajouté les catégories suivantes :
Mandat de protection future, Subrogé tuteur et Subrogé curateur

_
## Autres solutions envisagées,rejetées et pourquoi :

_
## Maquettes (optionnel)

_
## A discuter ?
- [ ]  ?
_
## Critères d'acceptation
- [ ] ?
_
## autres stories à voir :
_
carte importée depuis carte trello : https://trello.com/c/NUfE5v0J

**Comment by coraliepelletier** [comment]
fonctionnalité ok _ 24.07.19
