### ISSUE TITLE
ETQ Mandataire , Dans mes informations si le champs est non remplit mettre l'icône ainsi que "non renseigné"

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#373]
ETQ Mandataire , Dans mes informations si le champs est non remplit mettre l'icône ainsi que "non renseigné"

## Problématique

_
** fréquence ** : combien de cas actuellement ? 
_
**conséquence** : 
_
**pourquoi/ causes identifées** :

_
## Utilisateur
**mandataire, magistrat, agent ?** : Mandataire,Magistrat,SERVICES

_
## Contexte d'utilisation
(quand est-ce que cela se produit dans le parcours utilisateur ?)

_
## Résultat souhaité

_
## Solution

_
## Autres solutions envisagées,rejetées et pourquoi :

_
## Maquettes (optionnel)

_
## A discuter ?
- [ ]  ?
_
## Critères d'acceptation
- [ ] ?
_
## autres stories à voir :
_
carte importée depuis carte trello : https://trello.com/c/YwGLlJKb

**Comment by coraliepelletier** [comment]
foncitonnalité ok _ 24.07.2019
