### ISSUE TITLE
CORRECTIONS PARCOURS D'INSCRIPTION

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#391]
CORRECTIONS PARCOURS D'INSCRIPTION
- [ ] Changer le premier titre par "Sélectionnez les régions dans lesquelles vous exercez"

- [ ] Ajouter un message sous le menu déroulant "E-MJPM n'est pas encore disponible partout en France. Si E-MJPM vous intéresse et que vous ne voyez pas votre région, parlons-en (mailto:contact@...)"

- [ ] Une fois la région sélectionnée, faire apparaître une nouvelle section "Choisissez les Tribunaux d'instance dans lesquels vous exercez"
Dans la liste des Tribunaux, supprimer "Tribunal d'instance" pour ne laisser que la ville apparaître

- [ ] Supprimer "(62)" pour Montreuil

- [ ] Dissocier 2 blocs "Vos informations de compte" (ID et Mot de Passe) puis vos informations professionnelles "Nom, adresse, etc."

- [ ] Ajouter une mention sur la page de confirmation "Si vous avez des difficultés pour activer votre compte, contactez nous à contact@emjpm.beta.gouv.fr (mailto)"

- [ ] Envoyer un mail de confirmation à l'utilisateur lui précisant que sa demande à été prise en compte et que son compte est créé - validation automatique du compte.

- [ ] Ecrire Guide d'utilisation plutot que assistance dans le header

- [ ] Faire coller le footer en bas de page

- [ ] Changer le premier titre par "Sélectionnez les régions dans lesquelles vous exercez"

- [ ] Ajouter un message sous le menu déroulant "E-MJPM n'est pas encore disponible partout en France. Si E-MJPM vous intéresse et que vous ne voyez pas votre région, parlons-en (mailto:contact@...)"

- [ ] Une fois la région sélectionnée, faire apparaître une nouvelle section "Choisissez les Tribunaux d'instance dans lesquels vous exercez"

- [ ] Dans la liste des Tribunaux, supprimer "Tribunal d'instance" pour ne laisser que la ville apparaître

- [ ] Supprimer "(62)" pour Montreuil

- [ ] Dissocier 2 blocs "Vos informations de compte" (ID et Mot de Passe) puis vos informations professionnelles "Nom, adresse, etc."

- [ ] Limiter à 3 le nombre de caractères minimum pour l'ID

- [ ] Limiter à 5 le nombre de caractères pour le mot de passe

- [ ] Ajouter une mention sur la page de confirmation "Si vous avez des difficultés pour activer votre compte, contactez nous à contact@emjpm.beta.gouv.fr (mailto)"

- [ ] Envoyer un mail de confirmation à l'utilisateur lui précisant que sa demande à été prise en compte et que son compte est créé

Validation automatique ?

**Comment by kwiss** [comment]
@coraliepelletier @Lucie-0 @Jasminemeurin c'est encore d'actualité ?
