### ISSUE TITLE
ETQ Magistrat,Dans « Mesures en attente » au lieu de « Mesures réservées », la colonne « Référence » est inutile tant qu'on aura pas imposer aux magistrats d'indiquer le n° RG au moment de la réservation

### ISSUE THREAD

**Issue by dlequepeys** [SocialGouv/emjpm#392]
ETQ Magistrat,Dans « Mesures en attente » au lieu de « Mesures réservées », la colonne « Référence » est inutile tant qu'on aura pas imposer aux magistrats d'indiquer le n° RG au moment de la réservation

## Problématique

_
** fréquence ** : combien de cas actuellement ? 
_
**conséquence** : 
_
**pourquoi/ causes identifées** :

_
## Utilisateur
**mandataire, magistrat, agent ?** : A discuter,Magistrat

_
## Contexte d'utilisation
(quand est-ce que cela se produit dans le parcours utilisateur ?)

_
## Résultat souhaité

_
## Solution

_
## Autres solutions envisagées,rejetées et pourquoi :

_
## Maquettes (optionnel)

_
## A discuter ?
- [ ]  ?
_
## Critères d'acceptation
- [ ] ?
_
## autres stories à voir :
_
carte importée depuis carte trello : https://trello.com/c/eUViVqbY

**Comment by coraliepelletier** [comment]
Modification ok (c'est maintenant le N° RG qui apparait).
