### ISSUE TITLE
BUG - Champs "Informations à destination des magistrats"

### ISSUE THREAD

**Issue by gonzalezad1** [SocialGouv/emjpm#425]
Le champs libre "Informations à destination des magistrats" n'apparait pas dans le nouveau profil pour les services.

Ce champs si situe normalement dans l'onglet "Mes informations" et l'utilisateur y a accès en cliquant sur "Modifier mon profil" (voir image ci-jointe).

Merci de rajouter ce champs :
- dans les informations générales du service (siège social - voir ci-joint)
- dans les onglets "Mes informations" de chaque antenne

Faire figurer ces champs dans les "fiches MJPM" mises à disposition des magistrats (voir ci-joint).

Merci

**Comment by coraliepelletier** [comment]
24.07.2019 > Apparemment ça n'apparait toujours pas. Toutefois je cloture cet issue car nous sommes entrain de refondre complètement l'interface eMJPM pour les SERVICES donc il n'est pas nécessaire de traiter ce bug.
