### ISSUE TITLE
DR DD - filtre par région / dept

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#430]
En tant qu'agent de l'Etat en administration centrale (DGCS), en région ou en département, je veux pouvoir filtrer les données e-MJPM sur une base territoriale (mesures par région / mesures par département ) afin d'affiner ma connaissance de l'activité des mandataires sur mon territoire.

## Problématique
L'interface e-MJPM pour les agents de l'Etat répond à une problématique de visualisation de la donnée d'activité sur les territoires. Le tri des données sur une base géographique est particulièrement importante pour les agents. Il convient de qualifier les données (mesures) de manière à pouvoir les rattacher non seulement à un code postal, mais également à une région et un département.

Les codes postaux permettent de rattacher les données à un département et une région.

## Utilisateur
**mandataire, magistrat, agent ?** : agents

## Contexte
Les agents de la DGCS (administration centrale), des directions régionales et des directions départementales ont besoin d'observer l'activité de protection juridique des majeurs sur leur territoire. 
En fonction de son niveau d'intervention (France entière / région / département) les agents auront accès aux données liées à leur territoire. Ils pourront effectuer des recherches en filtrant les données sur la base du rattachement territorial de ces dernières.

## Résultat souhaité
Chaque mesure doit être correctement qualifiée afin d'être géolocalisée (rattachée à une ville) mais aussi rattachée à un département, et une région pour que les filtres appliqués par les agents permettent d'extraire les données qu'ils cherchent (sur 1 région / 1 département ).

## Solution

https://gist.github.com/gzurbach/b0ccdeda51ec2fe135d5

règle 1 : 
- Si les codes postaux commencent par "01" ils sont rattachés au département "01 - Ain"
- Si les codes postaux commencent par "02" ils sont rattachés au département "02 - Aisne"
- Si les codes postaux commencent par "03" ils sont rattachés au département "03 - Allier"
- Si les codes postaux commencent par "04" ils sont rattachés au département "04 - Alpes-de-Haute-Provence"
- Si les codes postaux commencent par "05" ils sont rattachés au département "05 - Hautes-alpes"
- Si les codes postaux commencent par "06" ils sont rattachés au département "06 - Alpes-maritimes"
- Si les codes postaux commencent par "07" ils sont rattachés au département "07 - Ardèche"
- Si les codes postaux commencent par "08" ils sont rattachés au département "08 - Ardennes"
- Si les codes postaux commencent par "09" ils sont rattachés au département "09 - Ariège"
- Si les codes postaux commencent par "10" ils sont rattachés au département "10 - Aube"
- Si les codes postaux commencent par "11" ils sont rattachés au département "11 - Aude"
- Si les codes postaux commencent par "12" ils sont rattachés au département "12 - Aveyron"
- Si les codes postaux commencent par "13" ils sont rattachés au département "13 - Bouches-du-Rhône"
- Si les codes postaux commencent par "14" ils sont rattachés au département "14 - Calvados"
- Si les codes postaux commencent par "15" ils sont rattachés au département "15 - Cantal"
- Si les codes postaux commencent par "16" ils sont rattachés au département "16 - Charente"
- Si les codes postaux commencent par "17" ils sont rattachés au département "17 - Charente-maritime"
- Si les codes postaux commencent par "18" ils sont rattachés au département "18 - Cher"
- Si les codes postaux commencent par "19" ils sont rattachés au département "19 - Corrèze"
- Si les codes postaux commencent par "20100" ils sont rattachés au département "2a - Corse-du-sud"
- Si les codes postaux commencent par "20200" ils sont rattachés au département "2b - Haute-Corse"
- Si les codes postaux commencent par "21" ils sont rattachés au département "21 - Côte-d'Or"
- Si les codes postaux commencent par "22" ils sont rattachés au département "22 - Côtes-d'Armor"
- Si les codes postaux commencent par "23" ils sont rattachés au département "23 - Creuse "
- Si les codes postaux commencent par "24" ils sont rattachés au département "24 - Dordogne"
- Si les codes postaux commencent par "25" ils sont rattachés au département "25 - Doubs"
- Si les codes postaux commencent par "26" ils sont rattachés au département "26 - Drôme"
- Si les codes postaux commencent par "27" ils sont rattachés au département "27 - Eure "
- Si les codes postaux commencent par "28" ils sont rattachés au département "28 - Eure-et-loir"
- Si les codes postaux commencent par "29" ils sont rattachés au département "29 - Finistère"
- Si les codes postaux commencent par "30" ils sont rattachés au département "30 - Gard"
- Si les codes postaux commencent par "31" ils sont rattachés au département "31 - Haute-garonne"
- Si les codes postaux commencent par "32" ils sont rattachés au département "32 - Gers"
- Si les codes postaux commencent par "33" ils sont rattachés au département "33 - Gironde"
- Si les codes postaux commencent par "34" ils sont rattachés au département "34 - Hérault"
- Si les codes postaux commencent par "35" ils sont rattachés au département "35 - Ille-et-vilaine"
- Si les codes postaux commencent par "36" ils sont rattachés au département "36 - Indre "
- Si les codes postaux commencent par "37" ils sont rattachés au département "37 - Indre-et-loire"
- Si les codes postaux commencent par "38" ils sont rattachés au département "38 - Isère"
- Si les codes postaux commencent par "39" ils sont rattachés au département "39 - Jura"
- Si les codes postaux commencent par "40" ils sont rattachés au département "40 - Landes"
- Si les codes postaux commencent par "41" ils sont rattachés au département "41 - Loir-et-cher"
- Si les codes postaux commencent par "42" ils sont rattachés au département "42 - Loire"
- Si les codes postaux commencent par "43" ils sont rattachés au département "43 - Haute-loire"
- Si les codes postaux commencent par "44" ils sont rattachés au département "44 - Loire-atlantique"
- Si les codes postaux commencent par "45" ils sont rattachés au département "45 - Loiret"
- Si les codes postaux commencent par "46" ils sont rattachés au département "46 - Lot "
- Si les codes postaux commencent par "47" ils sont rattachés au département "47 - Lot-et-garonne"
- Si les codes postaux commencent par "48" ils sont rattachés au département "48 - Lozère"
- Si les codes postaux commencent par "49" ils sont rattachés au département "49 - Maine-et-loire"
- Si les codes postaux commencent par "50" ils sont rattachés au département "50 - Manche"
- Si les codes postaux commencent par "51" ils sont rattachés au département "51 - Marne"
- Si les codes postaux commencent par "52" ils sont rattachés au département "52 - Haute-marne"
- Si les codes postaux commencent par "53" ils sont rattachés au département "53 - Mayenne"
- Si les codes postaux commencent par "54" ils sont rattachés au département "54 - Meurthe-et-moselle"
- Si les codes postaux commencent par "55" ils sont rattachés au département "55 - Meuse"
- Si les codes postaux commencent par "56" ils sont rattachés au département "56 - Morbihan"
- Si les codes postaux commencent par "57" ils sont rattachés au département "57 - Moselle"
- Si les codes postaux commencent par "58" ils sont rattachés au département "58 - Nièvre "
- Si les codes postaux commencent par "59" ils sont rattachés au département "59 - Nord"
- Si les codes postaux commencent par "60" ils sont rattachés au département "60 - Oise "
- Si les codes postaux commencent par "61" ils sont rattachés au département "61 - Orne"
- Si les codes postaux commencent par "62" ils sont rattachés au département "62 - Pas-de-calais"
- Si les codes postaux commencent par "63" ils sont rattachés au département "63 - Puy-de-dôme"
- Si les codes postaux commencent par "64" ils sont rattachés au département "64 - Pyrénées-atlantiques "
- Si les codes postaux commencent par "65" ils sont rattachés au département "65 - Hautes-Pyrénées"
- Si les codes postaux commencent par "66" ils sont rattachés au département "66 - Pyrénées-orientales"
- Si les codes postaux commencent par "67" ils sont rattachés au département "67 - Bas-rhin"
- Si les codes postaux commencent par "68" ils sont rattachés au département "68 - Haut-rhin"
- Si les codes postaux commencent par "69" ils sont rattachés au département "69 - Rhône"
- Si les codes postaux commencent par "70" ils sont rattachés au département "70 - Haute-saône"
- Si les codes postaux commencent par "71" ils sont rattachés au département "71 - Saône-et-loire"
- Si les codes postaux commencent par "72" ils sont rattachés au département "72 - Sarthe"
- Si les codes postaux commencent par "73" ils sont rattachés au département "73 - Savoie"
- Si les codes postaux commencent par "74" ils sont rattachés au département "74 - Haute-savoie"
- Si les codes postaux commencent par "75" ils sont rattachés au département "75 - Paris"
- Si les codes postaux commencent par "76" ils sont rattachés au département "76 - Seine-maritime"
- Si les codes postaux commencent par "77" ils sont rattachés au département "77 - Seine-et-marne"
- Si les codes postaux commencent par "78" ils sont rattachés au département "78 - Yvelines"
- Si les codes postaux commencent par "79" ils sont rattachés au département "79 - Deux-sèvres"
- Si les codes postaux commencent par "80" ils sont rattachés au département "80 - Somme"
- Si les codes postaux commencent par "81" ils sont rattachés au département "81 - Tarn"
- Si les codes postaux commencent par "82" ils sont rattachés au département "82 - Tarn-et-garonne "
- Si les codes postaux commencent par "83" ils sont rattachés au département "83 - Var "
- Si les codes postaux commencent par "84" ils sont rattachés au département "84 - Vaucluse"
- Si les codes postaux commencent par "85" ils sont rattachés au département "85 - Vendée"
- Si les codes postaux commencent par "86" ils sont rattachés au département "86 - Vienne"
- Si les codes postaux commencent par "87" ils sont rattachés au département "87 - Haute-vienne"
- Si les codes postaux commencent par "88" ils sont rattachés au département "88 - Vosges"
- Si les codes postaux commencent par "89" ils sont rattachés au département "89 - Yonne"
- Si les codes postaux commencent par "90" ils sont rattachés au département "90 - Territoire de belfort"
- Si les codes postaux commencent par "91" ils sont rattachés au département "91 - Essonne"
- Si les codes postaux commencent par "92" ils sont rattachés au département "92 - Hauts-de-seine"
- Si les codes postaux commencent par "93" ils sont rattachés au département "93 - Seine-Saint-Denis"
- Si les codes postaux commencent par "94" ils sont rattachés au département "94 - Val-de-marne"
- Si les codes postaux commencent par "95" ils sont rattachés au département "95 - Val-d'oise"

règle 2 : 
- Si le département est 01 _ 07 _ 15 _ 26 _ 38 _ 42 _ 43 _ 63 _ 69 _ 73 _ 74 ; la région associée est " Auvergne-Rhône-Alpes "
- Si le département est 21 _ 25 _ 39 _ 58 _ 70 _ 71 _ 89 _ 90 ; la région associée est " Bourgogne-Franche-Comté "
- Si le département est 22 _ 29 _ 35 _ 56 ; la région associée est " Bretagne "
- Si le département est 18 _ 28 _ 36 _ 37 _ 41 _ 45 ; la région associée est " Centre-Val de Loire "
- Si le département est 2A _ 2B ; la région associée est " Corse "
- Si le département est 08 _ 10 _ 51 _ 52 _ 54 _ 55 _ 57 _ 67 _ 68 _ 88 ; la région associée est " Grand Est "
- Si le département est 02 _ 59 _ 60 _ 62 _ 80 ; la région associée est " Hauts-de-France "
- Si le département est 75 _ 77 _ 78 _ 91 _ 92 _ 93 _ 94 _ 95 ; la région associée est " Île-de-France "
- Si le département est 14 _ 27 _ 50 _ 61 _ 76 ; la région associée est " Normandie "
- Si le département est 16 _ 17 _ 19 _ 23 _ 24 _ 33 _ 40 _ 47 _ 64 _ 79 _ 86 _ 87 ; la région associée est " Nouvelle Aquitaine "
- Si le département est 09 _ 11 _ 12 _ 30 _ 31 _ 32 _ 34 _ 46 _ 48 _ 65 _ 66 _ 81 _ 82 ; la région associée est " Occitanie "
- Si le département est 44 _ 49 _ 53 _ 72 _ 85 ; la région associée est " Pays de la Loire "
- Si le département est 04 _ 05 _ 06 _ 13 _ 83 _ 84 ; la région associée est " Provence-Alpes-Côte d'Azur "

## Maquettes (optionnel)
Je vous mets ici un extrait du wireframe correspondant à cette première US : nous souhaitons rattacher la donnée à sa région et à son département afin que les agents puissent trier les données suivant les filtres ci-dessous en jaune :

![extrait de wireframe _ filtres.PNG](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/5e3e7396-db75-48eb-9db9-b2607d107f35)

## Critères d'acceptation
- [ ] chaque filtres doit être fonctionnel
- [ ] le choix d'un critère donne lieu à une mise à jour direct sans qu'aucune autre action ne soit nécessaire
- [ ] les filtres doivent tous être combinable pour affiner le filtrage de la donnée de la manière la plus fine possible 
- [ ] ces filtres doivent être présent sur les pages suivantes : (home de la partie agent régional ou départemental)[à compléter]
- [ ] chaque filtre donne lieu à un rafraichissement des données des cartes concerné de la page
- [ ] en cas de rafraichissement de la page, les filtres se remettent à zéro et les données de l'ensemble de la France sont présentées

**Comment by ChrisMP75** [comment]
**UX**

Pour **Région**, nous avons accès à la liste de toutes les régions de France. Nous pouvons en sélectionner une seule ou plusieurs à l’aide des checkbox. Si nous sélectionnons Toutes les régions, la checkbox active des régions cliquées manuellement disparaît pour se répercuter sur la checkbox Toutes les régions.

Un système d’auto complétion permet de chercher les région directement en tapant sur clavier (vu et validé avec Christophe Dumont)

Pour **Département**, la liste des départements affichés dépend des régions sélectionnées dans Région. Le système de recherche et de sélecteur est exactement le même pour les trois boutons **Région**, **Département** et **Tribunal**.



Pour **Tribunal**, nous affichons la liste des tribunaux en fonction des sélecteurs **Région** et **Département**

Ex 1 : Si nous sélectionnons uniquement Auvergne Rhône-Alpes, nous aurons accès à la liste des départements pour Auvergne et Rhônes-Alpes. In fine, dans le sélecteur **Tribunal**, nous aurons uniquement la liste des Tribunaux répertoriés pour Auvergne Rhône-Alpes.

Ex 2 : Si nous décidons d’affiner notre recherche dans un département Rhône Alpes Auvergne en sélectionnant uniquement le département Puy de Dôme, nous aurons accès à la liste des tribunaux répertoriés dans le Puy de Dôme.

**Comment by kwiss** [comment]
- [ ] il manque actuellement les migration pour les régions que @tglatt doit faire en revenant
