### ISSUE TITLE
page connexion DR DD

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#443]
En tant qu'agent de l'Etat (DR DD DGCS) je veux me connecter sur un espace personnel au sein de eMJPM afin d'avoir accès aux données contenues dans le produit

## Problématique
L'interface e-MJPM pour les agents de l'Etat répond à une problématique de visualisation de la donnée d'activité sur les territoires. Les agents doivent avoir accès à une interface dédiée à leur type de profil ("agents"), qui leur donne accès aux données présentes dans eMJPM suivant leur niveau d'accréditation :
- les agents de la DGCS ont accès à toutes les données
- les agents de niveau Direction Régionale ont accès aux statistiques nationales ET aux données sur leur territoire (une seule région, tous les départements liés et tous les tribunaux d'instance liés)
- les agents de niveau Direction Départementale ont accès aux statistiques nationales ET aux données sur leur région (sur leur département, les tribunaux d'instance liés MAIS AUSSI les données des autres départements de leur région pour pouvoir se comparer).

## Utilisateur
**mandataire, magistrat, agent ?** : agents

## Contexte
Les agents de la DGCS (administration centrale), des directions régionales et des directions départementales qui prennent en charge des missions de suivi de la Protection Juridique des majeurs doivent avoir accès à leur interface DR - DD - DGCS, qui est dans sa version intiale (actuelle) un dashboard de suivi statistique. Les agents doivent avoir accès aux données détaillées sur leur territoire et aux données des territoires limitrophes :
* Un agent en département a accès aux données de son départements ET des autres départements de sa région (pour pouvoir se comparer)
* Un agent en Région a accès aux données de sa région et aux données nationales
* Un agent à la DGCS a accès aux données sur toutes les régions / tous les départements

## Résultat souhaité
Le parcours d'inscription des agents doit aboutir à relier chaque compte à un territoire et un niveau de droit (administration centrale / région / département).
Attention, un compte a accès à 1 niveau de droits, en revanche un même niveau adminsitratif sera représenté par plusieurs comptes (à la DGCS, on peut anticiper 4 à 10 comptes utilisateurs, pour chaque DR entre 3 et 10 utilisateurs, pour chaque DD entre 1 et 5 utilisateurs par exemple).

## Solution
- les agents doivent s'inscrire en ligne de manière autonome. Le parcours d'inscription doit contenir une étape de validation de leur profil par leur hiérarchie ou par l'équipe eMJPM
- le parcours d'inscription doit contenir une étape de choix de leur territoire d'exercice au sein d'une liste déroulante comprenant l'ensemble des régions et des départements.

## Maquettes (optionnel)
Les maquettes de l'interface DR - DD - DGCS ne comprennent pas l'écran d'inscription. A ce stade, il semble opportun de reprendre la page d'inscription eMJPM standard, comprenant les champs suivants :
- Prénom NOM
- Territoire d'exercice [liste déroulante comprenant l'ensemble des régions et des départements]

![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/3f549963-0127-464a-9aa7-19d00c605b88)

## Critères d'acceptation
- [ ] Les champs nom et prénom doivent être fonctionnels
- [ ] La liste déroulante de choix du territoire d'appartenance doit être fonctionnelle
- [ ] le choix d'un item dans la liste déroulante "territoire d'exercice" doit induire l'accès aux données de ce territoire uniquement
- [ ] 
- [ ] 
- [ ]

**Comment by coraliepelletier** [comment]
Un point reste à voir avec Jamsine et Lucie : la validation des comptes doit-elle être prévue par voie hiérarchique ou une validation des comptes par l'équipe eMJPM serait suffisante ?

Je demande à la DGCS si un référentiel à jour des agents cohésion sociale dédiés à la PJM existe (avec noms et adresses mail) _ auquel cas on pourrait créer les comptes en amont du lancement en spetembre. Dans tous les cas une inscription en ligne est nécessaire pour les nouveaux arrivants dans le domaine.

**Comment by Lucie-0** [comment]
A mon sens pas besoin de validation hiérarchique pour l'accès à e-MJPM. Si on peut ne pas ajouter de la lourdeur à un outil que se veut facile d'utilisation, c'est mieux. 

Surtout pas de création de comptes au niveau national (règle n1) : d'une part la DGCS ne sera jamais à jour des référents MJPM dans les territoires (qui sont amenés à changer régulièrement sans que la DGCS en soit informée) ET si on procède de la sorte cela nous oblige à gérer tous les comptes. trop de complexité.

**Comment by Lucie-0** [comment]
DONNEES PROPOSEES EN FONCTION DU NIVEAU D'ACCREDITATION : 

"Les agents de niveau Direction Départementale ont accès aux statistiques nationales ET aux données sur leur territoire (un seul département et tous les tribunaux d'instance liés)" : il ne me semble pas légitime de réduire autant les informations dont disposent les agents du niveau départemental : a minima leur ouvrir les informations régionales (région rattachée à leur département) et les informations des autres départements de cette même région.

**Comment by Lucie-0** [comment]
POSSIBILITE D'AVOIR PLUSIEURS COMPTES PAR DPMT / REGION / AU NIVEAU NATIONAL

Possibilité d'avoir plusieurs comptes pour un même département / une même région ou pour le niveau national.

**Comment by coraliepelletier** [comment]
Les commentaires ont été traités et la carte retravaillée

Vu avec les filles :
- plusieurs comptes par niveaux administratifs _ intégré à la carte
- les agents en département ont accès aux données sur toute leur région d'appartenance _ intégré à la carte
- pas de validation hiérarchique des inscriptions, liberté de création de compte _ intégré à la carte
