### ISSUE TITLE
3 onglets DR - DD

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#536]
En tant qu'agent de l'Etat en administration centrale (DGCS), en région ou en département, je veux avoir accès à une interface dédiée comportant 3 onglets afin d'avoir accès à l'ensemble des informations contenues dans eMJPM qui peuvent m'intéresser.

## Problématique
L'interface e-MJPM pour les agents de l'Etat répond à une problématique de visualisation de la donnée d'activité sur les territoires. Les données à afficher et les modalités d'affichage sont nombreuses, aussi il a été choisi de les répartir en 3 catégories (= 3 onglets).

## Utilisateur
**mandataire, magistrat, agent ?** : agents

## Contexte
Les agents de la DGCS (administration centrale), des directions régionales et des directions départementales ont besoin d'observer l'activité de protection juridique des majeurs sur leur territoire. 
Les agents auront accès aux données liées à leur territoire suivant 3 onglets : "mesures" / "mandataires" / "population protégée"

## Résultat souhaité
- l'onglet "MESURES" donne à voir les données contenues dans eMJPM sous l'angle statistique des mesures attribuées et gérées sur un territoire (nombre de mesures / type de mesures ...)
- l'onglet "MANDATAIRES" donne à voir les données contenues dans eMJPM sous l'angle de l'activité des mandataires (taux d'occupation des mandataires / disponibilités ...)
- l'onglet "POPULATION PROTEGEE" donne à voir les données contenues dans eMJPM sous l'angle des staistiques se rapportant à la population des majeurs (hommes - femmes / pyramide des âges ...)

[EDIT] l'onglet sur lequel l'agent est connecté par défaut est l'onglet MANDATAIRES 

## Solution
Préparer une interface avec 3 onglets

## Maquettes
https://projects.invisionapp.com/share/7USWWVBF3K2#/screens/373153386_0-1_-_V2_-_Portail_DR-DD_-_Vue_Mesure

![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/9cd359ee-a9c5-4dba-99ff-74ff3a499aab)

## Critères d'acceptation
- [ ] Lorsque je me connecte en tant qu'agent de l'Etat, j'ai accès à 3 onglets 
- [ ] Par défaut j'arrive sur l'onglet "mesures"
- [ ] Lorsque je clique sur l'onglet "mandataires" j'accède aux données et graphiques portant sur l'activité des mandataires
- [ ] Lorsque je clique sur l'onglet "données démographiques" j'accède aux données et graphiques portant sur les informations relatives aux populations de majeurs protégés

**Comment by coraliepelletier** [comment]
ATTENTION : l'onglet par défaut sera l'onglet "mandataires" dès la version 2 de l'interface ; pour le moment cet onglet "mandataires" est en cours de refonte par Lucie avec Christophe M. aussi nous pensons laissé cet onglet "mesures" comme onglet par défaut dans cette v1.

Point peut-être à discuté en Review

**Comment by coraliepelletier** [comment]
L'onglet par défaut est l'onglet MANDATAIRES - la maquette est en cours de redéfinition.

**Comment by kwiss** [comment]
je passe cet tache en review on peut éventuellement en ouvrir une pour la partie donnée demo mais pas obligé
