### ISSUE TITLE
onglet "mesures" nombre de "mesures en cours"

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#539]
En tant qu'agent de l'Etat en administration centrale (DGCS), en région (DR) ou en département (DD), je veux lire dans l'onglet "mesures" le nombre de "mesures en cours" en haut à gauche de l'onglet "mesures" (onglet par défaut du profil "agents de l'Etat")

## Problématique
Le nombre de mesures en cours sur un territoire est l'un des indicateurs d'activité les plus importants pour les agents de l'Etat. Cette donnée fondamentale est par ailleurs aujourd'hui mal connue (peu précise) au niveau national. Pouvoir avoir rapidement accès à cette donnée, et de manière fiable, est l'une des avancées principale de eMJPM pour les utilisateurs "agents de l'Etat".

## Utilisateur
**mandataire, magistrat, agent ?** : agents

## Contexte
Les agents de la DGCS (administration centrale), des directions régionales et des directions départementales ont besoin d'observer l'activité de protection juridique des majeurs sur leur territoire et de pouvoir en rendre compte. Le nombre de "mesures en cours" est une donnée fondamentale, qui sera régulièrement consultée, à tous les niveaux.

**Définition de "mesure en cours" : ce sont les mesures ouvertes à la date de consultation de la page, hors "mesures réservées" (non confirmées donc non comptabilisées) et hors "mesures fermées".**

## Résultat souhaité
Lorqu'un agent de l'Etat se connecte sur l'interface DGCS - DR - DD, il voit apparaitre en haut à gauche de son dashboard (cf. maquette ci-dessous) le nombre de mesures en cours (correspondant à la définition ci-dessus). Ce nombre est mit à jour en temps réel, et est valable à la date de connexion de l'agent sur l'interface.

## Solution
La base de données doit recencer les dates d'ouverture et de fermeture des mesures afin de permettre de recenser les mesures "en cours" à chaque date de connexion (et sur une période de référence).

## Maquettes
![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/76ba8b41-6d75-4019-be3b-55de59b5c156)

## Critères d'acceptation
- [ ] Lorsque je me connecte en tant qu'agent de l'Etat, le nombre de "mesures en cours" (c'est-à-dire non réservées et non fermées) à la date du jour apparait en haut à gauche. Ce chiffre est fiable.

**Comment by tglatt** [comment]
- [x] La partie backend 
- [  ] front end

**Comment by kwiss** [comment]
why close this issue @tglatt ?

**Comment by tglatt** [comment]
my bad!!
