### ISSUE TITLE
onglet MESURES - nombre de "nouvelles mesures"

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#541]
En tant qu'agent de l'Etat en administration centrale (DGCS), en région (DR) ou en département (DD), je veux lire dans l'onglet "mesures" le nombre de "nouvelles mesures" depuis une date définie dans le bandeau de haut de page, en haut à centre-droite de l'onglet "mesures" (onglet par défaut du profil "agents de l'Etat")

## Problématique
Les nouvelles mesures (ou "mesures ouvertes") sont les mesures que les juges viennent de prononcées. 
Au début d'une mesure, le travail des mandataires est plus important que dans la gestion courrante de la mesure. Dans les premiers mois de gestion d'une mesure par un mandataire, celui-ci a un peu plus de travail (il ne connait pas le majeur, ne connait pas la famille, ne connait pas le patrimoine ...), le temps de faire tout le travail adminsitratif et d'apprendre à connaitre le majeur et sa situation, le madataire connait une période de surcroit d'activité. Au regard de cette sur-activité, les agents de l'état souhaitent savoir si le nombre de "nouvelles mesures" est important ou non.
Le nombre de "nouvelles mesures" sur une période est aussi un bon indicateur de tendance : si le nombre de mesures nouvelles est important, ça indique que les disponibilités des mandataires vont continuer à décroitre dans les mois suivants.

## Utilisateur
**mandataire, magistrat, agent ?** : agents

## Contexte
Les agents de la DGCS (administration centrale), des directions régionales et des directions départementales ont besoin d'observer l'activité de protection juridique des majeurs sur leur territoire et de pouvoir anticiper les tendances.

**Définition de "nouvelles mesures" : mesures dont la date d'ouverture est comprise entre les dates indiquées ans le filtre" (par défaut du 1er janvier de l'année en cours à la date du jour de connexion).**

## Résultat souhaité
Lorqu'un agent de l'Etat se connecte sur l'interface DGCS - DR - DD, il voit apparaitre en haut à droite-centre de son dashboard, dans le bandeau du haut de page (cf. maquette ci-dessous), le nombre de "nouvelles mesures" (correspondant à la définition ci-dessus) sur son territoire. Ce nombre est mit à jour à cahque connexion.

En cas de non précision de la période, les chiffres s'affichent pour une période par défaut du 1er janvier de l'année en cours jusqu'à la date de connexion.

## Solution
La base de données doit pouvoir être triée par date d'ouverture des mesures.
Le nombre de "nouvelles mesures" indique le nombre de mesures dont les dates d'ouverture correspondent à la période indiquée dans les filtres.

## Maquettes
![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/ef28c1fc-8df8-4589-a283-f800e1b9ab86)

## Critères d'acceptation
- [ ] Lorsque je me connecte en tant qu'agent de l'Etat, le nombre de "nouvelles mesures" (ouvertes entre les dates indiquées dans le filtre) apparait dans le bandeau du haut de page. Ce chiffre est fiable.

**Comment by tglatt** [comment]
- [x] backend  https://github.com/SocialGouv/emjpm/pull/562 `getNewMesuresNumber`
- [] frontend
