### ISSUE TITLE
onglet MESURES - "mesures éteintes"

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#542]
En tant qu'agent de l'Etat en administration centrale (DGCS), en région (DR) ou en département (DD), je veux lire dans l'onglet "mesures" le nombre de "mesures éteintes" depuis une date définie dans les filtres en haut de page, en haut à droite de l'onglet "mesures".

ETQ agent de l'Etat (DGCS - DR - DD) je souhaite voir apparaitre sur l'onglet "mesures" le nombre de "mesures éteintes" depuis une date précise

## Problématique
Les mesures éteintes sont les mesures arrêtées (décès du majeur, levée de la mesure ...). 
Comme au début, la fin de la mesure nécessite un surcroit de travail pour les mandataires professionnels par rapport à une gestion courrante de la mesure. Pour suivre le travail des mandataires sur son territoire ; et pou anticiper les tendances sur leurs territoires, les agents de l'Etat souhaitent voir le nombre de mesures éteintes sur une période.

## Utilisateur
**mandataire, magistrat, agent ?** : agents

## Contexte
Les agents de la DGCS (administration centrale), des directions régionales et des directions départementales ont besoin d'observer l'activité de protection juridique des majeurs sur leur territoire et de pouvoir anticiper les tendances.

**Définition de "mesures éteintes" : mesures dont la date de fermeture est comprise entre les dates indiquées dans le filtre" (par défaut du 1er janvier de l'année en cours à la date du jour de connexion).**

## Résultat souhaité
Lorqu'un agent de l'Etat se connecte sur l'interface DGCS - DR - DD, il voit apparaitre en haut à droite de son dashboard, dans le bandeau du haut de page (cf. maquette ci-dessous), le nombre de "mesures éteintes" (correspondant à la définition ci-dessus) sur son territoire. Ce nombre est mit à jour à chaque changement des dates dans le filtre (à chaque nouvelle connexion, la date de fin est mise à jour pour être la date du jour).

En cas de non précision de la période, les chiffres s'affichent pour une période par défaut du 1er janvier de l'année en cours jusqu'à la date de connexion.

## Solution
La base de données doit pouvoir être triée par date de fermeture des mesures (pour les mesures qui ne sont plus en cours)
Le nombre de "mesures éteintes" indique le nombre de mesures dont les dates de fermeture correspondent à la période indiquée dans les filtres.

## Maquettes
![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/4bdb9e7a-c1cc-47e2-97c6-4d53e4576566)

## Critères d'acceptation
- [ ] Lorsque je me connecte en tant qu'agent de l'Etat, le nombre de "mesures éteintes" (fermées entre les dates indiquées dans le filtre) apparait dans le bandeau du haut de page. Ce chiffre est fiable.

**Comment by tglatt** [comment]
- [x] backend
