### ISSUE TITLE
onglet MESURES _ tri par type de mesures

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#545]
En tant qu'agent de l'Etat en administration centrale (DGCS), en région (DR) ou en département (DD), je veux voir les mesures classées par type de mesures de protection (tutelle / curatelle renforcée / curatelle simple / sauvegarde de justice / autres).

## Problématique
Les mesures de protection juridique des majeurs sont de déifférentes natures, plus ou moins lourdes à gérer pour les mandataires. Les agents de l'Etat ont besoin de connaitre la proportion de chaque type de mesure dans l'activité des mandataires de leur territoire. Cette donnée qualitative n'est pas ou mal connue des agents de l'Etat actuellement.

## Utilisateur
**mandataire, magistrat, agent ?** : agents

## Contexte
Les mesures de protection juridique des majeurs sont de différents types, chacune représentant une charge de travail différente pour les mandataires (et un coût différent pour l'Etat, chaque type de mesure étant chiffré de manière différente). Aussi pour tenir les budgets, les agents de l'Etat on besoin de connaitre les grandes tendances des types de mesures sur leurs territoires pour anticiper les besoins de financement des mandataires sur les territoires.

## Résultat souhaité
En fonction du secteur géographique identifié dans les filtres, les types de mesures apparaissent sous format de graphique en baton selon 4 catégories :
- Tutelles
- Curatelles simples
- Curatelles renforcées
- Sauvegarde de justice
- autre
La catégorie "autre" doit recenser tous les autres types de mesures existantes, la liste à importable doit donner le détail de ces autres mesures.

Les agents de l'Etat doivent pouvoir télécharger la liste complète des mesures triée par type de mesures.

**ATTENTION : la liste des types de mesures est aujourd'hui très complète (suite à une réforme), les données doivent être qualifiée finement et donner accès à la liste détaillée par type de mesure - incluant les nouveaux types de mesures. Cette liste des types de mesures est à récupérer auprès du ministère de la justice**

## Solution
En fonction du secteur géographique et des dates identifiés dans les filtres, les mesures sont sélectionnées. Ces mesures sélectionnées sont réparties en 4 catégories pour les faire apparaitre en diagramme baton :
- Tutelles
- Curatelles simples
- Curatelles renforcées
- Sauvegarde de justice
- autre (tous les types de mesures hors tutelle / curatelle renforcée / curatelle simple / sauvegarde de justice doivent être intégrés dans le décompte "autre")

Les données ainsi triées sont exportables en format excel ou CSV. cet export indique le détail du type de mesure pour les mesures hors tutelle / curatelle renforcée / curatelle simple / sauvegarde de justice.

## Maquettes
![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/0284c6bd-9352-46ed-b596-bb576ae5075c)

## Critères d'acceptation
- [ ] le diagramme présente 5 barres verticales
- [ ] les barres représentent les catégories tutelle / curatelle renforcée / curatelle simple / sauvegarde de justice / autre
- [ ] les chiffres sont justes et adaptés au territoire et aux dates sélectionnées
- [ ] l'export est fonctionnel
- [ ] les données du document exporté sont lisibles, justes et détaillées

**Comment by tglatt** [comment]
@coraliepelletier, je pense qu'il faudra séparer l'export excel du reste. Les exports excels correspondent à une tache particulière.

**Comment by tglatt** [comment]
- [x] backend https://github.com/SocialGouv/emjpm/pull/562
- [] frontend

**Comment by kwiss** [comment]
j'ai vu un bug avec des mesures à moitié renseigné, je ne les ai pas compté du coup
