### ISSUE TITLE
ETQ agent de l'Etat (DGCS - DR - DD) je souhaite voir les mesures de mon territoire triées par état "en attente" / "en cours" / "éteintes" à date

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#546]
En tant qu'agent de l'Etat en administration centrale (DGCS), en région (DR) ou en département (DD), je veux voir la répartition des mesures sur mon territoire et à la date de consultation de la page dans les filtres suivant leur caractéristique "en attente" / "en cours" / "éteintes" afin d'observer les rapports entre mesures actives et non actives.

## Problématique
Le produit gère des données de mesures actives ("en cours") et de mesures non-actives ("en attente" ou "éteintes"). Les agents de l'Etat ne savent pas aujourd'hui quantifier le rapport entre mesures en actives et mesures non actives sur leur territoire. C'est une clef de lecture qui leur permet d'estimer des tendances d'activité et donc de programmer les évolutions budgétaires nécessaires pour les mois et années à venir. (le pilotage de la politique publique aux niveaux locaux et nationaux reposera sur ces tendances grâce à eMJPM).

## Utilisateur
**mandataire, magistrat, agent ?** : agents

## Contexte
eMJPM permet de suivre une mesure depuis sa réservation jusqu'à son extinction (du moment où le juge prononce la mesure au moment où cette mesure de protection prend fin). Il existe 3 états pour une mesure dans eMJPM :
- "en attente" (= "réservée")
- "en cours"
- " éteinte"

## Résultat souhaité
En fonction du secteur géographique identifié dans les filtres, le décompte des mesures apparait sous format de chiffre et de pourcentage pour les 3 catégories :
- Mesures en Cours
- Mesures en attente
- Mesures éteintes

Les agents de l'Etat doivent pouvoir télécharger la liste complète des mesures triée par état en cliquant sur l'icone en haut à droite du carré.

## Solution
En fonction du secteur géographique identifié dans les filtres, les mesures sont sélectionnées. Ces mesures sélectionnées sont réparties en 3 suivant l'état des mesures.
Le décompte se fait au jour de la consultation ("à date"), c'est-à-dire :
- les mesures en cours à date de la consultation de la page
- les mesures en attentes à date de la consultation de la page
- les mesures éteintes depuis 3 mois en arrière maximum depuis la date de consultation de la page
Pour chacune les données extraites sont : le nombre total sur le territoire par état de mesure & le pourcentage de chaque catégorie dans l'ensemble des mesures sur le territoire.

Les données ainsi triées sont exportables en format excel ou CSV. cet export indique le détail du type de mesure pour les mesures en cours / en attente / éteintes.

## Maquettes
![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/1d07d533-11f5-40b6-a04c-7774b5b7c398)

## Critères d'acceptation
- [ ] le nombre de mesures en cours est présenté
- [ ] la part de mesures en cours dans le nombre de total de mesures sur le territoire apparait sous format de pourcentage
- [ ] le nombre de mesures en attente est présenté
- [ ] la part de mesures en attente dans le nombre de total de mesures sur le territoire apparait sous format de pourcentage
- [ ] le nombre de mesures éteintes (depuis maximum 3 mois) est présenté
- [ ] la part de mesures éteintes (depuis maximum 3 mois) dans le nombre de total de mesures sur le territoire apparait sous format de pourcentage
- [ ] les chiffres doivent être justes et mis à jour à date

**Comment by tglatt** [comment]
@coraliepelletier, @ChrisMP75 sur la maquette on ne comprends pas que les mesures éteintes sont uniquement celles des 3 derniers mois.

**Comment by coraliepelletier** [comment]
Suite à la remarque de @tglatt, nous avons revu l'onglet MESURES avec @ChrisMP75 et nous avons retiré cette visualisation de l'onglet.
