### ISSUE TITLE
DR-DD tri par état "en attente" / "en cours" / "éteintes"

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#547]
En tant qu'agent de l'Etat en administration centrale (DGCS), en région (DR) ou en département (DD), je veux voir la répartition des mesures sur mon territoire et suivant la période indiquée par les dates précisées dans les filtres suivant leur caractéristique "en attente" / "en cours" / "éteintes" afin d'observer les rapports entre mesures actives et non actives.

## Problématique
Le produit gère des données de mesures actives ("en cours") et de mesures non-actives ("en attente" ou "éteintes"). Les agents de l'Etat ne savent pas aujourd'hui quantifier le rapport entre mesures en actives et mesures non actives sur leur territoire. C'est une clef de lecture qui leur permet d'estimer des tendances d'activité et donc de programmer les évolutions budgétaires nécessaires pour les mois et années à venir. (le pilotage de la politique publique aux niveaux locaux et nationaux reposera sur ces tendances grâce à eMJPM).

## Utilisateur
**mandataire, magistrat, agent ?** : agents

## Contexte
eMJPM permet de suivre une mesure depuis sa réservation jusqu'à son extinction (du moment où le juge prononce la mesure au moment où cette mesure de protection prend fin). Il existe 3 états pour une mesure dans eMJPM :
- "en attente" (= "réservée")
- "en cours"
- " éteinte"

## Résultat souhaité
En fonction du secteur géographique et de la période identifiés dans les filtres, le décompte des mesures apparait sous format de chiffre et de pourcentage pour les 3 catégories :
- Mesures en cours
- Mesures en attente
- Mesures éteintes

Les agents de l'Etat doivent pouvoir télécharger la liste complète des mesures triée par état et l'évolution de chaque catégorie sur la période en cliquant sur l'icone en haut à droite du carré.

## Solution
En fonction du secteur géographique et de la période identifiés dans les filtres, les mesures sont sélectionnées. Ces mesures sélectionnées sont réparties en 3 suivant l'état des mesures.
Le décompte se fait sur la période de consultation, c'est-à-dire :
- les mesures "en cours" du début à la fin de la période demandée, sur la période de consultation
- les mesures ouvertes sur la période de consultation
- les mesures éteintes sur la période de consultation 
Pour chacune les données extraites sont : le nombre total sur le territoire par état de mesure sur la période & l'évolution de chaque catégorie dans l'ensemble des mesures sur le territoire.

Les données ainsi triées sont exportables en format excel ou CSV. cet export indique le détail du type de mesure pour les mesures en cours / en attente / éteintes et les évolutions de chaque catégorie sur la période.

## Maquettes
![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/f7056a46-c7df-4482-b502-b4dee5e4fde3)

## Critères d'acceptation
- [ ] le nombre de mesures en cours sur la période est présenté
- [ ] l'évolution du nombre de mesures en cours sur la période apparait 
- [ ] le nombre de mesures en attente sur la période est présenté
- [ ] l'évolution du nombre de mesures en attente sur la période apparait 
- [ ] le nombre de mesures éteintes sur la période est présenté
- [ ] la part de mesures éteintes sur la période apparait
- [ ] les chiffres doivent être justes et mis à jour à date

**Comment by tglatt** [comment]
@coraliepelletier 

*les mesures "en cours" du début à la fin de la période demandée, sur la période de consultation*
__Question__:  cela veut dire:
 - cas 1: `date_debut` < date_ouverture < `date_fin`
 - cas 2: `date_ouverture` < `date_debut` && (date_extinction IS NULL || date_extinction > `date_fin`)
 - cas n : ...
__Il faut redéfinir la notion de en cours sur une période__

*les mesures ouvertes sur la période de consultation*
- `date_debut` < date_ouverture < `date_fin`

les mesures éteintes sur la période de consultation
*les mesures ouvertes sur la période de consultation*
- `date_debut` < date_extinction < `date_fin`
