### ISSUE TITLE
DR-DD évolution du nombre de mesure trié par type

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#548]
En tant qu'agent de l'Etat en administration centrale (DGCS), en région (DR) ou en département (DD), je veux voir l'évolution du nombre de mesure trié par type de mesures (tutelle / curatelle renforcée / curatelle simple / sauvegarde de justice / autre / total) afin de pouvoir lire et anticiper les tendances sur mon territoire.

## Problématique
Aujourd'hui les agents de l'Etat n'ont pas de lisibilité des tendances d'activité des mandataires sur leurs territoires. Cette absence de visibilité est un point de difficulté majeur pour les agents qui ne peuvent pas anticiper la mise en place des procédures de recrutement des mandataires ou les tendances budgétaires prévisionnelles.

## Utilisateur
**mandataire, magistrat, agent ?** : agents

## Contexte
eMJPM permet de suivre le nombre et la répartition des mesures par type de mesures. Au fur et à mesure de son utilisation, des courbes de tendances se dessinerons, mois par mois.

## Résultat souhaité
En fonction du secteur géographique et de la période identifiés dans les filtres, le décompte des mesures par type de mesure apparait sous format de courbes.
- tutelle
- curatelle renforcée
- curatelle simple
- sauvegarde de justice
- autre
- une ligne total doit agréger les 5 autres tendances 

Lorsque l'on passe la souris sur une courbe, le nombre de mesures apparait (voir 2e écran de maquette ci-dessous).

Les agents de l'Etat doivent pouvoir télécharger la liste complète des mesures triée par type de mesures et réparties dans le temps, en cliquant sur l'icone en haut à droite du carré.

## Solution
En fonction du secteur géographique et de la période identifiés dans les filtres, les mesures sont sélectionnées et triées par type de mesures. 

Le décompte se fait mois par mois sur la période de consultation.
A défaut de choix dans le filtre en haut de page, le décompte s'effectue à partir du 1er janvier de l'année en cours.

Les données ainsi triées sont exportables en format excel ou CSV. 

**ATTENTION : qu'y a-t-il dans le "filtre" en haut du graphique ?**

## Maquettes
![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/9e5f1df0-cb09-426a-b9b0-b4fac492e839)

![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/39cea9e5-bd29-4270-805e-b329b3a07bd3)

## Critères d'acceptation
- [x] les mesures sont triées par types
- [x] les nombre de mesures classées par types sont réparties chronologiquement (un chiffre par mois), ceci dessine des courbes de tendance
- [ ] les chiffres sont justes

**Comment by coraliepelletier** [comment]
Vérifier auprès de Christophe M. ce que recoupe le filtre "filtrer par : mesures" ?

**Comment by tglatt** [comment]
@coraliepelletier 

__Question__: Pour chaque mois, on compte le nombre de mesure ouverte dans le mois?
