### ISSUE TITLE
[mandataires] Liste des mandataires pour DR/DD

### ISSUE THREAD

**Issue by Lucie-0** [SocialGouv/emjpm#552]
ETQ agents cohésion sociale - accès DR/DD - onglet mandataires je veux pouvoir avoir accès à des informations précises mandataires par mandataires.  

En tant qu'agent de l'Etat en administration centrale (DGCS), en région (DR) ou en département (DD), je veux pouvoir avoir accès à des données similaires à celles dont disposent les magistrats afin d'avoir un maximum d'informations sur les professionnels exerçant sur mon territoire. 

# Problématique 
Les maquettes telles que proposées actuellement ne permettent pas aux agents de la cohésion sociale  d'avoir une visibilité précise sur l'activité mandataire par mandataire et leur fiche information. Il ressort des retours faits que les agents souhaitent avoir au moins autant d'informations dont celles que disposent les magistrats. 

# Utilisateurs
Agents cohésion sociale : DGCS / DR / DD

# Contexte
Les agents cohésion sociale ont besoin d'observer l'activité de protection juridique des majeurs sur leur territoire et le profil des professionnel de manière individuelle. En ajoutant en premier lieu sur l'onglet mandataire une carte des professionnels et la liste associée comme c'est le cas pour les magistrats, les agents auront accès à ces informations. 

# Solution 
 Ajouter avant les stat. actuellement proposées une carte et la liste des professionnels comme c'est le cas pour l'accès Justice.
Interface eMJPM DR / DD - onglet mandataires : 
Tri : Région / département / TI 
Puis dessous 

A gauche une carte, dont le zoom (France, région ou département) est défini en fonction du tri effectué, faisant apparaître un point par professionnel, avec une couleur distincte en fonction du type de professionnels : services, individuels ou préposés. 

A droite : la liste des professionnels telle qu'elle apparaît pour les magistrats avec leur disponibilité et en cliquant sur le professionnel voulu la possibilité d'avoir accès à sa fiche information. 

Ajouter la possibilité sur cette première barre d'informations de faire un tri par type de mandataires : services / individuels ou préposés comme c'est le cas aujourd'hui dans l'accès magistrat. 

# Critères d'acceptation
- [ ] une carte fonctionnelle sur laquelle on peut zoomer / dézoomer
- [ ] les professionnels facilement identifiables sur cette carte
- [ ] fonctionnalité des deux filtes : territoires / professionnels 
- [ ] possibilité d'ouvrir la fiche information en cliquant sur le nom du professionnel.

**Comment by coraliepelletier** [comment]
Au regard de la nature des données, il est décidé que les agents de l'Etat ont également accès aux données d'activité des autres régions et autres départements, pour plus de simplicité de gestion. Si une iterration doit être afite sur ce point, elle le sera pour décembre.
