### ISSUE TITLE
[mandataires] DR-DD _ onglet mandataires _ capacité des professionnels

### ISSUE THREAD

**Issue by Lucie-0** [SocialGouv/emjpm#559]
ETQ agent de l'Etat, volet DR-DD, onglet mandataires je veux avoir accès à un graphique illustrant la capacité des professionnels 

Graphique tel qu'il est présenté dans les maquettes :

![Capture d’écran 2019-07-15 à 17.53.19.png](https://images.zenhubusercontent.com/5d244af23f19ff7f4112fabf/fe793803-27a1-4c44-a4ba-f5666fa1269f)

- ajouter le nom du professionnel à la verticale sur la barre le concernant 
- préciser entre parenthèse individuel service ou préposé
- possibilité de faire des tris en fonction du type de mandataire (individuels, préposé, établissement)
- tri en fonction de la dispo ou non dispo

**Comment by kwiss** [comment]
Comme vu ensemble caché pour l'instant + verifier l'utilisé auprès des utilisateurs cc @coraliepelletier @Lucie-0
