### ISSUE TITLE
Incohérence de texte modifier une mesure

### ISSUE THREAD

**Issue by Lucie-0** [SocialGouv/emjpm#594]
ETQ mandataire (services, individuels ou préposés) je veux pouvoir modifier une mesure.

## Problématique - contexte
ETQ mandataire (services, individuels ou préposés) Lorsque je clique sur « modifier » dans modifier une mesure, une fenêtre « ouvrir une nouvelle mesure » s'affiche. 

## Utilisateur
**mandataire, magistrat, agent ?** : mandataires

## Résultat souhaité
Les mandataires doivent pouvoir modifier les mesures de leur profil.

## Solution
Modifier le titre de la fenêtre 
Il faut corriger le texte pour qu'apparaisse le texte "modification de la mesure"
et vérifier que les fonctionnalités intégrées dans la fenêtre alors ouverte sont bien des fonctionnalités permettant de modifier une mesure préalablement sélectionnée.

## Maquettes (optionnel)

 ![image.png](https://images.zenhubusercontent.com/5d244af23f19ff7f4112fabf/ffecb899-99ed-4f10-8651-14b707a261a5)

## Critères d'acceptation
- [ ] lorsque je clique sur "modification de la mesure" une fenêtre s'ouvre
- [ ] au sein de la fenêtre alors ouverte, le mandataire peut modifier la mesure choisie 
- [ ] au sein de la fenêtre alors ouverte, les données de la mesure choisie / à modifier sont pré-remplies
- [ ] lorsque les informations sur la mesure sont modifiées et que le mandataire enregistre les modifications, les données qui apparaissent dans l'outil sont les données mises à jour.

**Comment by coraliepelletier** [comment]
[ ] Est-ce qu'on est sûrs que seul le titre est à revoir ?
[ ] Est-ce que ça pourrait servir / est-ce que l'on pourrait ajouter quelque part la date de modifications des données ?
