### ISSUE TITLE
modifier une mesure sans numéro RG

### ISSUE THREAD

**Issue by Lucie-0** [SocialGouv/emjpm#595]
ETQ mandataires - services / individuels ou préposés - je souhaite pouvoir modifier une mesure et finaliser la modification de la mesure sans être bloqué par l'obligation de remplir le numéro RG. 

## Problématique / contexte
Lorsqu'un mandataire souhaite modifier une mesure, un numéro RG manquant semble être un élément bloquant. Aucune validation des modifications ne peut être faite et un message d'erreur peu clair apparait à l'écran du mandataire.

Or le mandataire eut faire le choix de ne pas remplir le numéro RG sur le produit eMJPM. Cette décision ne doit pas être bloquante pour son utilisation de l'outil. 

## Utilisateurs
Mandataires (individuels, services, préposés)

## Résultat souhaité
Pas de blocage et pas de message d'erreur en cas d'absence de numéro RG.

## Solution
Retirer le test automatique / le blocage automatique
Retirer le message d'erreur.

## Maquettes
![image.png](https://images.zenhubusercontent.com/5d244af23f19ff7f4112fabf/0b765aac-558b-489f-a7dd-a0c0f3d4492f)

## Critères d'acceptation
- [ ] les modifications de mesures sont possibles pour les mandataires y compris en l'absence de numéro RG
- [ ] la validation des modifications est fonctionnelle
- [ ] aucun message d'erreur n'apparait
- [ ] si un message d'avertissement apprait, celui-ci doit être rédigé en français (administration publique oblige)

**Comment by coraliepelletier** [comment]
@Lucie-0 : est-ce vrai que le numéro RG n'est pas obligatoire dans l'utilisation de eMJPM ?
@kwiss : peut-on envisager la fonction d'import sans obliger à utiliser un numéro de référence unique pour chaque mesure (numéro RG) ?

**Comment by Lucie-0** [comment]
@coraliepelletier : effectivement le n° RG n'est pas obligatoire dans l'utilisation d'e-MJPM. Il n'est d'ailleurs pas pris en compte il me semble lors de l'importation des mesures (j'ai fait une carte pour remédier à cela). Quid du double référencement des mesures : n° RG et référence de la mesure (champ libre).
