### ISSUE TITLE
Interface administrateurs

### ISSUE THREAD

**Issue by Lucie-0** [SocialGouv/emjpm#597]
En tant qu'administrateur du produit eMJPM (équipe produit - nous), je veux pouvoir agir sur les comptes des utilisateurs afin de solutionner leurs problématiques et répondre efficacement aux demandes de support utilisateurs.

**Nota Bene** les bonnes pratiques en matière de support visent à rendre les utilisateurs les plus autonomes possibles avant de considérer faire à leur place.

## Problématique - contexte
Actuellement l'équipe produit est sollicitée pour apporter du support aux utilisateurs mais manque de moyens pour agir sur les comptes des utilisateurs et ne peut donc pas apporter satisfaction.
Un profil dédié au support intègre l'équipe au 5 août 2019, des outils opérants ou une procédure rodée doit être mise en place d'ici là pour que ce profil ait les moyens de sa mission.

**attention au nécessaire respect du RGPD**
revue @ThomasHonnet

## Utilisateurs
équipe produit eMJPM (nous ;) )

## Résultat souhaité
1 / Accéder aux mesures des mandataires pour effectuer des modifications
2 / Effacer des mesures entrées en doublon par erreur (US#308)
3/ Modifier les informations des mandataires
4/ Modifier leurs mots de passe et identifiants **OU** générer identifiants et mots de passe temporaires ?
5 / Importer les tableaux à la place des mandataires (tant que cette solution d'import Excel est conservée)
6/ Supprimer des comptes utilisateurs existants

7/ ETQ Administrateur, je souhaite que les informations rentrées dans la fiche d'inscription apparaissent dans la section "Gestion des utilisateurs"
8/ Quand je me connecte en tant qu'admin, dans l'onglet "Gestion des utilisateurs", je souhaite que la colonne "En attente" apparaisse avant la colonne "Actifs"

## Solutions 
1/ Ouvrir les fonctionnalités décrites ci-dessus aux utilisateurs directement (développement de nouvelles features) 
- US#308 les mandataires peuvent supprimer des mesures 
- US#617 les mandataires peuvent retrouver leur mot de passe
- US#618 les mandataires peuvent supprimer un compte

2 / Permettre aux administrateurs de prendre la main sur les comptes des utilisateurs (se connecter "en tant que" tel ou tel utilisateur réel)

3/ Rédiger des US #support et dédier du temps de DEV pour réaliser ces modifications au jour le jour directement dans la base de données 

## Maquettes
Pas de maquettes prévues sur ce sujet.

## Critères d'acceptation
- [ ] la solution est accessible à tout administrateur du produit (notamment @clement_support, @melanie57 , et les PO)
- [ ] la solution doit être sécurisée, conforme du point de vue RGPD (@thomashonnet) 
- [ ] la solution retenue doit être fonctionnelle c'est-à-dire permettre d'apporter une réponse aux demandes de support en 48h
- [ ] la solution doit permettre de garder la trace des actions effectuées (et idéalement quelle personne de l'équipe les a effectué)

**Comment by coraliepelletier** [comment]
Pour Revue @Lucie-0 et @kwiss :)
