### ISSUE TITLE
ETQ mandataire (services, individuels, préposés) je veux pouvoir en cas de modification d'une mesure, que soient préciser les raisons. 

### ISSUE THREAD

**Issue by Lucie-0** [SocialGouv/emjpm#622]
# Problématique : 

Actuellement, il y a un flou sur les modifications de mesures en cas de renouvellement / aggravation / allègement des mesures.Les MJPM doivent-il modifier la mesure en cours ou doivent-ils mettre fin au mandat pour ensuite le recréer? Quels impacts sur les statistiques? Quelles directives données aux mandataires sur cette situation? 

# Solution :

- Communiquer sur la modification de mesure - changer la date? 
- Ajouter la possibilité de préciser les raisons de la modification d'une mesure

**Comment by coraliepelletier** [comment]
Mettre la possibilité d'afficher des dates complémentaires notamment :
- la date du jugement (qui elle reste et est fixe)
- la date du dernier renouvellement
- la date de l'agravation de la mesure

Quand la mesure est renouvellée / modifier il faut pouvoir le préciser
