### ISSUE TITLE
MVP Magistrats _ liste des MANDATAIRES _ release 18.09

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#720]
En tant que Magistrat, je veux avoir accès à une interface très simplifiée de eMJPM du 15 septembre au 30 septembre 2019, afin de ne connaitre aucune coupure de service, notamment éviter la suspension de la fonctionnalité de réservation de mesures auprès des services.

## Utilisateur
MAGISTRATS

## Problématique
La refonte du profil SERVICES travaillé durant l'été 2019 a une date de mise en production prévue le 18 septembre 2019. Or la mise en production de ce nouveau profil SERVICES induit une casse importante sur le profil magistrats, qui ne peuvent notamment plus réserver de mesure auprès des services.

## Résultat souhaité
Pour que les magistrats puissent continuer à réserver des mesures auprès des services mandataires tout au long de la mise en ligne des nouvelles features pour les services, il faut que le profil magistrat allégé contienne la liste complète des mandataires de leur territoire (liste similaire à la liste du profil DR DD).

Cette liste doit pouvoir être filtrée par région et par département (filtres identiques aux filtres sur DR DD).

## Maquettes
![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/19ec1fcc-b2b2-49cc-9c69-7e32bcc50fff)

## Critères d'acceptation
- [ ] les magistrats peuvent réserver une mesure auprès d'un service
- [ ] la liste des mandataires apparaît sous format de liste ordonnée quand les magistrats se connecte

**Comment by coraliepelletier** [comment]
Idéalement, cette liste doit pouvoir être filtrée par tribunal mais pour le moment on n'a pas le filtre TI.

**Comment by tglatt** [comment]
@coraliepelletier, étant donné que les magistrats ne peuvent voir que les mandataires / services associés à leur tribunal, le filtre par tribunal est inutile. non?

**Comment by tglatt** [comment]
@coraliepelletier, les filtres par région et département ne me semblent pas pertinents étant donné que le magistrat ne voit que les mandataires / services associés à son tribunal. Pour le moment, les filtres sont 'type de mandataire' et tri par capacité.

**Comment by coraliepelletier** [comment]
@tglatt : si nous pouvons donner à voir uniquement les mandataires affiliés à un tribunal, en effet les filtres ne servent pas. tu as raison, les filtres région, départements, tribunaux ne sont pas pertinents. Seuls les filtres par **type de mandataires** et par **disponibilité** sont pertinents. Merci pour ta vigilance :)
