### ISSUE TITLE
Feat/service-mesure-remove

### ISSUE THREAD

**Issue by kwiss** [SocialGouv/emjpm#736]
Il faut pouvoir supprimer une mesure quand elle est éteinte.

La suppression de mesure est une fonctionnalité nouvelle mais essentielle pour limiter le support. Le bouton peut être implémenter de différentes manières, nous en choisissons une ici, peut-être à revoir par la suite

## Utilisateurs
Mandataires (indivuels / services / préposés) _ ici il s'agit du profil SERVICES, mais la fonctionnalité sera à dupliquer sur les profils individuels et proposés dès que possible.

## Problématique - contexte
Les utilisateurs entrent de "fausses" mesures, souvent pour tester l'outil. Or aucune fonctionnalité ne permet aux utilisateurs de supprimer les mesures une fois que celles-ci sont enregistrées dans l'outil. 
Le bouton "fin de mandat" (#738) ne permet pas de supprimer vraiment la mesure : une mesure éteinte entre en compte dans les statistiques. Une mesure "supprimée" en revanche doit être totalement effacée de l'outil.

## Résultat souhaité
une mesure en cours peut être "fermée" grâce au bouton "fin de mandat" (#738).
Une mesure "fermée" ou "éteinte" peut être réactivée (#735) ou définitivement supprimée.

Dans l'onglet "mesures éteintes", en cliquant sur le bouton "supprimer une mesure" un message d'alerte spécifique doit apparaître dans fenêtre pop up à priori (sauf meilleure solution d'affichage) indiquant à l'utilisateur que sa démarche est irréversible.
Exemple de message à faire apparaître  : "Vous êtes sur le point de supprimer définitivement une mesure de protection du système eMJPM. Toute suppression est irreversible, vous ne pourrez pas récupérer les données associées à cette mesure et celle-ci disparaîtra des statistiques d'activité produites par eMJPM à destination des magistrats et des agents de l'Etat. Si vous souhaitez supprimer définitivement cette mesure, cliquez sur "valider". 
Dans le cas contraire, cliquez sur "annuler", vous reviendrez sur l'onglet de vos mesures éteintes, celles-ci ne sont plus comptabilisées dans votre activité actuelle mais apparaissent dans les statistiques nationales et dans votre historique d'activité sur eMJPM. "

Deux boutons sont présents sous le message d'avertissement :
- "valider"
- "annuler"

Lorsque l'utilisateur valide l'annulation en cliquant sur "valider", l'ensemble des données relatives à la mesure sont effacées de la base de données.

**Comment by coraliepelletier** [comment]
Nous nous sommes questionnés sur deux points quant à la "suppression des mesures" :

1. est-ce que le bouton "suppression de la mesure" doit se trouver après le bouton "fin de mandat" dans le parcours utilisateurs. Ce positionnement va peut-être posé question aux utilisateurs, voir leur sembler inaccessible ( "mettre fin" à une "fausse" mesure avant de pouvoir l'effacer définitivement serait un comportement un peu étonnant ...). Les autres solutions évoquées : mettre dans la liste des raisons d'extinction d'une mesure "effacer définitivement car c'est une erreur / je me suis trompé.e" ; ou ouvrir une fenêtre pop up au moment d'appuyer sur le bouton "mettre fin au mandat" proposant soit de mettre fin au mandat, soit de supprimer définitivement la mesure, soit d'annuler pour revenir en arrière et garder la mesure active.

2. est-ce que la "suppression" définitive d'une mesure par un utilisateur doit conduire à l'effacement réel et définitif de toutes les données (on a pensé que ce serait plus sécurisé au niveau gestion (RGPD) de la donnée mais peut-être risqué aux vues des fausses manipulations) ; ou est-ce que les données doivent être effacées de la vue des utilisateurs mais être conservées dans la base de données (avec le bon flagage) pour pouvoir être récupérées en cas de fausse manipulation par un utilisateur.
