### ISSUE TITLE
Feat/service-mesure-close

### ISSUE THREAD

**Issue by kwiss** [SocialGouv/emjpm#738]
il faut pouvoir ferme une mesure en cour via un bouton de fermeture

<img width="1111" alt="Capture d’écran 2019-09-13 à 14 05 50" src="https://user-images.githubusercontent.com/243668/64861175-9bf76700-d62f-11e9-9d16-737ed6bf4a8b.png">

il faut pouvoir donner des informations sur la fermeture via un panel qui s'ouvre 
<img width="606" alt="Capture d’écran 2019-09-13 à 14 06 04" src="https://user-images.githubusercontent.com/243668/64861212-ae71a080-d62f-11e9-9c53-e81a8b621004.png">

La **raison de l'extinction de la mesure** doit être remplie à partir d'un **menu déroulant**
![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/e45b5232-7e3c-408e-ba99-ab7fb804e792)

 ## Utilisateurs
Mandataires (indivuels / services / préposés) _ ici il s'agit du profil SERVICES, mais la fonctionnalité sera à dupliquer sur les profils individuels et proposés dès que possible.

## Problématique - contexte
Il existe plusieurs raisons pour lesquelles une mesure de protection juridique de majeur prend fin (la mesure s'arrête, la personne est décédée, ...). La mesure de protection a bien eu lieu et elle est finie. L'outil eMJPM doit pouvoir tracer ces mesures là pour des raisons statistiques.
Par ailleurs, il faut une date de fermeture car cette étape représente une surcharge de travail pour les mandataires (dans les 3 mois qui suivent la fermeture d'une mesure, les mandataires doivent gérer la clôture du dossier en quelque sorte).

On parle de "fermeture d'une mesure [de protection]", "d'extinction d'une mesure [de protection]" ou de "fin de mandat [de protection]" pour dire que la mesure de protection a pris fin. Suite à ça, on parle de "mesure éteinte". Pour les raisons de traçabilité évoquée ci-dessus, **une mesure éteinte n'est pas supprimée** .

## Résultat souhaité
Dans la liste des mesures en cours, un bouton apparaît pour chaque mesure permettant de "mettre fin au mandat". 

La fin de mandat doit être motivée, et une liste déroulante de "raison d’extinction de la mesure" appairait, ces raisons sont listées au sein d'un menu déroulant (ou tout autre format de meilleur design). La liste des raisons d'extinction d'une mesure est à retrouver dans le code de la version précédente de l'application, une ligne "erreur dans la saisie de la mesure" doit être ajoutée aux raisons d'extinction pour permettre le traitement statistique différencié des vraies fermetures de mesure et des erreurs de saisie. 

L'utilisateur choisi une raison dans la liste puis clique sur un bouton "valider".

Une fois la mesure fermée, c'est-à-dire que l'utilisateur a cliqué sur "mettre fin au mandat" puis a choisi une raison d'extinction et a validé son action, la mesure change de statut et se retrouve dans l'onglet "mesures éteintes".

**Comment by coraliepelletier** [comment]
@kwiss : les raisons d'extinction à ajouter dans le mette dans le menu déroulant (la "raison d'extinction de la mesure" n'est pas un champ libre) : 
- caducité
- changement de mandataires
- changement de tribunal d'instance
- décès
- main levée
- erreur de saisie [nouveauté]
- autre
