### ISSUE TITLE
Feat/service-mesure-edit

### ISSUE THREAD

**Issue by kwiss** [SocialGouv/emjpm#739]
il faut pouvoir editer une mesure en cour via un bouton de modification

<img width="1111" alt="Capture d’écran 2019-09-13 à 14 05 50" src="https://user-images.githubusercontent.com/243668/64861268-cc3f0580-d62f-11e9-8dc1-6dcc7ba9a7f7.png">

il faut pouvoir editer les informations via un panel qui s'ouvre.

<img width="607" alt="Capture d’écran 2019-09-13 à 14 07 47" src="https://user-images.githubusercontent.com/243668/64861305-e1b42f80-d62f-11e9-840e-7d884ea696d8.png">

 ## Utilisateurs
Mandataires (individuels / services / préposés) _ ici il s'agit du profil SERVICES, mais la fonctionnalité sera à dupliquer sur les profils individuels et proposés dès que possible.

## Problématique - contexte
Les données intégrées aux mesures entrées dans l'outil eMJPM ne sont pas toujours bonnes d'une part et d'autre part, les mesures de protection peuvent évoluer (souvent s’aggraver, et théoriquement s'alléger). Aussi il faut que les utilisateurs puissent modifier les informations relatives aux mesures.

## Résultat souhaité
En cliquant sur le bouton "modifier la mesure" l'utilisateur doit avoir accès à une fenêtre pop up permettant de modifier les informations relatives à la mesure. Un bouton "valider" doit se trouver en bas de la fenêtre de modifications. La validation des modifications (cliquer sur le bouton "valider") entraîne la fermeture de la fenêtre et l'enregistrement des modifications dans la base de données.

**Comment by coraliepelletier** [comment]
Attention : une fois le numéro RG rentré, il faudrait qu'il ne puisse plus être modifié car c'est notre clef de comparaison pour les imports (avec le code postal du tribunal). La modification du N°RG entraînerait l'impossibilité de comparer les données entre les imports et donc empêcherait la mise à jour des données.
