### ISSUE TITLE
[MAGISTRAT] ajouter le cabinet dans la mutation de creation de la mesure

### ISSUE THREAD

**Issue by kwiss** [SocialGouv/emjpm#937]
- [x] ajouter le cabinet dans la mutation de creation de la mesure d'un mandataire ou d'un service

**Comment by tglatt** [comment]
- [ ] permettre de modifier le cabinet à la création de la mesure
- [ ] permettre de modifier le cabinet  l'édition de la mesure
- [ ] afficher le tribunal et le cabinet dans la liste des mesures coté service et mandataire

**Comment by tglatt** [comment]
#940
