### ISSUE TITLE
[MAGISTRAT] Afficher le tribunal et le cabinet dans la liste des mesures

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#963]
Un magistrat du TI avec plusieurs cabinet a besoin de voir sur quel cabinet est une mesure.

- [ ] Comme pour le profil service, ajouter le tribunal et le cabinet dans la liste des mesures

**Comment by kwiss** [comment]
y en a qu'un normalement non ?

**Comment by tglatt** [comment]
pour un magistrat on affiche toutes les mesures de son tribunal. Donc il n'y a q'un tribunal mais plusieurs cabinets.
Ils ont besoin de voir le cabinet sur les mesures.

**Comment by tglatt** [comment]
Un magistrat ne voit que ses mesures et non celles de tout le tribunal.
